SELECT CD_LOJ, CD_VEN, SUM(VL_PAR)
FROM PARCELA P
GROUP BY (CD_LOJ, CD_VEN)
ORDER BY (CD_LOJ);


SELECT NM_LOJ "Loja", V.CD_VEN "Venda", COUNT(*) "Parcelas", SUM(VL_PAR) "Total Venda",  AVG(VL_PAR) "Média Parcelas"
FROM PARCELA P, LOJA L, VENDA V
WHERE P.CD_LOJ = V.CD_LOJ
  AND P.CD_VEN = V.CD_VEN
  AND V.CD_LOJ = L.CD_LOJ  
GROUP BY NM_LOJ, V.CD_VEN
  HAVING SUM(VL_PAR) BETWEEN 400 AND 600
ORDER BY NM_LOJ, V.CD_VEN;


