;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 4/3/2008 13:24:49
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2921			GOTO	_main
$0004	$	_i2c_is_idle:
;I2C_c34.ppas,22 :: 		
;I2C_c34.ppas,23 :: 		
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$01A7			CLRF	_i2c_is_idle_local_result, 1
;I2C_c34.ppas,24 :: 		
$0007	$3000			MOVLW	0
$0008	$1683			BSF	STATUS, RP0
$0009	$1914			BTFSC	SSPSTAT, 2
$000A	$3001			MOVLW	1
$000B	$00F1			MOVWF	STACK_1
$000C	$0871			MOVF	STACK_1, 0
$000D	$3A00			XORLW	0
$000E	$1D03			BTFSS	STATUS, Z
$000F	$281A			GOTO	I2C_c34_L_11
$0010	$	I2C_c34_L_10:
;I2C_c34.ppas,25 :: 		
$0010	$301F			MOVLW	31
$0011	$0511			ANDWF	SSPCON2, 0
$0012	$00F1			MOVWF	STACK_1
$0013	$0871			MOVF	STACK_1, 0
$0014	$3A00			XORLW	0
$0015	$1D03			BTFSS	STATUS, Z
$0016	$281A			GOTO	I2C_c34_L_14
$0017	$	I2C_c34_L_13:
$0017	$30FF			MOVLW	255
$0018	$1283			BCF	STATUS, RP0
$0019	$00A7			MOVWF	_i2c_is_idle_local_result
$001A	$	I2C_c34_L_14:
$001A	$	I2C_c34_L_15:
$001A	$	I2C_c34_L_11:
$001A	$	I2C_c34_L_12:
$001A	$	I2C_c34_L_9:
;I2C_c34.ppas,26 :: 		
$001A	$1303			BCF	STATUS, RP1
$001B	$1283			BCF	STATUS, RP0
$001C	$1303			BCF	STATUS, RP1
$001D	$1283			BCF	STATUS, RP0
$001E	$0827			MOVF	_i2c_is_idle_local_result, 0
$001F	$00F0			MOVWF	STACK_0
$0020	$0008			RETURN
$0021	$	_i2c_start:
;I2C_c34.ppas,34 :: 		
;I2C_c34.ppas,35 :: 		
$0021	$1303			BCF	STATUS, RP1
$0022	$1283			BCF	STATUS, RP0
$0023	$01A5			CLRF	_i2c_start_local_j
$0024	$01A6			CLRF	_i2c_start_local_j+1
$0025	$	I2C_c34_L_17:
$0025	$0826			MOVF	_i2c_start_local_j+1, 0
$0026	$3C12			SUBLW	18
$0027	$1D03			BTFSS	STATUS, Z
$0028	$282B			GOTO	L_I2C_Start_0
$0029	$0825			MOVF	_i2c_start_local_j, 0
$002A	$3C8E			SUBLW	142
$002B	$	L_I2C_Start_0:
$002B	$1C03			BTFSS	STATUS, C
$002C	$283F			GOTO	I2C_c34_L_20
;I2C_c34.ppas,36 :: 		
$002D	$2004			CALL	_i2c_is_idle
$002E	$0870			MOVF	STACK_0, 0
$002F	$3A00			XORLW	0
$0030	$1903			BTFSC	STATUS, Z
$0031	$2833			GOTO	I2C_c34_L_22
$0032	$	I2C_c34_L_21:
;I2C_c34.ppas,37 :: 		
$0032	$283F			GOTO	I2C_c34_L_20
$0033	$	I2C_c34_L_22:
$0033	$	I2C_c34_L_23:
$0033	$0826			MOVF	_i2c_start_local_j+1, 0
$0034	$3A12			XORLW	18
$0035	$1D03			BTFSS	STATUS, Z
$0036	$2839			GOTO	L_I2C_Start_1
$0037	$308E			MOVLW	142
$0038	$0625			XORWF	_i2c_start_local_j, 0
$0039	$	L_I2C_Start_1:
$0039	$1903			BTFSC	STATUS, Z
$003A	$283F			GOTO	I2C_c34_L_20
$003B	$	I2C_c34_L_18:
$003B	$0AA5			INCF	_i2c_start_local_j, 1
$003C	$1903			BTFSC	STATUS, Z
$003D	$0AA6			INCF	_i2c_start_local_j+1, 1
$003E	$2825			GOTO	I2C_c34_L_17
$003F	$	I2C_c34_L_20:
;I2C_c34.ppas,39 :: 		
$003F	$3012			MOVLW	18
$0040	$0226			SUBWF	_i2c_start_local_j+1, 0
$0041	$1D03			BTFSS	STATUS, Z
$0042	$2845			GOTO	L_I2C_Start_2
$0043	$308F			MOVLW	143
$0044	$0225			SUBWF	_i2c_start_local_j, 0
$0045	$	L_I2C_Start_2:
$0045	$1C03			BTFSS	STATUS, C
$0046	$284A			GOTO	I2C_c34_L_25
$0047	$	I2C_c34_L_24:
;I2C_c34.ppas,40 :: 		
$0047	$307B			MOVLW	123
$0048	$00A4			MOVWF	_i2c_start_local_result
$0049	$2857			GOTO	I2C_c34_L_26
;I2C_c34.ppas,41 :: 		
$004A	$	I2C_c34_L_25:
;I2C_c34.ppas,42 :: 		
$004A	$	I2C_c34_L_27:
$004A	$1683			BSF	STATUS, RP0
$004B	$1411			BSF	SSPCON2, 0
$004C	$	I2C_c34_L_28:
;I2C_c34.ppas,43 :: 		
$004C	$	I2C_c34_L_30:
$004C	$3001			MOVLW	1
$004D	$0511			ANDWF	SSPCON2, 0
$004E	$00F1			MOVWF	STACK_1
$004F	$0871			MOVF	STACK_1, 0
$0050	$3A00			XORLW	0
$0051	$1903			BTFSC	STATUS, Z
$0052	$2855			GOTO	I2C_c34_L_31
;I2C_c34.ppas,44 :: 		
$0053	$0000			NOP
$0054	$284C			GOTO	I2C_c34_L_30
$0055	$	I2C_c34_L_31:
;I2C_c34.ppas,45 :: 		
$0055	$1283			BCF	STATUS, RP0
$0056	$01A4			CLRF	_i2c_start_local_result, 1
;I2C_c34.ppas,46 :: 		
$0057	$	I2C_c34_L_26:
$0057	$	I2C_c34_L_16:
;I2C_c34.ppas,47 :: 		
$0057	$0824			MOVF	_i2c_start_local_result, 0
$0058	$00F0			MOVWF	STACK_0
$0059	$0008			RETURN
$005A	$	_i2c_wr:
;I2C_c34.ppas,81 :: 		
;I2C_c34.ppas,82 :: 		
$005A	$1303			BCF	STATUS, RP1
$005B	$1283			BCF	STATUS, RP0
$005C	$0824			MOVF	FARG_I2C_Wr, 0
$005D	$0093			MOVWF	SSPBUF
;I2C_c34.ppas,83 :: 		
$005E	$118C			BCF	PIR1, 3
$005F	$	I2C_c34_L_70:
;I2C_c34.ppas,84 :: 		
$005F	$	I2C_c34_L_72:
$005F	$3000			MOVLW	0
$0060	$1683			BSF	STATUS, RP0
$0061	$1914			BTFSC	SSPSTAT, 2
$0062	$3001			MOVLW	1
$0063	$00F1			MOVWF	STACK_1
$0064	$0871			MOVF	STACK_1, 0
$0065	$3A00			XORLW	0
$0066	$1D03			BTFSS	STATUS, Z
$0067	$285F			GOTO	I2C_c34_L_72
$0068	$	I2C_c34_L_73:
;I2C_c34.ppas,85 :: 		
$0068	$	I2C_c34_L_77:
$0068	$3000			MOVLW	0
$0069	$1283			BCF	STATUS, RP0
$006A	$198C			BTFSC	PIR1, 3
$006B	$3001			MOVLW	1
$006C	$00F1			MOVWF	STACK_1
$006D	$0871			MOVF	STACK_1, 0
$006E	$3A00			XORLW	0
$006F	$1903			BTFSC	STATUS, Z
$0070	$2868			GOTO	I2C_c34_L_77
$0071	$	I2C_c34_L_78:
;I2C_c34.ppas,86 :: 		
$0071	$3000			MOVLW	0
$0072	$1683			BSF	STATUS, RP0
$0073	$1B11			BTFSC	SSPCON2, 6
$0074	$3001			MOVLW	1
$0075	$00F1			MOVWF	STACK_1
$0076	$0871			MOVF	STACK_1, 0
$0077	$3A00			XORLW	0
$0078	$1D03			BTFSS	STATUS, Z
$0079	$287D			GOTO	I2C_c34_L_82
$007A	$	I2C_c34_L_81:
$007A	$1283			BCF	STATUS, RP0
$007B	$01A5			CLRF	_i2c_wr_local_result, 1
$007C	$2884			GOTO	I2C_c34_L_83
;I2C_c34.ppas,87 :: 		
$007D	$	I2C_c34_L_82:
;I2C_c34.ppas,88 :: 		
$007D	$	I2C_c34_L_84:
$007D	$1303			BCF	STATUS, RP1
$007E	$1283			BCF	STATUS, RP0
$007F	$1683			BSF	STATUS, RP0
$0080	$1511			BSF	SSPCON2, 2
$0081	$	I2C_c34_L_85:
;I2C_c34.ppas,89 :: 		
$0081	$3002			MOVLW	2
$0082	$1283			BCF	STATUS, RP0
$0083	$00A5			MOVWF	_i2c_wr_local_result
;I2C_c34.ppas,90 :: 		
$0084	$	I2C_c34_L_83:
$0084	$	I2C_c34_L_68:
;I2C_c34.ppas,91 :: 		
$0084	$0825			MOVF	_i2c_wr_local_result, 0
$0085	$00F0			MOVWF	STACK_0
$0086	$0008			RETURN
$0087	$	_i2c_stop:
;I2C_c34.ppas,97 :: 		
;I2C_c34.ppas,98 :: 		
$0087	$	I2C_c34_L_87:
$0087	$1303			BCF	STATUS, RP1
$0088	$1683			BSF	STATUS, RP0
$0089	$1511			BSF	SSPCON2, 2
$008A	$	I2C_c34_L_88:
$008A	$	I2C_c34_L_86:
;I2C_c34.ppas,99 :: 		
$008A	$0008			RETURN
$008B	$	_i2c_repeated_start:
;I2C_c34.ppas,54 :: 		
;I2C_c34.ppas,55 :: 		
$008B	$	I2C_c34_L_35:
$008B	$1303			BCF	STATUS, RP1
$008C	$1683			BSF	STATUS, RP0
$008D	$1491			BSF	SSPCON2, 1
$008E	$	I2C_c34_L_36:
;I2C_c34.ppas,56 :: 		
$008E	$	I2C_c34_L_38:
$008E	$3000			MOVLW	0
$008F	$1891			BTFSC	SSPCON2, 1
$0090	$3001			MOVLW	1
$0091	$00F1			MOVWF	STACK_1
$0092	$0871			MOVF	STACK_1, 0
$0093	$3A00			XORLW	0
$0094	$1903			BTFSC	STATUS, Z
$0095	$2898			GOTO	I2C_c34_L_39
;I2C_c34.ppas,57 :: 		
$0096	$0000			NOP
$0097	$288E			GOTO	I2C_c34_L_38
$0098	$	I2C_c34_L_39:
$0098	$	I2C_c34_L_34:
;I2C_c34.ppas,58 :: 		
$0098	$0008			RETURN
$0099	$	_i2c_rd:
;I2C_c34.ppas,65 :: 		
;I2C_c34.ppas,66 :: 		
$0099	$	I2C_c34_L_43:
$0099	$1303			BCF	STATUS, RP1
$009A	$1683			BSF	STATUS, RP0
$009B	$1591			BSF	SSPCON2, 3
$009C	$	I2C_c34_L_44:
;I2C_c34.ppas,67 :: 		
$009C	$1283			BCF	STATUS, RP0
$009D	$118C			BCF	PIR1, 3
$009E	$	I2C_c34_L_46:
;I2C_c34.ppas,68 :: 		
$009E	$	I2C_c34_L_48:
$009E	$3000			MOVLW	0
$009F	$198C			BTFSC	PIR1, 3
$00A0	$3001			MOVLW	1
$00A1	$00F1			MOVWF	STACK_1
$00A2	$0871			MOVF	STACK_1, 0
$00A3	$3A00			XORLW	0
$00A4	$1903			BTFSC	STATUS, Z
$00A5	$289E			GOTO	I2C_c34_L_48
$00A6	$	I2C_c34_L_49:
;I2C_c34.ppas,69 :: 		
$00A6	$0813			MOVF	SSPBUF, 0
$00A7	$00A5			MOVWF	_i2c_rd_local_result
;I2C_c34.ppas,70 :: 		
$00A8	$1683			BSF	STATUS, RP0
$00A9	$1291			BCF	SSPCON2, 5
$00AA	$	I2C_c34_L_53:
;I2C_c34.ppas,71 :: 		
$00AA	$1283			BCF	STATUS, RP0
$00AB	$0824			MOVF	FARG_I2C_Rd, 0
$00AC	$3A00			XORLW	0
$00AD	$1D03			BTFSS	STATUS, Z
$00AE	$28B1			GOTO	I2C_c34_L_55
$00AF	$	I2C_c34_L_54:
$00AF	$	I2C_c34_L_57:
$00AF	$1683			BSF	STATUS, RP0
$00B0	$1691			BSF	SSPCON2, 5
$00B1	$	I2C_c34_L_58:
$00B1	$	I2C_c34_L_55:
$00B1	$	I2C_c34_L_56:
;I2C_c34.ppas,72 :: 		
$00B1	$	I2C_c34_L_59:
$00B1	$1303			BCF	STATUS, RP1
$00B2	$1683			BSF	STATUS, RP0
$00B3	$1611			BSF	SSPCON2, 4
$00B4	$	I2C_c34_L_60:
;I2C_c34.ppas,73 :: 		
$00B4	$1283			BCF	STATUS, RP0
$00B5	$118C			BCF	PIR1, 3
$00B6	$	I2C_c34_L_62:
;I2C_c34.ppas,74 :: 		
$00B6	$	I2C_c34_L_64:
$00B6	$3000			MOVLW	0
$00B7	$198C			BTFSC	PIR1, 3
$00B8	$3001			MOVLW	1
$00B9	$00F1			MOVWF	STACK_1
$00BA	$0871			MOVF	STACK_1, 0
$00BB	$3A00			XORLW	0
$00BC	$1903			BTFSC	STATUS, Z
$00BD	$28B6			GOTO	I2C_c34_L_64
$00BE	$	I2C_c34_L_65:
$00BE	$	I2C_c34_L_42:
;I2C_c34.ppas,75 :: 		
$00BE	$0825			MOVF	_i2c_rd_local_result, 0
$00BF	$00F0			MOVWF	STACK_0
$00C0	$0008			RETURN
$00C1	$	_escrever_i2c:
;MemI2C.ppas,26 :: 		begin
;MemI2C.ppas,27 :: 		i2c_start;			        //Condição de início
$00C1	$2021			CALL	_i2c_start
;MemI2C.ppas,28 :: 		i2c_wr(%10100000); 	  	//Envia o byte de e escrita
$00C2	$30A0			MOVLW	160
$00C3	$00A4			MOVWF	FARG_I2C_Wr
$00C4	$205A			CALL	_i2c_wr
;MemI2C.ppas,29 :: 		i2c_wr(endereco);		   	//Envia endereço
$00C5	$0820			MOVF	FARG_Escrever_I2C, 0
$00C6	$00A4			MOVWF	FARG_I2C_Wr
$00C7	$205A			CALL	_i2c_wr
;MemI2C.ppas,30 :: 		i2c_wr(dado);	          //Escreve dado na E²PROM
$00C8	$0821			MOVF	FARG_Escrever_I2C+1, 0
$00C9	$00A4			MOVWF	FARG_I2C_Wr
$00CA	$205A			CALL	_i2c_wr
;MemI2C.ppas,31 :: 		i2c_stop;			       		// Condição de parada
$00CB	$2087			CALL	_i2c_stop
;MemI2C.ppas,32 :: 		delay_ms(5);				    // espera a gravação estar completa
$00CC	$3007			MOVLW	7
$00CD	$00FB			MOVWF	STACK_11
$00CE	$30FF			MOVLW	255
$00CF	$00FA			MOVWF	STACK_10
$00D0	$0BFB			DECFSZ	STACK_11, F
$00D1	$28D3			GOTO	$+2
$00D2	$28D6			GOTO	$+4
$00D3	$0BFA			DECFSZ	STACK_10, F
$00D4	$28D3			GOTO	$-1
$00D5	$28D0			GOTO	$-5
$00D6	$3078			MOVLW	120
$00D7	$00FA			MOVWF	STACK_10
$00D8	$0BFA			DECFSZ	STACK_10, F
$00D9	$28D8			GOTO	$-1
$00DA	$0000			NOP
$00DB	$0000			NOP
$00DC	$	MemI2C_L_1:
;MemI2C.ppas,33 :: 		end;
$00DC	$0008			RETURN
$00DD	$	_le_i2c:
;MemI2C.ppas,10 :: 		begin
;MemI2C.ppas,11 :: 		i2c_start;           				//Condição de início
$00DD	$2021			CALL	_i2c_start
;MemI2C.ppas,12 :: 		i2c_wr(%10100000);		  		//Envia um byte de escrita
$00DE	$30A0			MOVLW	160
$00DF	$00A4			MOVWF	FARG_I2C_Wr
$00E0	$205A			CALL	_i2c_wr
;MemI2C.ppas,13 :: 		i2c_wr(endereco);				    //Envia endereço
$00E1	$0820			MOVF	FARG_Le_I2C, 0
$00E2	$00A4			MOVWF	FARG_I2C_Wr
$00E3	$205A			CALL	_i2c_wr
;MemI2C.ppas,14 :: 		I2C_Repeated_Start;					//Nova condição de início
$00E4	$208B			CALL	_i2c_repeated_start
;MemI2C.ppas,15 :: 		i2c_wr(%10100001);				  //Envia o byte de controle de leitura
$00E5	$30A1			MOVLW	161
$00E6	$1283			BCF	STATUS, RP0
$00E7	$00A4			MOVWF	FARG_I2C_Wr
$00E8	$205A			CALL	_i2c_wr
;MemI2C.ppas,16 :: 		aux:=i2c_rd(0);         		//lê o dado armazenado na E²PROM e envia nack
$00E9	$01A4			CLRF	FARG_I2C_Rd, 1
$00EA	$2099			CALL	_i2c_rd
$00EB	$0870			MOVF	STACK_0, 0
$00EC	$00A2			MOVWF	_le_i2c_local_aux
;MemI2C.ppas,17 :: 		i2c_stop;	                  //Condição de parada
$00ED	$2087			CALL	_i2c_stop
;MemI2C.ppas,18 :: 		result:=aux;                //retorna o dado lido
$00EE	$1283			BCF	STATUS, RP0
$00EF	$0822			MOVF	_le_i2c_local_aux, 0
$00F0	$00A1			MOVWF	_le_i2c_local_result
$00F1	$	MemI2C_L_0:
;MemI2C.ppas,19 :: 		end;
$00F1	$0821			MOVF	_le_i2c_local_result, 0
$00F2	$00F0			MOVWF	STACK_0
$00F3	$0008			RETURN
$00F4	$	_usart_write:
;USART_c67.ppas,40 :: 		
;USART_c67.ppas,42 :: 		
$00F4	$	USART_c67_L_14:
$00F4	$3000			MOVLW	0
$00F5	$1303			BCF	STATUS, RP1
$00F6	$1683			BSF	STATUS, RP0
$00F7	$1898			BTFSC	TXSTA, 1
$00F8	$3001			MOVLW	1
$00F9	$00F1			MOVWF	STACK_1
$00FA	$0871			MOVF	STACK_1, 0
$00FB	$3A00			XORLW	0
$00FC	$1D03			BTFSS	STATUS, Z
$00FD	$2900			GOTO	USART_c67_L_15
;USART_c67.ppas,43 :: 		
$00FE	$0000			NOP
$00FF	$28F4			GOTO	USART_c67_L_14
$0100	$	USART_c67_L_15:
;USART_c67.ppas,44 :: 		
$0100	$1283			BCF	STATUS, RP0
$0101	$0820			MOVF	FARG_USART_Write, 0
$0102	$0099			MOVWF	TXREG
$0103	$	USART_c67_L_12:
;USART_c67.ppas,45 :: 		
$0103	$0008			RETURN
$0104	$	_usart_init:
;USART_c67.ppas,22 :: 		
;USART_c67.ppas,24 :: 		
$0104	$	USART_c67_L_1:
$0104	$1303			BCF	STATUS, RP1
$0105	$1683			BSF	STATUS, RP0
$0106	$1698			BSF	TXSTA, 5
$0107	$	USART_c67_L_2:
;USART_c67.ppas,25 :: 		
$0107	$3090			MOVLW	144
$0108	$1283			BCF	STATUS, RP0
$0109	$0098			MOVWF	RCSTA
;USART_c67.ppas,31 :: 		
$010A	$	USART_c67_L_3:
$010A	$1683			BSF	STATUS, RP0
$010B	$1787			BSF	TRISC, 7
$010C	$	USART_c67_L_4:
;USART_c67.ppas,32 :: 		
$010C	$1307			BCF	TRISC, 6
$010D	$	USART_c67_L_6:
;USART_c67.ppas,35 :: 		
$010D	$	USART_c67_L_8:
$010D	$3000			MOVLW	0
$010E	$1283			BCF	STATUS, RP0
$010F	$1A8C			BTFSC	PIR1, 5
$0110	$3001			MOVLW	1
$0111	$00F1			MOVWF	STACK_1
$0112	$0871			MOVF	STACK_1, 0
$0113	$3A01			XORLW	1
$0114	$1903			BTFSC	STATUS, Z
$0115	$290D			GOTO	USART_c67_L_8
;USART_c67.ppas,36 :: 		
$0116	$	USART_c67_L_9:
$0116	$	USART_c67_L_0:
;USART_c67.ppas,37 :: 		
$0116	$0008			RETURN
$0117	$	_i2c_init:
;I2C_c34.ppas,8 :: 		
;I2C_c34.ppas,9 :: 		
$0117	$1303			BCF	STATUS, RP1
$0118	$1683			BSF	STATUS, RP0
$0119	$1314			BCF	SSPSTAT, 6
$011A	$	I2C_c34_L_2:
;I2C_c34.ppas,10 :: 		
$011A	$1394			BCF	SSPSTAT, 7
$011B	$	I2C_c34_L_4:
;I2C_c34.ppas,11 :: 		
$011B	$	I2C_c34_L_5:
$011B	$1607			BSF	TRISC, 4
$011C	$	I2C_c34_L_6:
;I2C_c34.ppas,12 :: 		
$011C	$	I2C_c34_L_7:
$011C	$1587			BSF	TRISC, 3
$011D	$	I2C_c34_L_8:
;I2C_c34.ppas,13 :: 		
$011D	$3038			MOVLW	56
$011E	$1283			BCF	STATUS, RP0
$011F	$0094			MOVWF	SSPCON
$0120	$	I2C_c34_L_0:
;I2C_c34.ppas,15 :: 		
$0120	$0008			RETURN
$0121	$	_main:
;MemI2C.ppas,40 :: 		begin
;MemI2C.ppas,42 :: 		usart_init(9600);             //Inicializa a usart a 9600 bps
$0121	$3019			MOVLW	25
$0122	$1303			BCF	STATUS, RP1
$0123	$1683			BSF	STATUS, RP0
$0124	$0099			MOVWF	SPBRG
$0125	$1518			BSF	TXSTA, BRGH
$0126	$2104			CALL	_usart_init
;MemI2C.ppas,44 :: 		I2C_init(100000);             //inicializa o módulo para funcionar a 100kHz em modo master
$0127	$300A			MOVLW	10
$0128	$1683			BSF	STATUS, RP0
$0129	$0093			MOVWF	SSPADD
$012A	$2117			CALL	_i2c_init
;MemI2C.ppas,45 :: 		usart_init(9600);             //inicializa a usart em 9600 bps
$012B	$3019			MOVLW	25
$012C	$1683			BSF	STATUS, RP0
$012D	$0099			MOVWF	SPBRG
$012E	$1518			BSF	TXSTA, BRGH
$012F	$2104			CALL	_usart_init
;MemI2C.ppas,47 :: 		Escrever_I2C(0,'A');          //Escreve na posição 0 o caracter 'A'
$0130	$01A0			CLRF	FARG_Escrever_I2C, 1
$0131	$3041			MOVLW	65
$0132	$00A1			MOVWF	FARG_Escrever_I2C+1
$0133	$20C1			CALL	_escrever_i2c
;MemI2C.ppas,48 :: 		usart_write(Le_I2C(0));      //Envia via serial o dado lido da posição 0 de memória I2C
$0134	$1283			BCF	STATUS, RP0
$0135	$01A0			CLRF	FARG_Le_I2C, 1
$0136	$20DD			CALL	_le_i2c
$0137	$0870			MOVF	STACK_0, 0
$0138	$00A0			MOVWF	FARG_USART_Write
$0139	$20F4			CALL	_usart_write
$013A	$	MemI2C_L_2:
;MemI2C.ppas,56 :: 		end.
$013A	$293A			GOTO	$
