;  ASM code generated by mikroVirtualMachine for PIC - V. 5.0.0.2
;  Date/Time: 16/2/2007 14:41:58
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$291C			GOTO	RecepcaoSerial_main
$0004	$	delays_delay_1us:
^delays.pbas, 5 :: 		sub procedure Delay_1us
^delays.pbas, 6 :: 		Delay_us(1)
$0004	$0000			NOP
$0005	$	delays_L_0:
$0005	$0008			RETURN
$0006	$	delays_delay_5500us:
^delays.pbas, 29 :: 		sub procedure Delay_5500us
^delays.pbas, 30 :: 		Delay_us(5500)
$0006	$3008			MOVLW	8
$0007	$1303			BCF	STATUS, RP1
$0008	$1283			BCF	STATUS, RP0
$0009	$00FB			MOVWF	STACK_11
$000A	$30FF			MOVLW	255
$000B	$00FA			MOVWF	STACK_10
$000C	$0BFB			DECFSZ	STACK_11, F
$000D	$280F			GOTO	$+2
$000E	$2812			GOTO	$+4
$000F	$0BFA			DECFSZ	STACK_10, F
$0010	$280F			GOTO	$-1
$0011	$280C			GOTO	$-5
$0012	$301E			MOVLW	30
$0013	$00FA			MOVWF	STACK_10
$0014	$0BFA			DECFSZ	STACK_10, F
$0015	$2814			GOTO	$-1
$0016	$	delays_L_6:
$0016	$0008			RETURN
$0017	$	delays_delay_500us:
^delays.pbas, 25 :: 		sub procedure Delay_500us
^delays.pbas, 26 :: 		Delay_us(498)
$0017	$30A5			MOVLW	165
$0018	$1303			BCF	STATUS, RP1
$0019	$1283			BCF	STATUS, RP0
$001A	$00FA			MOVWF	STACK_10
$001B	$0BFA			DECFSZ	STACK_10, F
$001C	$281B			GOTO	$-1
$001D	$0000			NOP
$001E	$0000			NOP
$001F	$	delays_L_5:
$001F	$0008			RETURN
$0020	$	lcd8bit_lcd8_cmd:
$0020	$1303			BCF	STATUS, RP1
$0021	$1283			BCF	STATUS, RP0
$0022	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0023	$0084			MOVWF	FSR
$0024	$0180			CLRF	INDF, 1
$0025	$1BAA			BTFSC	FARG_LCD8_CMD, 7
$0026	$1780			BSF	INDF, __LCD8_DB7
$0027	$1B2A			BTFSC	FARG_LCD8_CMD, 6
$0028	$1700			BSF	INDF, __LCD8_DB6
$0029	$1AAA			BTFSC	FARG_LCD8_CMD, 5
$002A	$1680			BSF	INDF, __LCD8_DB5
$002B	$1A2A			BTFSC	FARG_LCD8_CMD, 4
$002C	$1600			BSF	INDF, __LCD8_DB4
$002D	$19AA			BTFSC	FARG_LCD8_CMD, 3
$002E	$1580			BSF	INDF, __LCD8_DB3
$002F	$192A			BTFSC	FARG_LCD8_CMD, 2
$0030	$1500			BSF	INDF, __LCD8_DB2
$0031	$18AA			BTFSC	FARG_LCD8_CMD, 1
$0032	$1480			BSF	INDF, __LCD8_DB1
$0033	$182A			BTFSC	FARG_LCD8_CMD, 0
$0034	$1400			BSF	INDF, __LCD8_DB0
$0035	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0036	$0084			MOVWF	FSR
$0037	$0822			MOVF	lcd8bit_main_global_com, 0
$0038	$3A01			XORLW	1
$0039	$1D03			BTFSS	STATUS, Z
$003A	$283D			GOTO	lcd8bit_L_2
$003B	$	lcd8bit_L_1:
$003B	$1100			BCF	INDF, __LCD8_RS
$003C	$283E			GOTO	lcd8bit_L_3
$003D	$	lcd8bit_L_2:
$003D	$1500			BSF	INDF, __LCD8_RS
$003E	$	lcd8bit_L_3:
$003E	$1480			BSF	INDF, __LCD8_ENABLE
$003F	$2004			CALL	delays_delay_1us
$0040	$1080			BCF	INDF, __LCD8_ENABLE
$0041	$0822			MOVF	lcd8bit_main_global_com, 0
$0042	$3A01			XORLW	1
$0043	$1D03			BTFSS	STATUS, Z
$0044	$2847			GOTO	lcd8bit_L_5
$0045	$	lcd8bit_L_4:
$0045	$2006			CALL	delays_delay_5500us
$0046	$2848			GOTO	lcd8bit_L_6
$0047	$	lcd8bit_L_5:
$0047	$2017			CALL	delays_delay_500us
$0048	$	lcd8bit_L_6:
$0048	$	lcd8bit_L_0:
$0048	$0008			RETURN
$0049	$	usartlib_u_a_usart_data_ready:
$0049	$3000			MOVLW	0
$004A	$1303			BCF	STATUS, RP1
$004B	$1283			BCF	STATUS, RP0
$004C	$1A8C			BTFSC	PIR1, 5
$004D	$3001			MOVLW	1
$004E	$00F1			MOVWF	STACK_1
$004F	$0871			MOVF	STACK_1, 0
$0050	$00A6			MOVWF	usartlib_u_a_usart_data_ready_local_result
$0051	$	usartlib_u_a_L_18:
$0051	$0826			MOVF	usartlib_u_a_usart_data_ready_local_result, 0
$0052	$00F0			MOVWF	STACK_0
$0053	$0008			RETURN
$0054	$	usartlib_u_a_usart_read:
$0054	$1303			BCF	STATUS, RP1
$0055	$1283			BCF	STATUS, RP0
$0056	$081A			MOVF	RCREG, 0
$0057	$00A6			MOVWF	usartlib_u_a_usart_read_local_result
$0058	$3000			MOVLW	0
$0059	$1898			BTFSC	RCSTA, 1
$005A	$3001			MOVLW	1
$005B	$00F1			MOVWF	STACK_1
$005C	$0871			MOVF	STACK_1, 0
$005D	$3A01			XORLW	1
$005E	$1D03			BTFSS	STATUS, Z
$005F	$2862			GOTO	usartlib_u_a_L_21
$0060	$	usartlib_u_a_L_20:
$0060	$1218			BCF	RCSTA, 4
$0061	$	usartlib_u_a_L_24:
$0061	$	usartlib_u_a_L_25:
$0061	$1618			BSF	RCSTA, 4
$0062	$	usartlib_u_a_L_26:
$0062	$	usartlib_u_a_L_21:
$0062	$	usartlib_u_a_L_22:
$0062	$	usartlib_u_a_L_19:
$0062	$0826			MOVF	usartlib_u_a_usart_read_local_result, 0
$0063	$00F0			MOVWF	STACK_0
$0064	$0008			RETURN
$0065	$	usartlib_u_a_usart_write:
$0065	$	usartlib_u_a_L_14:
$0065	$3000			MOVLW	0
$0066	$1303			BCF	STATUS, RP1
$0067	$1683			BSF	STATUS, RP0
$0068	$1898			BTFSC	TXSTA, 1
$0069	$3001			MOVLW	1
$006A	$00F1			MOVWF	STACK_1
$006B	$0871			MOVF	STACK_1, 0
$006C	$3A00			XORLW	0
$006D	$1D03			BTFSS	STATUS, Z
$006E	$2871			GOTO	usartlib_u_a_L_15
$006F	$0000			NOP
$0070	$2865			GOTO	usartlib_u_a_L_14
$0071	$	usartlib_u_a_L_15:
$0071	$1283			BCF	STATUS, RP0
$0072	$0826			MOVF	FARG_USART_Write, 0
$0073	$0099			MOVWF	TXREG
$0074	$	usartlib_u_a_L_12:
$0074	$0008			RETURN
$0075	$	lcd8bit_lcd8_chr:
$0075	$	lcd8bit_L_10:
$0075	$1303			BCF	STATUS, RP1
$0076	$1283			BCF	STATUS, RP0
$0077	$0826			MOVF	FARG_Lcd8_Chr, 0
$0078	$3A01			XORLW	1
$0079	$1D03			BTFSS	STATUS, Z
$007A	$287E			GOTO	lcd8bit_L_11
$007B	$	lcd8bit_L_9:
$007B	$3080			MOVLW	128
$007C	$00A6			MOVWF	FARG_Lcd8_Chr
$007D	$2895			GOTO	lcd8bit_L_8
$007E	$	lcd8bit_L_11:
$007E	$	lcd8bit_L_13:
$007E	$0826			MOVF	FARG_Lcd8_Chr, 0
$007F	$3A02			XORLW	2
$0080	$1D03			BTFSS	STATUS, Z
$0081	$2885			GOTO	lcd8bit_L_14
$0082	$	lcd8bit_L_12:
$0082	$30C0			MOVLW	192
$0083	$00A6			MOVWF	FARG_Lcd8_Chr
$0084	$2895			GOTO	lcd8bit_L_8
$0085	$	lcd8bit_L_14:
$0085	$	lcd8bit_L_16:
$0085	$0826			MOVF	FARG_Lcd8_Chr, 0
$0086	$3A03			XORLW	3
$0087	$1D03			BTFSS	STATUS, Z
$0088	$288C			GOTO	lcd8bit_L_17
$0089	$	lcd8bit_L_15:
$0089	$3094			MOVLW	148
$008A	$00A6			MOVWF	FARG_Lcd8_Chr
$008B	$2895			GOTO	lcd8bit_L_8
$008C	$	lcd8bit_L_17:
$008C	$	lcd8bit_L_19:
$008C	$0826			MOVF	FARG_Lcd8_Chr, 0
$008D	$3A04			XORLW	4
$008E	$1D03			BTFSS	STATUS, Z
$008F	$2893			GOTO	lcd8bit_L_20
$0090	$	lcd8bit_L_18:
$0090	$30D4			MOVLW	212
$0091	$00A6			MOVWF	FARG_Lcd8_Chr
$0092	$2895			GOTO	lcd8bit_L_8
$0093	$	lcd8bit_L_20:
$0093	$3080			MOVLW	128
$0094	$00A6			MOVWF	FARG_Lcd8_Chr
$0095	$	lcd8bit_L_8:
$0095	$0827			MOVF	FARG_Lcd8_Chr+1, 0
$0096	$0726			ADDWF	FARG_Lcd8_Chr, 0
$0097	$00F0			MOVWF	STACK_0
$0098	$03F0			DECF	STACK_0, 1
$0099	$0870			MOVF	STACK_0, 0
$009A	$00A6			MOVWF	FARG_Lcd8_Chr
$009B	$0870			MOVF	STACK_0, 0
$009C	$00AA			MOVWF	FARG_Lcd8_Cmd
$009D	$2020			CALL	lcd8bit_lcd8_cmd
$009E	$01A2			CLRF	lcd8bit_main_global_com, 1
$009F	$0828			MOVF	FARG_Lcd8_Chr+2, 0
$00A0	$00AA			MOVWF	FARG_Lcd8_Cmd
$00A1	$2020			CALL	lcd8bit_lcd8_cmd
$00A2	$3001			MOVLW	1
$00A3	$00A2			MOVWF	lcd8bit_main_global_com
$00A4	$	lcd8bit_L_7:
$00A4	$0008			RETURN
$00A5	$	lcd8bit_lcd8_init:
$00A5	$2006			CALL	delays_delay_5500us
$00A6	$2006			CALL	delays_delay_5500us
$00A7	$2006			CALL	delays_delay_5500us
$00A8	$0827			MOVF	FARG_Lcd8_Init+1, 0
$00A9	$00A0			MOVWF	lcd8bit_main_global_dataaddress
$00AA	$0826			MOVF	FARG_Lcd8_Init, 0
$00AB	$00A1			MOVWF	lcd8bit_main_global_ctrladdress
$00AC	$0827			MOVF	FARG_Lcd8_Init+1, 0
$00AD	$0084			MOVWF	FSR
$00AE	$1784			BSF	FSR, 7
$00AF	$0180			CLRF	INDF, 1
$00B0	$0826			MOVF	FARG_Lcd8_Init, 0
$00B1	$0084			MOVWF	FSR
$00B2	$1180			BCF	INDF, __LCD8_RW
$00B3	$1784			BSF	FSR, 7
$00B4	$1100			BCF	INDF, __LCD8_RS
$00B5	$1180			BCF	INDF, __LCD8_RW
$00B6	$1080			BCF	INDF, __LCD8_ENABLE
$00B7	$1384			BCF	FSR, 7
$00B8	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00B9	$0084			MOVWF	FSR
$00BA	$3030			MOVLW	48
$00BB	$0080			MOVWF	INDF
$00BC	$2006			CALL	delays_delay_5500us
$00BD	$2006			CALL	delays_delay_5500us
$00BE	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00BF	$0084			MOVWF	FSR
$00C0	$1480			BSF	INDF, __LCD8_ENABLE
$00C1	$2004			CALL	delays_delay_1us
$00C2	$1080			BCF	INDF, __LCD8_ENABLE
$00C3	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00C4	$0084			MOVWF	FSR
$00C5	$3030			MOVLW	48
$00C6	$0080			MOVWF	INDF
$00C7	$2006			CALL	delays_delay_5500us
$00C8	$2006			CALL	delays_delay_5500us
$00C9	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00CA	$0084			MOVWF	FSR
$00CB	$1480			BSF	INDF, __LCD8_ENABLE
$00CC	$2004			CALL	delays_delay_1us
$00CD	$1080			BCF	INDF, __LCD8_ENABLE
$00CE	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00CF	$0084			MOVWF	FSR
$00D0	$3030			MOVLW	48
$00D1	$0080			MOVWF	INDF
$00D2	$2006			CALL	delays_delay_5500us
$00D3	$2006			CALL	delays_delay_5500us
$00D4	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00D5	$0084			MOVWF	FSR
$00D6	$1480			BSF	INDF, __LCD8_ENABLE
$00D7	$2004			CALL	delays_delay_1us
$00D8	$1080			BCF	INDF, __LCD8_ENABLE
$00D9	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00DA	$0084			MOVWF	FSR
$00DB	$3038			MOVLW	56
$00DC	$0080			MOVWF	INDF
$00DD	$2006			CALL	delays_delay_5500us
$00DE	$2006			CALL	delays_delay_5500us
$00DF	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00E0	$0084			MOVWF	FSR
$00E1	$1480			BSF	INDF, __LCD8_ENABLE
$00E2	$2004			CALL	delays_delay_1us
$00E3	$1080			BCF	INDF, __LCD8_ENABLE
$00E4	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00E5	$0084			MOVWF	FSR
$00E6	$3010			MOVLW	16
$00E7	$0080			MOVWF	INDF
$00E8	$2006			CALL	delays_delay_5500us
$00E9	$2006			CALL	delays_delay_5500us
$00EA	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00EB	$0084			MOVWF	FSR
$00EC	$1480			BSF	INDF, __LCD8_ENABLE
$00ED	$2004			CALL	delays_delay_1us
$00EE	$1080			BCF	INDF, __LCD8_ENABLE
$00EF	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00F0	$0084			MOVWF	FSR
$00F1	$3001			MOVLW	1
$00F2	$0080			MOVWF	INDF
$00F3	$2006			CALL	delays_delay_5500us
$00F4	$2006			CALL	delays_delay_5500us
$00F5	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00F6	$0084			MOVWF	FSR
$00F7	$1480			BSF	INDF, __LCD8_ENABLE
$00F8	$2004			CALL	delays_delay_1us
$00F9	$1080			BCF	INDF, __LCD8_ENABLE
$00FA	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$00FB	$0084			MOVWF	FSR
$00FC	$300F			MOVLW	15
$00FD	$0080			MOVWF	INDF
$00FE	$2006			CALL	delays_delay_5500us
$00FF	$2006			CALL	delays_delay_5500us
$0100	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0101	$0084			MOVWF	FSR
$0102	$1480			BSF	INDF, __LCD8_ENABLE
$0103	$2004			CALL	delays_delay_1us
$0104	$1080			BCF	INDF, __LCD8_ENABLE
$0105	$3001			MOVLW	1
$0106	$00A2			MOVWF	lcd8bit_main_global_com
$0107	$	lcd8bit_L_22:
$0107	$0008			RETURN
$0108	$	usartlib_u_a_usart_init:
$0108	$	usartlib_u_a_L_1:
$0108	$1303			BCF	STATUS, RP1
$0109	$1683			BSF	STATUS, RP0
$010A	$1698			BSF	TXSTA, 5
$010B	$	usartlib_u_a_L_2:
$010B	$3090			MOVLW	144
$010C	$1283			BCF	STATUS, RP0
$010D	$0098			MOVWF	RCSTA
$010E	$	usartlib_u_a_L_3:
$010E	$1683			BSF	STATUS, RP0
$010F	$1787			BSF	TRISC, 7
$0110	$	usartlib_u_a_L_4:
$0110	$1307			BCF	TRISC, 6
$0111	$	usartlib_u_a_L_6:
$0111	$	usartlib_u_a_L_8:
$0111	$3000			MOVLW	0
$0112	$1283			BCF	STATUS, RP0
$0113	$1A8C			BTFSC	PIR1, 5
$0114	$3001			MOVLW	1
$0115	$00F1			MOVWF	STACK_1
$0116	$0871			MOVF	STACK_1, 0
$0117	$3A01			XORLW	1
$0118	$1D03			BTFSS	STATUS, Z
$0119	$291B			GOTO	usartlib_u_a_L_9
$011A	$2911			GOTO	usartlib_u_a_L_8
$011B	$	usartlib_u_a_L_9:
$011B	$	usartlib_u_a_L_0:
$011B	$0008			RETURN
$011C	$	RecepcaoSerial_main:
^RecepcaoSerial.pbas, 28 :: 		dim recepcao as char
$011C	$	RecepcaoSerial_main_main:
^RecepcaoSerial.pbas, 62 :: 		trisa=%11111111            ' põe todos os pinos para entrada
$011C	$30FF			MOVLW	255
$011D	$1303			BCF	STATUS, RP1
$011E	$1683			BSF	STATUS, RP0
$011F	$0085			MOVWF	TRISA
^RecepcaoSerial.pbas, 63 :: 		trisd=%00000000
$0120	$0188			CLRF	TRISD, 1
^RecepcaoSerial.pbas, 64 :: 		trise=%00000001            'configura i/os
$0121	$3001			MOVLW	1
$0122	$0089			MOVWF	TRISE
^RecepcaoSerial.pbas, 65 :: 		adcon1=7                   'desliga todos os a/ds
$0123	$3007			MOVLW	7
$0124	$009F			MOVWF	ADCON1
^RecepcaoSerial.pbas, 66 :: 		option_reg=%10000000       'configura prescaler do timer 0
$0125	$3080			MOVLW	128
$0126	$0081			MOVWF	OPTION_REG
^RecepcaoSerial.pbas, 67 :: 		Lcd8_Config(PORTE, PORTD, 2, 1, 3, 7, 6, 5, 4, 3, 2, 1, 0)
$0127	$3009			MOVLW	PORTE
$0128	$1283			BCF	STATUS, RP0
$0129	$00A6			MOVWF	farg_Lcd8_Init
$012A	$3008			MOVLW	PORTD
$012B	$00A7			MOVWF	farg_Lcd8_Init+1
$012C	$20A5			CALL	lcd8bit_lcd8_init
^RecepcaoSerial.pbas, 68 :: 		Lcd8_Cmd(LCD_CLEAR)        'limpa o display
$012D	$3001			MOVLW	1
$012E	$00AA			MOVWF	FARG_Lcd8_Cmd
$012F	$2020			CALL	lcd8bit_lcd8_cmd
^RecepcaoSerial.pbas, 69 :: 		Lcd8_Cmd(LCD_CURSOR_OFF)   'Desliga o cursor
$0130	$300C			MOVLW	12
$0131	$00AA			MOVWF	FARG_Lcd8_Cmd
$0132	$2020			CALL	lcd8bit_lcd8_cmd
^RecepcaoSerial.pbas, 70 :: 		Usart_Init(9600)           'Inicializa o módulo Usart para trabalhar a 9600bps
$0133	$3019			MOVLW	25
$0134	$1683			BSF	STATUS, RP0
$0135	$0099			MOVWF	SPBRG
$0136	$1518			BSF	TXSTA, BRGH
$0137	$2108			CALL	usartlib_u_a_usart_init
^RecepcaoSerial.pbas, 71 :: 		linha=1
$0138	$3001			MOVLW	1
$0139	$00A3			MOVWF	main_global_linha
^RecepcaoSerial.pbas, 72 :: 		coluna=1
$013A	$3001			MOVLW	1
$013B	$00A4			MOVWF	main_global_coluna
^RecepcaoSerial.pbas, 78 :: 		while 1=1
$013C	$	RecepcaoSerial_L_2:
^RecepcaoSerial.pbas, 79 :: 		if usart_data_ready<>0 then
$013C	$2049			CALL	usartlib_u_a_usart_data_ready
$013D	$0870			MOVF	STACK_0, 0
$013E	$3A00			XORLW	0
$013F	$1903			BTFSC	STATUS, Z
$0140	$2961			GOTO	RecepcaoSerial_L_7
$0141	$	RecepcaoSerial_L_6:
^RecepcaoSerial.pbas, 80 :: 		recepcao=Usart_Read
$0141	$2054			CALL	usartlib_u_a_usart_read
$0142	$0870			MOVF	STACK_0, 0
$0143	$00A5			MOVWF	main_global_recepcao
^RecepcaoSerial.pbas, 81 :: 		Usart_Write(recepcao)
$0144	$0870			MOVF	STACK_0, 0
$0145	$00A6			MOVWF	FARG_USART_Write
$0146	$2065			CALL	usartlib_u_a_usart_write
^RecepcaoSerial.pbas, 82 :: 		Lcd8_Chr(linha,coluna,recepcao)
$0147	$0823			MOVF	main_global_linha, 0
$0148	$00A6			MOVWF	FARG_Lcd8_Chr
$0149	$0824			MOVF	main_global_coluna, 0
$014A	$00A7			MOVWF	FARG_Lcd8_Chr+1
$014B	$0825			MOVF	main_global_recepcao, 0
$014C	$00A8			MOVWF	FARG_Lcd8_Chr+2
$014D	$2075			CALL	lcd8bit_lcd8_chr
^RecepcaoSerial.pbas, 83 :: 		coluna=coluna+1
$014E	$0A24			INCF	main_global_coluna, 0
$014F	$00F1			MOVWF	STACK_1
$0150	$0871			MOVF	STACK_1, 0
$0151	$00A4			MOVWF	main_global_coluna
^RecepcaoSerial.pbas, 84 :: 		if coluna=17 then
$0152	$0871			MOVF	STACK_1, 0
$0153	$3A11			XORLW	17
$0154	$1D03			BTFSS	STATUS, Z
$0155	$2961			GOTO	RecepcaoSerial_L_10
$0156	$	RecepcaoSerial_L_9:
^RecepcaoSerial.pbas, 85 :: 		coluna=1
$0156	$3001			MOVLW	1
$0157	$00A4			MOVWF	main_global_coluna
^RecepcaoSerial.pbas, 86 :: 		if linha=1 then
$0158	$0823			MOVF	main_global_linha, 0
$0159	$3A01			XORLW	1
$015A	$1D03			BTFSS	STATUS, Z
$015B	$295F			GOTO	RecepcaoSerial_L_13
$015C	$	RecepcaoSerial_L_12:
^RecepcaoSerial.pbas, 87 :: 		linha=2
$015C	$3002			MOVLW	2
$015D	$00A3			MOVWF	main_global_linha
$015E	$2961			GOTO	RecepcaoSerial_L_14
^RecepcaoSerial.pbas, 88 :: 		else
$015F	$	RecepcaoSerial_L_13:
^RecepcaoSerial.pbas, 89 :: 		linha=1
$015F	$3001			MOVLW	1
$0160	$00A3			MOVWF	main_global_linha
^RecepcaoSerial.pbas, 90 :: 		end if
$0161	$	RecepcaoSerial_L_14:
$0161	$	RecepcaoSerial_L_10:
^RecepcaoSerial.pbas, 91 :: 		end if
$0161	$	RecepcaoSerial_L_11:
$0161	$	RecepcaoSerial_L_7:
^RecepcaoSerial.pbas, 92 :: 		end if
$0161	$	RecepcaoSerial_L_8:
$0161	$293C			GOTO	RecepcaoSerial_L_2
^RecepcaoSerial.pbas, 93 :: 		wend
$0162	$2962			GOTO	$
