;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 4/3/2008 13:15:47
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;Acionando.ppas,3 :: 		begin
;Acionando.ppas,5 :: 		trisd:=%00000000;       //Configura todo o PORTD como saída
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0188			CLRF	TRISD, 1
;Acionando.ppas,6 :: 		trisb:=%00000000;       //Configura todo o PORTB como saída
$0007	$0186			CLRF	TRISB, 1
;Acionando.ppas,7 :: 		portd:=%00000001;       //Deixa o pino RD0 em nível alto
$0008	$3001			MOVLW	1
$0009	$1283			BCF	STATUS, RP0
$000A	$0088			MOVWF	PORTD
;Acionando.ppas,8 :: 		portb:=%00100000;       //Liga o pino RB5 para acionar a linha de seleção dos leds
$000B	$3020			MOVLW	32
$000C	$0086			MOVWF	PORTB
$000D	$	Acionando_L_0:
;Acionando.ppas,10 :: 		end.
$000D	$280D			GOTO	$
