;  ASM code generated by mikroVirtualMachine for PIC - V. 5.0.0.2
;  Date/Time: 16/2/2007 14:32:26
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$283E			GOTO	MemoriaEEPROM_main
$0004	$	eepromlib_e_a_eeprom_read:
$0004	$1303			BCF	STATUS, RP1
$0005	$1283			BCF	STATUS, RP0
$0006	$0821			MOVF	FARG_EEprom_read, 0
$0007	$1703			BSF	STATUS, RP1
$0008	$008D			MOVWF	EEADR
$0009	$1683			BSF	STATUS, RP0
$000A	$138C			BCF	EECON1, 7
$000B	$138C			BCF	EECON1, EEPGD
$000C	$140C			BSF	EECON1, RD
$000D	$0000			NOP
$000E	$0000			NOP
$000F	$1283			BCF	STATUS, RP0
$0010	$080C			MOVF	EEDATA, 0
$0011	$1303			BCF	STATUS, RP1
$0012	$00A2			MOVWF	eepromlib_e_a_eeprom_read_local_result
$0013	$	eepromlib_e_a_L_0:
$0013	$0822			MOVF	eepromlib_e_a_eeprom_read_local_result, 0
$0014	$00F0			MOVWF	STACK_0
$0015	$0008			RETURN
$0016	$	eepromlib_e_a_eeprom_write:
$0016	$0000			NOP
$0017	$	eepromlib_e_a_L_3:
$0017	$3000			MOVLW	0
$0018	$1703			BSF	STATUS, RP1
$0019	$1683			BSF	STATUS, RP0
$001A	$188C			BTFSC	EECON1, 1
$001B	$3001			MOVLW	1
$001C	$00F1			MOVWF	STACK_1
$001D	$0871			MOVF	STACK_1, 0
$001E	$3A01			XORLW	1
$001F	$1D03			BTFSS	STATUS, Z
$0020	$2823			GOTO	eepromlib_e_a_L_4
$0021	$0000			NOP
$0022	$2817			GOTO	eepromlib_e_a_L_3
$0023	$	eepromlib_e_a_L_4:
$0023	$1303			BCF	STATUS, RP1
$0024	$1283			BCF	STATUS, RP0
$0025	$0821			MOVF	FARG_EEprom_write, 0
$0026	$1703			BSF	STATUS, RP1
$0027	$008D			MOVWF	EEADR
$0028	$1303			BCF	STATUS, RP1
$0029	$0822			MOVF	FARG_EEprom_write+1, 0
$002A	$1703			BSF	STATUS, RP1
$002B	$008C			MOVWF	EEDATA
$002C	$307F			MOVLW	127
$002D	$1683			BSF	STATUS, RP0
$002E	$050C			ANDWF	EECON1, 0
$002F	$00F0			MOVWF	STACK_0
$0030	$0870			MOVF	STACK_0, 0
$0031	$008C			MOVWF	EECON1
$0032	$3004			MOVLW	4
$0033	$0470			IORWF	STACK_0, 0
$0034	$008C			MOVWF	EECON1
$0035	$138B			BCF	INTCON, 7
$0036	$3055			MOVLW	85
$0037	$008D			MOVWF	EECON2
$0038	$30AA			MOVLW	170
$0039	$008D			MOVWF	EECON2
$003A	$148C			BSF	EECON1, WR
$003B	$178B			BSF	INTCON, 7
$003C	$110C			BCF	EECON1, 2
$003D	$	eepromlib_e_a_L_1:
$003D	$0008			RETURN
$003E	$	MemoriaEEPROM_main:
^MemoriaEEPROM.pbas, 43 :: 		dim dado as byte
$003E	$	MemoriaEEPROM_main_main:
^MemoriaEEPROM.pbas, 77 :: 		portb=0
$003E	$1303			BCF	STATUS, RP1
$003F	$1283			BCF	STATUS, RP0
$0040	$0186			CLRF	PORTB, 1
^MemoriaEEPROM.pbas, 78 :: 		trisb=%00000000            'inicializa o barramento
$0041	$1683			BSF	STATUS, RP0
$0042	$0186			CLRF	TRISB, 1
^MemoriaEEPROM.pbas, 79 :: 		trisd=%00000000            'configura i/o do sistema
$0043	$0188			CLRF	TRISD, 1
^MemoriaEEPROM.pbas, 80 :: 		adcon1=7                   'desliga a/d
$0044	$3007			MOVLW	7
$0045	$009F			MOVWF	ADCON1
^MemoriaEEPROM.pbas, 81 :: 		option_reg=%10000000       'configura prescaler do timer 0
$0046	$3080			MOVLW	128
$0047	$0081			MOVWF	OPTION_REG
^MemoriaEEPROM.pbas, 82 :: 		dado=eeprom_read(0)        'lê a posição zero de memória e carrega no barramento
$0048	$1283			BCF	STATUS, RP0
$0049	$01A1			CLRF	FARG_EEprom_read, 1
$004A	$2004			CALL	eepromlib_e_a_eeprom_read
$004B	$0870			MOVF	STACK_0, 0
$004C	$00A0			MOVWF	main_global_dado
^MemoriaEEPROM.pbas, 88 :: 		while 1 = 1
$004D	$	MemoriaEEPROM_L_2:
$004D	$1303			BCF	STATUS, RP1
$004E	$1283			BCF	STATUS, RP0
^MemoriaEEPROM.pbas, 89 :: 		SEL_LEDS=1                 'liga a saída de leds
$004F	$	MemoriaEEPROM_L_6:
$004F	$1686			BSF	PORTB, 5
$0050	$	MemoriaEEPROM_L_7:
^MemoriaEEPROM.pbas, 90 :: 		portd=dado                 'atualiza a saída de leds
$0050	$0820			MOVF	main_global_dado, 0
$0051	$0088			MOVWF	PORTD
^MemoriaEEPROM.pbas, 91 :: 		delay_ms(500)              'aguarda 1000ms
$0052	$3003			MOVLW	3
$0053	$00FC			MOVWF	STACK_12
$0054	$30FF			MOVLW	255
$0055	$00FB			MOVWF	STACK_11
$0056	$30FF			MOVLW	255
$0057	$00FA			MOVWF	STACK_10
$0058	$0BFC			DECFSZ	STACK_12, F
$0059	$285B			GOTO	$+2
$005A	$2862			GOTO	$+8
$005B	$0BFB			DECFSZ	STACK_11, F
$005C	$285E			GOTO	$+2
$005D	$2861			GOTO	$+4
$005E	$0BFA			DECFSZ	STACK_10, F
$005F	$285E			GOTO	$-1
$0060	$285B			GOTO	$-5
$0061	$2858			GOTO	$-9
$0062	$308C			MOVLW	140
$0063	$00FB			MOVWF	STACK_11
$0064	$30FF			MOVLW	255
$0065	$00FA			MOVWF	STACK_10
$0066	$0BFB			DECFSZ	STACK_11, F
$0067	$2869			GOTO	$+2
$0068	$286C			GOTO	$+4
$0069	$0BFA			DECFSZ	STACK_10, F
$006A	$2869			GOTO	$-1
$006B	$2866			GOTO	$-5
$006C	$30A1			MOVLW	161
$006D	$00FA			MOVWF	STACK_10
$006E	$0BFA			DECFSZ	STACK_10, F
$006F	$286E			GOTO	$-1
$0070	$0000			NOP
^MemoriaEEPROM.pbas, 93 :: 		SEL_LEDS=0                 'desliga saída de leds
$0071	$1286			BCF	PORTB, 5
$0072	$	MemoriaEEPROM_L_9:
^MemoriaEEPROM.pbas, 94 :: 		portd=%11111110            'seleciona linha 1 do teclado matricial
$0072	$30FE			MOVLW	254
$0073	$0088			MOVWF	PORTD
^MemoriaEEPROM.pbas, 95 :: 		delay_us(10)               'tempo de acomodação
$0074	$3003			MOVLW	3
$0075	$00FA			MOVWF	STACK_10
$0076	$0BFA			DECFSZ	STACK_10, F
$0077	$2876			GOTO	$-1
^MemoriaEEPROM.pbas, 97 :: 		if COL1=0 then             'se o botão estiver pressioando...
$0078	$3000			MOVLW	0
$0079	$1A05			BTFSC	PORTA, 4
$007A	$3001			MOVLW	1
$007B	$00F1			MOVWF	STACK_1
$007C	$0871			MOVF	STACK_1, 0
$007D	$3A00			XORLW	0
$007E	$1D03			BTFSS	STATUS, Z
$007F	$2888			GOTO	MemoriaEEPROM_L_11
$0080	$	MemoriaEEPROM_L_10:
^MemoriaEEPROM.pbas, 98 :: 		dado=dado+1            'incrementa o dado
$0080	$0A20			INCF	main_global_dado, 0
$0081	$00F0			MOVWF	STACK_0
$0082	$0870			MOVF	STACK_0, 0
$0083	$00A0			MOVWF	main_global_dado
^MemoriaEEPROM.pbas, 99 :: 		eeprom_write(0,dado)   'atualiza a eeprom
$0084	$01A1			CLRF	FARG_EEprom_write, 1
$0085	$0870			MOVF	STACK_0, 0
$0086	$00A2			MOVWF	FARG_EEprom_write+1
$0087	$2016			CALL	eepromlib_e_a_eeprom_write
$0088	$	MemoriaEEPROM_L_11:
$0088	$1703			BSF	STATUS, RP1
$0089	$1683			BSF	STATUS, RP0
^MemoriaEEPROM.pbas, 100 :: 		end if
$008A	$	MemoriaEEPROM_L_12:
^MemoriaEEPROM.pbas, 102 :: 		if COL2=0 then             'se o botão estiver pressioando...
$008A	$3000			MOVLW	0
$008B	$1303			BCF	STATUS, RP1
$008C	$1283			BCF	STATUS, RP0
$008D	$1A85			BTFSC	PORTA, 5
$008E	$3001			MOVLW	1
$008F	$00F1			MOVWF	STACK_1
$0090	$0871			MOVF	STACK_1, 0
$0091	$3A00			XORLW	0
$0092	$1D03			BTFSS	STATUS, Z
$0093	$289C			GOTO	MemoriaEEPROM_L_14
$0094	$	MemoriaEEPROM_L_13:
^MemoriaEEPROM.pbas, 103 :: 		dado=dado-1            'decrementa o dado
$0094	$0320			DECF	main_global_dado, 0
$0095	$00F0			MOVWF	STACK_0
$0096	$0870			MOVF	STACK_0, 0
$0097	$00A0			MOVWF	main_global_dado
^MemoriaEEPROM.pbas, 104 :: 		eeprom_write(0,dado)   'atualiza a eeprom
$0098	$01A1			CLRF	FARG_EEprom_write, 1
$0099	$0870			MOVF	STACK_0, 0
$009A	$00A2			MOVWF	FARG_EEprom_write+1
$009B	$2016			CALL	eepromlib_e_a_eeprom_write
$009C	$	MemoriaEEPROM_L_14:
$009C	$1703			BSF	STATUS, RP1
$009D	$1683			BSF	STATUS, RP0
^MemoriaEEPROM.pbas, 105 :: 		end if
$009E	$	MemoriaEEPROM_L_15:
$009E	$284D			GOTO	MemoriaEEPROM_L_2
^MemoriaEEPROM.pbas, 107 :: 		wend
$009F	$289F			GOTO	$
