import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.JMenuItem;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PrincipalGUI.java
 *
 * Created on 19/11/2009, 15:52:43
 */


/**
 *
 * @author Fabio Dela Bruna
 */
public class InterfaceGrafica extends javax.swing.JFrame {


	/** Creates new form PrincipalGUI */
	public InterfaceGrafica() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jSlider2 = new javax.swing.JSlider();
		jSlider3 = new javax.swing.JSlider();
		jSlider4 = new javax.swing.JSlider();
		jSlider5 = new javax.swing.JSlider();
		jSlider6 = new javax.swing.JSlider();
		jSlider7 = new javax.swing.JSlider();
		jSlider8 = new javax.swing.JSlider();
		jSlider9 = new javax.swing.JSlider();
		jSlider10 = new javax.swing.JSlider();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Algorítmos Genéticos - Equalização");

		jSlider2.setMajorTickSpacing(1);
		jSlider2.setMaximum(16);
		jSlider2.setMinorTickSpacing(1);
		jSlider2.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider2.setPaintLabels(true);
		jSlider2.setPaintTicks(true);
		jSlider2.setSnapToTicks(true);
		jSlider2.setToolTipText("Botão 2");
		jSlider2.setValue(0);
		jSlider2.setName("jSlider2"); // NOI18N

		jSlider3.setMajorTickSpacing(1);
		jSlider3.setMaximum(16);
		jSlider3.setMinorTickSpacing(1);
		jSlider3.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider3.setPaintLabels(true);
		jSlider3.setPaintTicks(true);
		jSlider3.setSnapToTicks(true);
		jSlider3.setToolTipText("Botão 3");
		jSlider3.setValue(0);
		jSlider3.setName("jSlider3"); // NOI18N

		jSlider4.setMajorTickSpacing(1);
		jSlider4.setMaximum(16);
		jSlider4.setMinorTickSpacing(1);
		jSlider4.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider4.setPaintLabels(true);
		jSlider4.setPaintTicks(true);
		jSlider4.setSnapToTicks(true);
		jSlider4.setToolTipText("Botão 4");
		jSlider4.setValue(0);
		jSlider4.setName("jSlider4"); // NOI18N

		jSlider5.setMajorTickSpacing(1);
		jSlider5.setMaximum(16);
		jSlider5.setMinorTickSpacing(1);
		jSlider5.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider5.setPaintLabels(true);
		jSlider5.setPaintTicks(true);
		jSlider5.setSnapToTicks(true);
		jSlider5.setToolTipText("Botão 5");
		jSlider5.setValue(0);
		jSlider5.setName("jSlider5"); // NOI18N

		jSlider6.setMajorTickSpacing(1);
		jSlider6.setMaximum(16);
		jSlider6.setMinorTickSpacing(1);
		jSlider6.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider6.setPaintLabels(true);
		jSlider6.setPaintTicks(true);
		jSlider6.setSnapToTicks(true);
		jSlider6.setToolTipText("Botão 6");
		jSlider6.setValue(0);
		jSlider6.setName("jSlider6"); // NOI18N

		jSlider7.setMajorTickSpacing(1);
		jSlider7.setMaximum(16);
		jSlider7.setMinorTickSpacing(1);
		jSlider7.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider7.setPaintLabels(true);
		jSlider7.setPaintTicks(true);
		jSlider7.setSnapToTicks(true);
		jSlider7.setToolTipText("Botão 7");
		jSlider7.setValue(0);
		jSlider7.setName("jSlider7"); // NOI18N

		jSlider8.setMajorTickSpacing(1);
		jSlider8.setMaximum(16);
		jSlider8.setMinorTickSpacing(1);
		jSlider8.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider8.setPaintLabels(true);
		jSlider8.setPaintTicks(true);
		jSlider8.setSnapToTicks(true);
		jSlider8.setToolTipText("Botão 8");
		jSlider8.setValue(0);
		jSlider8.setName("jSlider8"); // NOI18N

		jSlider9.setMajorTickSpacing(1);
		jSlider9.setMaximum(16);
		jSlider9.setMinorTickSpacing(1);
		jSlider9.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider9.setPaintLabels(true);
		jSlider9.setPaintTicks(true);
		jSlider9.setSnapToTicks(true);
		jSlider9.setToolTipText("Botão 9");
		jSlider9.setValue(0);
		jSlider9.setName("jSlider9"); // NOI18N

		jSlider10.setMajorTickSpacing(1);
		jSlider10.setMaximum(16);
		jSlider10.setMinorTickSpacing(1);
		jSlider10.setOrientation(javax.swing.JSlider.VERTICAL);
		jSlider10.setPaintLabels(true);
		jSlider10.setPaintTicks(true);
		jSlider10.setSnapToTicks(true);
		jSlider10.setToolTipText("Botão 1");
		jSlider10.setValue(0);
		jSlider10.setName("jSlider10"); // NOI18N

		jMenuBar1.setName("jMenuBar1"); // NOI18N

		jMenu1.setText("File");
		jMenu1.setName("jMenu1"); // NOI18N

		menuItem = new JMenuItem("Executar");
		menuItem.addActionListener( 
				new ActionListener() {
					public void actionPerformed(ActionEvent e) {
						ag = new AlgoritmoGenetico();
						cr = ag.equalizador();
						String temp = "";

						for (int i = 0; i < cr.getCodigoGenetico().size(); i++) {
							temp += cr.getCodigoGenetico().get(i);
						}

						jSlider10.setValue( convertBinToDec( temp.substring(0, 4)) );
						jSlider2.setValue( convertBinToDec( temp.substring(4, 8)) );
						jSlider3.setValue( convertBinToDec( temp.substring(8, 12)) );
						jSlider4.setValue( convertBinToDec( temp.substring(12, 16)) );
						jSlider5.setValue( convertBinToDec( temp.substring(16, 20)) );
						jSlider6.setValue( convertBinToDec( temp.substring(20, 24)) );
						jSlider7.setValue( convertBinToDec( temp.substring(24, 28)) );
						jSlider8.setValue( convertBinToDec( temp.substring(28, 32)) );
						jSlider9.setValue( convertBinToDec( temp.substring(32, 36)) );

					}
				}
		);
		jMenu1.add(menuItem);

		jMenuBar1.add(jMenu1);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(20, 20, 20)
						.addComponent(jSlider10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(jSlider9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(29, Short.MAX_VALUE))
		);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup()
						.addGap(25, 25, 25)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jSlider2, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider4, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider5, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider6, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider7, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider8, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider9, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(jSlider10, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(22, Short.MAX_VALUE))
		);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InterfaceGrafica().setVisible(true);
			}
		});
	}


	/**
	 * Este exemplo mostra como efetuar a conversão
	 * de um valor binário para decimal.
	 */

	public int convertBinToDec( String binario ) {
		// efetua a conversão de binário para decimal
		int decimal = Integer.parseInt(binario, 2);
		return decimal;
	} 



	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JSlider jSlider10;
	private javax.swing.JSlider jSlider2;
	private javax.swing.JSlider jSlider3;
	private javax.swing.JSlider jSlider4;
	private javax.swing.JSlider jSlider5;
	private javax.swing.JSlider jSlider6;
	private javax.swing.JSlider jSlider7;
	private javax.swing.JSlider jSlider8;
	private javax.swing.JSlider jSlider9;
	private javax.swing.JMenuItem menuItem;
	private static final long serialVersionUID = 1L;
	private AlgoritmoGenetico ag;
	private Cromossomo cr;
	// End of variables declaration//GEN-END:variables

}
