;  ASM code generated by mikroVirtualMachine for PIC - V. 5.0.0.2
;  Date/Time: 30/05/06 16:34:29
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2A60			GOTO	Temperatura_main
$0004	$	delays_delay_1us:
^delays.pbas, 5 :: 		sub procedure Delay_1us
^delays.pbas, 6 :: 		Delay_us(1)
$0004	$0000			NOP
$0005	$	delays_L_0:
$0005	$0008			RETURN
$0006	$	delays_delay_5500us:
^delays.pbas, 29 :: 		sub procedure Delay_5500us
^delays.pbas, 30 :: 		Delay_us(5500)
$0006	$3008			MOVLW	8
$0007	$1303			BCF	STATUS, RP1
$0008	$1283			BCF	STATUS, RP0
$0009	$00FB			MOVWF	STACK_11
$000A	$30FF			MOVLW	255
$000B	$00FA			MOVWF	STACK_10
$000C	$0BFB			DECFSZ	STACK_11, F
$000D	$280F			GOTO	$+2
$000E	$2812			GOTO	$+4
$000F	$0BFA			DECFSZ	STACK_10, F
$0010	$280F			GOTO	$-1
$0011	$280C			GOTO	$-5
$0012	$301E			MOVLW	30
$0013	$00FA			MOVWF	STACK_10
$0014	$0BFA			DECFSZ	STACK_10, F
$0015	$2814			GOTO	$-1
$0016	$	delays_L_6:
$0016	$0008			RETURN
$0017	$	delays_delay_500us:
^delays.pbas, 25 :: 		sub procedure Delay_500us
^delays.pbas, 26 :: 		Delay_us(498)
$0017	$30A5			MOVLW	165
$0018	$1303			BCF	STATUS, RP1
$0019	$1283			BCF	STATUS, RP0
$001A	$00FA			MOVWF	STACK_10
$001B	$0BFA			DECFSZ	STACK_10, F
$001C	$281B			GOTO	$-1
$001D	$0000			NOP
$001E	$0000			NOP
$001F	$	delays_L_5:
$001F	$0008			RETURN
$0020	$	lcd8bit_lcd8_cmd:
$0020	$1303			BCF	STATUS, RP1
$0021	$1283			BCF	STATUS, RP0
$0022	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0023	$0084			MOVWF	FSR
$0024	$0180			CLRF	INDF, 1
$0025	$1BC1			BTFSC	FARG_LCD8_CMD, 7
$0026	$1780			BSF	INDF, __LCD8_DB7
$0027	$1B41			BTFSC	FARG_LCD8_CMD, 6
$0028	$1700			BSF	INDF, __LCD8_DB6
$0029	$1AC1			BTFSC	FARG_LCD8_CMD, 5
$002A	$1680			BSF	INDF, __LCD8_DB5
$002B	$1A41			BTFSC	FARG_LCD8_CMD, 4
$002C	$1600			BSF	INDF, __LCD8_DB4
$002D	$19C1			BTFSC	FARG_LCD8_CMD, 3
$002E	$1580			BSF	INDF, __LCD8_DB3
$002F	$1941			BTFSC	FARG_LCD8_CMD, 2
$0030	$1500			BSF	INDF, __LCD8_DB2
$0031	$18C1			BTFSC	FARG_LCD8_CMD, 1
$0032	$1480			BSF	INDF, __LCD8_DB1
$0033	$1841			BTFSC	FARG_LCD8_CMD, 0
$0034	$1400			BSF	INDF, __LCD8_DB0
$0035	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0036	$0084			MOVWF	FSR
$0037	$0822			MOVF	lcd8bit_main_global_com, 0
$0038	$3A01			XORLW	1
$0039	$1D03			BTFSS	STATUS, Z
$003A	$283D			GOTO	lcd8bit_L_2
$003B	$	lcd8bit_L_1:
$003B	$1100			BCF	INDF, __LCD8_RS
$003C	$283E			GOTO	lcd8bit_L_3
$003D	$	lcd8bit_L_2:
$003D	$1500			BSF	INDF, __LCD8_RS
$003E	$	lcd8bit_L_3:
$003E	$1480			BSF	INDF, __LCD8_ENABLE
$003F	$2004			CALL	delays_delay_1us
$0040	$1080			BCF	INDF, __LCD8_ENABLE
$0041	$0822			MOVF	lcd8bit_main_global_com, 0
$0042	$3A01			XORLW	1
$0043	$1D03			BTFSS	STATUS, Z
$0044	$2847			GOTO	lcd8bit_L_5
$0045	$	lcd8bit_L_4:
$0045	$2006			CALL	delays_delay_5500us
$0046	$2848			GOTO	lcd8bit_L_6
$0047	$	lcd8bit_L_5:
$0047	$2017			CALL	delays_delay_500us
$0048	$	lcd8bit_L_6:
$0048	$	lcd8bit_L_0:
$0048	$0008			RETURN
$0049	$	delays_delay_22us:
^delays.pbas, 13 :: 		sub procedure Delay_22us
^delays.pbas, 14 :: 		Delay_us(22)
$0049	$3007			MOVLW	7
$004A	$1303			BCF	STATUS, RP1
$004B	$1283			BCF	STATUS, RP0
$004C	$00FA			MOVWF	STACK_10
$004D	$0BFA			DECFSZ	STACK_10, F
$004E	$284D			GOTO	$-1
$004F	$	delays_L_2:
$004F	$0008			RETURN
$0050	$	math_mul_16x16_u:
$0050	$1303			BCF	STATUS, RP1
$0051	$1283			BCF	STATUS, RP0
$0052	$01FB			CLRF	STACK_11
$0053	$01FA			CLRF	STACK_10
$0054	$01F9			CLRF	STACK_9
$0055	$3080			MOVLW	128
$0056	$00F8			MOVWF	STACK_8
$0057	$0CF1			RRF	STACK_1, F
$0058	$0CF0			RRF	STACK_0, F
$0059	$1C03			BTFSS	STATUS, C
$005A	$2864			GOTO	$+10
$005B	$0874			MOVF	STACK_4, W
$005C	$07F9			ADDWF	STACK_9, F
$005D	$0875			MOVF	STACK_5, W
$005E	$1803			BTFSC	STATUS, C
$005F	$0F75			INCFSZ	STACK_5, W
$0060	$07FA			ADDWF	STACK_10, F
$0061	$1803			BTFSC	STATUS, C
$0062	$0AFB			INCF	STACK_11, F
$0063	$1003			BCF	STATUS, C
$0064	$1FF0			BTFSS	STACK_0, 7
$0065	$286C			GOTO	$+7
$0066	$0874			MOVF	STACK_4, W
$0067	$07FA			ADDWF	STACK_10, F
$0068	$0875			MOVF	STACK_5, W
$0069	$1803			BTFSC	STATUS, C
$006A	$0F75			INCFSZ	STACK_5, W
$006B	$07FB			ADDWF	STACK_11, F
$006C	$0CFB			RRF	STACK_11, F
$006D	$0CFA			RRF	STACK_10, F
$006E	$0CF9			RRF	STACK_9, F
$006F	$0CF8			RRF	STACK_8, F
$0070	$1C03			BTFSS	STATUS, C
$0071	$2857			GOTO	$-26
$0072	$087B			MOVF	STACK_11, W
$0073	$00F3			MOVWF	STACK_3
$0074	$087A			MOVF	STACK_10, W
$0075	$00F2			MOVWF	STACK_2
$0076	$0879			MOVF	STACK_9, W
$0077	$00F1			MOVWF	STACK_1
$0078	$0878			MOVF	STACK_8, W
$0079	$00F0			MOVWF	STACK_0
$007A	$	math_L_1:
$007A	$0008			RETURN
$007B	$	math_div_16x16_u:
$007B	$1303			BCF	STATUS, RP1
$007C	$1283			BCF	STATUS, RP0
$007D	$01F8			CLRF	STACK_8
$007E	$01F9			CLRF	STACK_9
$007F	$3010			MOVLW	16
$0080	$00FC			MOVWF	STACK_12
$0081	$0D71			RLF	STACK_1, W
$0082	$0DF8			RLF	STACK_8, F
$0083	$0DF9			RLF	STACK_9, F
$0084	$0874			MOVF	STACK_4, W
$0085	$02F8			SUBWF	STACK_8, F
$0086	$0875			MOVF	STACK_5, W
$0087	$1C03			BTFSS	STATUS, C
$0088	$0F75			INCFSZ	STACK_5, W
$0089	$02F9			SUBWF	STACK_9, F
$008A	$1803			BTFSC	STATUS, C
$008B	$2893			GOTO	$+8
$008C	$0874			MOVF	STACK_4, W
$008D	$07F8			ADDWF	STACK_8, F
$008E	$0875			MOVF	STACK_5, W
$008F	$1803			BTFSC	STATUS, C
$0090	$0F75			INCFSZ	STACK_5, W
$0091	$07F9			ADDWF	STACK_9, F
$0092	$1003			BCF	STATUS, C
$0093	$0DF0			RLF	STACK_0, F
$0094	$0DF1			RLF	STACK_1, F
$0095	$0BFC			DECFSZ	STACK_12, F
$0096	$2881			GOTO	$-21
$0097	$	math_L_3:
$0097	$0008			RETURN
$0098	$	lcd8bit_lcd8_out:
$0098	$	lcd8bit_L_26:
$0098	$1303			BCF	STATUS, RP1
$0099	$1283			BCF	STATUS, RP0
$009A	$083C			MOVF	FARG_Lcd8_Out, 0
$009B	$3A01			XORLW	1
$009C	$1D03			BTFSS	STATUS, Z
$009D	$28A1			GOTO	lcd8bit_L_27
$009E	$	lcd8bit_L_25:
$009E	$3080			MOVLW	128
$009F	$00BC			MOVWF	FARG_Lcd8_Out
$00A0	$28B8			GOTO	lcd8bit_L_24
$00A1	$	lcd8bit_L_27:
$00A1	$	lcd8bit_L_29:
$00A1	$083C			MOVF	FARG_Lcd8_Out, 0
$00A2	$3A02			XORLW	2
$00A3	$1D03			BTFSS	STATUS, Z
$00A4	$28A8			GOTO	lcd8bit_L_30
$00A5	$	lcd8bit_L_28:
$00A5	$30C0			MOVLW	192
$00A6	$00BC			MOVWF	FARG_Lcd8_Out
$00A7	$28B8			GOTO	lcd8bit_L_24
$00A8	$	lcd8bit_L_30:
$00A8	$	lcd8bit_L_32:
$00A8	$083C			MOVF	FARG_Lcd8_Out, 0
$00A9	$3A03			XORLW	3
$00AA	$1D03			BTFSS	STATUS, Z
$00AB	$28AF			GOTO	lcd8bit_L_33
$00AC	$	lcd8bit_L_31:
$00AC	$3094			MOVLW	148
$00AD	$00BC			MOVWF	FARG_Lcd8_Out
$00AE	$28B8			GOTO	lcd8bit_L_24
$00AF	$	lcd8bit_L_33:
$00AF	$	lcd8bit_L_35:
$00AF	$083C			MOVF	FARG_Lcd8_Out, 0
$00B0	$3A04			XORLW	4
$00B1	$1D03			BTFSS	STATUS, Z
$00B2	$28B6			GOTO	lcd8bit_L_36
$00B3	$	lcd8bit_L_34:
$00B3	$30D4			MOVLW	212
$00B4	$00BC			MOVWF	FARG_Lcd8_Out
$00B5	$28B8			GOTO	lcd8bit_L_24
$00B6	$	lcd8bit_L_36:
$00B6	$3080			MOVLW	128
$00B7	$00BC			MOVWF	FARG_Lcd8_Out
$00B8	$	lcd8bit_L_24:
$00B8	$083D			MOVF	FARG_Lcd8_Out+1, 0
$00B9	$073C			ADDWF	FARG_Lcd8_Out, 0
$00BA	$00F0			MOVWF	STACK_0
$00BB	$03F0			DECF	STACK_0, 1
$00BC	$0870			MOVF	STACK_0, 0
$00BD	$00BC			MOVWF	FARG_Lcd8_Out
$00BE	$0870			MOVF	STACK_0, 0
$00BF	$00C1			MOVWF	FARG_Lcd8_Cmd
$00C0	$2020			CALL	lcd8bit_lcd8_cmd
$00C1	$01A2			CLRF	lcd8bit_main_global_com, 1
$00C2	$01BF			CLRF	lcd8bit_lcd8_out_local_i, 1
$00C3	$083E			MOVF	FARG_Lcd8_Out+2, 0
$00C4	$0084			MOVWF	FSR
$00C5	$0800			MOVF	INDF, 0
$00C6	$00C0			MOVWF	lcd8bit_lcd8_out_local_a
$00C7	$	lcd8bit_L_38:
$00C7	$0840			MOVF	lcd8bit_lcd8_out_local_a, 0
$00C8	$3A00			XORLW	0
$00C9	$1903			BTFSC	STATUS, Z
$00CA	$28D7			GOTO	lcd8bit_L_39
$00CB	$0840			MOVF	lcd8bit_lcd8_out_local_a, 0
$00CC	$00C1			MOVWF	FARG_Lcd8_Cmd
$00CD	$2020			CALL	lcd8bit_lcd8_cmd
$00CE	$0ABF			INCF	lcd8bit_lcd8_out_local_i, 1
$00CF	$083F			MOVF	lcd8bit_lcd8_out_local_i, 0
$00D0	$073E			ADDWF	FARG_Lcd8_Out+2, 0
$00D1	$00F0			MOVWF	STACK_0
$00D2	$0870			MOVF	STACK_0, 0
$00D3	$0084			MOVWF	FSR
$00D4	$0800			MOVF	INDF, 0
$00D5	$00C0			MOVWF	lcd8bit_lcd8_out_local_a
$00D6	$28C7			GOTO	lcd8bit_L_38
$00D7	$	lcd8bit_L_39:
$00D7	$3001			MOVLW	1
$00D8	$00A2			MOVWF	lcd8bit_main_global_com
$00D9	$	lcd8bit_L_23:
$00D9	$0008			RETURN
$00DA	$	pwmlib_p_a_pwm_start:
$00DA	$1303			BCF	STATUS, RP1
$00DB	$1683			BSF	STATUS, RP0
$00DC	$1107			BCF	TRISC, 2
$00DD	$1283			BCF	STATUS, RP0
$00DE	$1512			BSF	T2CON, 2
$00DF	$300C			MOVLW	12
$00E0	$0497			IORWF	CCP1CON, 1
$00E1	$	pwmlib_p_a_L_2:
$00E1	$0008			RETURN
$00E2	$	adclib_a_c_adc_read:
$00E2	$1303			BCF	STATUS, RP1
$00E3	$1283			BCF	STATUS, RP0
$00E4	$019F			CLRF	ADCON0, 1
$00E5	$30C0			MOVLW	192
$00E6	$049F			IORWF	ADCON0, 1
$00E7	$3040			MOVLW	64
$00E8	$1683			BSF	STATUS, RP0
$00E9	$041F			IORWF	ADCON1, 0
$00EA	$00F0			MOVWF	STACK_0
$00EB	$0870			MOVF	STACK_0, 0
$00EC	$009F			MOVWF	ADCON1
$00ED	$3080			MOVLW	128
$00EE	$0470			IORWF	STACK_0, 0
$00EF	$009F			MOVWF	ADCON1
$00F0	$1283			BCF	STATUS, RP0
$00F1	$083C			MOVF	FARG_ADC_read, 0
$00F2	$00F0			MOVWF	STACK_0
$00F3	$0DF0			RLF	STACK_0, 1
$00F4	$1070			BCF	STACK_0, 0
$00F5	$0DF0			RLF	STACK_0, 1
$00F6	$1070			BCF	STACK_0, 0
$00F7	$0DF0			RLF	STACK_0, 1
$00F8	$1070			BCF	STACK_0, 0
$00F9	$0870			MOVF	STACK_0, 0
$00FA	$049F			IORWF	ADCON0, 1
$00FB	$141F			BSF	ADCON0, 0
$00FC	$2049			CALL	delays_delay_22us
$00FD	$151F			BSF	ADCON0, 2
$00FE	$	adclib_a_c_L_2:
$00FE	$3000			MOVLW	0
$00FF	$191F			BTFSC	ADCON0, 2
$0100	$3001			MOVLW	1
$0101	$00F2			MOVWF	STACK_2
$0102	$0872			MOVF	STACK_2, 0
$0103	$3A01			XORLW	1
$0104	$1D03			BTFSS	STATUS, Z
$0105	$2908			GOTO	adclib_a_c_L_3
$0106	$0000			NOP
$0107	$28FE			GOTO	adclib_a_c_L_2
$0108	$	adclib_a_c_L_3:
$0108	$081E			MOVF	ADRESH, 0
$0109	$00F2			MOVWF	STACK_2
$010A	$01F3			CLRF	STACK_2+1
$010B	$0872			MOVF	STACK_2, 0
$010C	$00F3			MOVWF	STACK_2+1
$010D	$01F2			CLRF	STACK_2
$010E	$0872			MOVF	STACK_2, 0
$010F	$00BD			MOVWF	adclib_a_c_adc_read_local_result
$0110	$0873			MOVF	STACK_2+1, 0
$0111	$00BE			MOVWF	adclib_a_c_adc_read_local_result+1
$0112	$1683			BSF	STATUS, RP0
$0113	$081E			MOVF	ADRESL, 0
$0114	$0472			IORWF	STACK_2, 0
$0115	$1283			BCF	STATUS, RP0
$0116	$00BD			MOVWF	adclib_a_c_adc_read_local_result
$0117	$0873			MOVF	STACK_2+1, 0
$0118	$00BE			MOVWF	adclib_a_c_adc_read_local_result+1
$0119	$3000			MOVLW	0
$011A	$04BE			IORWF	adclib_a_c_adc_read_local_result+1, 1
$011B	$101F			BCF	ADCON0, 0
$011C	$	adclib_a_c_L_0:
$011C	$083D			MOVF	adclib_a_c_adc_read_local_result, 0
$011D	$00F0			MOVWF	STACK_0
$011E	$083E			MOVF	adclib_a_c_adc_read_local_result+1, 0
$011F	$00F1			MOVWF	STACK_0+1
$0120	$0008			RETURN
$0121	$	pwmlib_p_a_pwm_change_duty:
$0121	$1303			BCF	STATUS, RP1
$0122	$1683			BSF	STATUS, RP0
$0123	$0812			MOVF	PR2, 0
$0124	$00F0			MOVWF	STACK_0
$0125	$01F1			CLRF	STACK_0+1
$0126	$0870			MOVF	STACK_0, 0
$0127	$3F01			ADDLW	1
$0128	$00F4			MOVWF	STACK_4
$0129	$3000			MOVLW	0
$012A	$1803			BTFSC	STATUS, C
$012B	$3F01			ADDLW	1
$012C	$0771			ADDWF	STACK_0+1, 0
$012D	$00F5			MOVWF	STACK_4+1
$012E	$1283			BCF	STATUS, RP0
$012F	$083C			MOVF	FARG_PWM_Change_Duty, 0
$0130	$00F0			MOVWF	STACK_0
$0131	$01F1			CLRF	STACK_0+1
$0132	$2050			CALL	math_mul_16x16_u
$0133	$3006			MOVLW	6
$0134	$00F2			MOVWF	STACK_2
$0135	$0870			MOVF	STACK_0, 0
$0136	$00F8			MOVWF	STACK_8
$0137	$0871			MOVF	STACK_0+1, 0
$0138	$00F9			MOVWF	STACK_8+1
$0139	$0872			MOVF	STACK_2, 0
$013A	$	L_PWM_Change_Duty_0:
$013A	$1903			BTFSC	STATUS, Z
$013B	$2941			GOTO	L_PWM_Change_Duty_1
$013C	$0CF9			RRF	STACK_8+1, 1
$013D	$0CF8			RRF	STACK_8, 1
$013E	$13F9			BCF	STACK_8+1, 7
$013F	$3FFF			ADDLW	255
$0140	$293A			GOTO	L_PWM_Change_Duty_0
$0141	$	L_PWM_Change_Duty_1:
$0141	$0878			MOVF	STACK_8, 0
$0142	$00F0			MOVWF	STACK_0
$0143	$0879			MOVF	STACK_8+1, 0
$0144	$00F1			MOVWF	STACK_0+1
$0145	$0DF0			RLF	STACK_0, 1
$0146	$0DF1			RLF	STACK_0+1, 1
$0147	$1070			BCF	STACK_0, 0
$0148	$0DF0			RLF	STACK_0, 1
$0149	$0DF1			RLF	STACK_0+1, 1
$014A	$1070			BCF	STACK_0, 0
$014B	$0DF0			RLF	STACK_0, 1
$014C	$0DF1			RLF	STACK_0+1, 1
$014D	$1070			BCF	STACK_0, 0
$014E	$0DF0			RLF	STACK_0, 1
$014F	$0DF1			RLF	STACK_0+1, 1
$0150	$1070			BCF	STACK_0, 0
$0151	$3030			MOVLW	48
$0152	$0570			ANDWF	STACK_0, 0
$0153	$00F6			MOVWF	STACK_6
$0154	$0871			MOVF	STACK_0+1, 0
$0155	$00F7			MOVWF	STACK_6+1
$0156	$3000			MOVLW	0
$0157	$05F7			ANDWF	STACK_6+1, 1
$0158	$0878			MOVF	STACK_8, 0
$0159	$00F0			MOVWF	STACK_0
$015A	$0879			MOVF	STACK_8+1, 0
$015B	$00F1			MOVWF	STACK_0+1
$015C	$0CF1			RRF	STACK_0+1, 1
$015D	$0CF0			RRF	STACK_0, 1
$015E	$13F1			BCF	STACK_0+1, 7
$015F	$0CF1			RRF	STACK_0+1, 1
$0160	$0CF0			RRF	STACK_0, 1
$0161	$13F1			BCF	STACK_0+1, 7
$0162	$0870			MOVF	STACK_0, 0
$0163	$0095			MOVWF	CCPR1L
$0164	$300F			MOVLW	15
$0165	$0597			ANDWF	CCP1CON, 1
$0166	$0876			MOVF	STACK_6, 0
$0167	$0497			IORWF	CCP1CON, 1
$0168	$	pwmlib_p_a_L_1:
$0168	$0008			RETURN
$0169	$	conv_wordtostr:
$0169	$3001			MOVLW	1
$016A	$1303			BCF	STATUS, RP1
$016B	$1283			BCF	STATUS, RP0
$016C	$00BF			MOVWF	conv_wordtostr_local_len
$016D	$083D			MOVF	FARG_WordToStr+1, 0
$016E	$3C00			SUBLW	0
$016F	$1D03			BTFSS	STATUS, Z
$0170	$2973			GOTO	L_WordToStr_0
$0171	$083C			MOVF	FARG_WordToStr, 0
$0172	$3C09			SUBLW	9
$0173	$	L_WordToStr_0:
$0173	$1803			BTFSC	STATUS, C
$0174	$2976			GOTO	conv_L_15
$0175	$	conv_L_14:
$0175	$0ABF			INCF	conv_wordtostr_local_len, 1
$0176	$	conv_L_15:
$0176	$	conv_L_16:
$0176	$083D			MOVF	FARG_WordToStr+1, 0
$0177	$3C00			SUBLW	0
$0178	$1D03			BTFSS	STATUS, Z
$0179	$297C			GOTO	L_WordToStr_1
$017A	$083C			MOVF	FARG_WordToStr, 0
$017B	$3C63			SUBLW	99
$017C	$	L_WordToStr_1:
$017C	$1803			BTFSC	STATUS, C
$017D	$297F			GOTO	conv_L_18
$017E	$	conv_L_17:
$017E	$0ABF			INCF	conv_wordtostr_local_len, 1
$017F	$	conv_L_18:
$017F	$	conv_L_19:
$017F	$083D			MOVF	FARG_WordToStr+1, 0
$0180	$3C03			SUBLW	3
$0181	$1D03			BTFSS	STATUS, Z
$0182	$2985			GOTO	L_WordToStr_2
$0183	$083C			MOVF	FARG_WordToStr, 0
$0184	$3CE7			SUBLW	231
$0185	$	L_WordToStr_2:
$0185	$1803			BTFSC	STATUS, C
$0186	$2988			GOTO	conv_L_21
$0187	$	conv_L_20:
$0187	$0ABF			INCF	conv_wordtostr_local_len, 1
$0188	$	conv_L_21:
$0188	$	conv_L_22:
$0188	$083D			MOVF	FARG_WordToStr+1, 0
$0189	$3C27			SUBLW	39
$018A	$1D03			BTFSS	STATUS, Z
$018B	$298E			GOTO	L_WordToStr_3
$018C	$083C			MOVF	FARG_WordToStr, 0
$018D	$3C0F			SUBLW	15
$018E	$	L_WordToStr_3:
$018E	$1803			BTFSC	STATUS, C
$018F	$2991			GOTO	conv_L_24
$0190	$	conv_L_23:
$0190	$0ABF			INCF	conv_wordtostr_local_len, 1
$0191	$	conv_L_24:
$0191	$	conv_L_25:
$0191	$083E			MOVF	FARG_WordToStr+2, 0
$0192	$0084			MOVWF	FSR
$0193	$3020			MOVLW	32
$0194	$0080			MOVWF	INDF
$0195	$0A84			INCF	FSR, 1
$0196	$0080			MOVWF	INDF
$0197	$0A84			INCF	FSR, 1
$0198	$0080			MOVWF	INDF
$0199	$0A84			INCF	FSR, 1
$019A	$0080			MOVWF	INDF
$019B	$0A84			INCF	FSR, 1
$019C	$0080			MOVWF	INDF
$019D	$0A84			INCF	FSR, 1
$019E	$0180			CLRF	INDF
$019F	$0384			DECF	FSR, 1
$01A0	$	conv_L_28:
$01A0	$083F			MOVF	conv_wordtostr_local_len, 0
$01A1	$3C00			SUBLW	0
$01A2	$1803			BTFSC	STATUS, C
$01A3	$29C2			GOTO	conv_L_29
$01A4	$300A			MOVLW	10
$01A5	$00F4			MOVWF	STACK_4
$01A6	$01F5			CLRF	STACK_4+1
$01A7	$083C			MOVF	FARG_WordToStr, 0
$01A8	$00F0			MOVWF	STACK_0
$01A9	$083D			MOVF	FARG_WordToStr+1, 0
$01AA	$00F1			MOVWF	STACK_0+1
$01AB	$207B			CALL	math_div_16x16_u
$01AC	$0878			MOVF	STACK_8, 0
$01AD	$00F0			MOVWF	STACK_0
$01AE	$0879			MOVF	STACK_9, 0
$01AF	$00F1			MOVWF	STACK_1
$01B0	$3030			MOVLW	48
$01B1	$0770			ADDWF	STACK_0, 0
$01B2	$0080			MOVWF	INDF
$01B3	$0384			DECF	FSR, 1
$01B4	$300A			MOVLW	10
$01B5	$00F4			MOVWF	STACK_4
$01B6	$01F5			CLRF	STACK_4+1
$01B7	$083C			MOVF	FARG_WordToStr, 0
$01B8	$00F0			MOVWF	STACK_0
$01B9	$083D			MOVF	FARG_WordToStr+1, 0
$01BA	$00F1			MOVWF	STACK_0+1
$01BB	$207B			CALL	math_div_16x16_u
$01BC	$0870			MOVF	STACK_0, 0
$01BD	$00BC			MOVWF	FARG_WordToStr
$01BE	$0871			MOVF	STACK_0+1, 0
$01BF	$00BD			MOVWF	FARG_WordToStr+1
$01C0	$03BF			DECF	conv_wordtostr_local_len, 1
$01C1	$29A0			GOTO	conv_L_28
$01C2	$	conv_L_29:
$01C2	$	conv_L_13:
$01C2	$0008			RETURN
$01C3	$	strcat_strcat:
$01C3	$1303			BCF	STATUS, RP1
$01C4	$1283			BCF	STATUS, RP0
$01C5	$01BE			CLRF	strcat_strcat_local_i, 1
$01C6	$01BF			CLRF	strcat_strcat_local_j, 1
$01C7	$	strcat_L_2:
$01C7	$083E			MOVF	strcat_strcat_local_i, 0
$01C8	$073C			ADDWF	FARG_strcat, 0
$01C9	$00F0			MOVWF	STACK_0
$01CA	$0870			MOVF	STACK_0, 0
$01CB	$0084			MOVWF	FSR
$01CC	$0800			MOVF	INDF, 0
$01CD	$00F1			MOVWF	STACK_1
$01CE	$0871			MOVF	STACK_1, 0
$01CF	$3A00			XORLW	0
$01D0	$1903			BTFSC	STATUS, Z
$01D1	$29D4			GOTO	strcat_L_3
$01D2	$0ABE			INCF	strcat_strcat_local_i, 1
$01D3	$29C7			GOTO	strcat_L_2
$01D4	$	strcat_L_3:
$01D4	$	strcat_L_7:
$01D4	$083F			MOVF	strcat_strcat_local_j, 0
$01D5	$073D			ADDWF	FARG_strcat+1, 0
$01D6	$00F0			MOVWF	STACK_0
$01D7	$0870			MOVF	STACK_0, 0
$01D8	$0084			MOVWF	FSR
$01D9	$0800			MOVF	INDF, 0
$01DA	$00F1			MOVWF	STACK_1
$01DB	$0871			MOVF	STACK_1, 0
$01DC	$3A00			XORLW	0
$01DD	$1903			BTFSC	STATUS, Z
$01DE	$29F0			GOTO	strcat_L_8
$01DF	$083E			MOVF	strcat_strcat_local_i, 0
$01E0	$073C			ADDWF	FARG_strcat, 0
$01E1	$00F1			MOVWF	STACK_1
$01E2	$083F			MOVF	strcat_strcat_local_j, 0
$01E3	$073D			ADDWF	FARG_strcat+1, 0
$01E4	$00F0			MOVWF	STACK_0
$01E5	$0870			MOVF	STACK_0, 0
$01E6	$0084			MOVWF	FSR
$01E7	$0800			MOVF	INDF, 0
$01E8	$00F0			MOVWF	STACK_0
$01E9	$0871			MOVF	STACK_1, 0
$01EA	$0084			MOVWF	FSR
$01EB	$0870			MOVF	STACK_0, 0
$01EC	$0080			MOVWF	INDF
$01ED	$0ABE			INCF	strcat_strcat_local_i, 1
$01EE	$0ABF			INCF	strcat_strcat_local_j, 1
$01EF	$29D4			GOTO	strcat_L_7
$01F0	$	strcat_L_8:
$01F0	$083E			MOVF	strcat_strcat_local_i, 0
$01F1	$073C			ADDWF	FARG_strcat, 0
$01F2	$00F0			MOVWF	STACK_0
$01F3	$0870			MOVF	STACK_0, 0
$01F4	$0084			MOVWF	FSR
$01F5	$0180			CLRF	INDF, 1
$01F6	$	strcat_L_0:
$01F6	$0008			RETURN
$01F7	$	lcd8bit_lcd8_init:
$01F7	$2006			CALL	delays_delay_5500us
$01F8	$2006			CALL	delays_delay_5500us
$01F9	$2006			CALL	delays_delay_5500us
$01FA	$083D			MOVF	FARG_Lcd8_Init+1, 0
$01FB	$00A0			MOVWF	lcd8bit_main_global_dataaddress
$01FC	$083C			MOVF	FARG_Lcd8_Init, 0
$01FD	$00A1			MOVWF	lcd8bit_main_global_ctrladdress
$01FE	$083D			MOVF	FARG_Lcd8_Init+1, 0
$01FF	$0084			MOVWF	FSR
$0200	$1784			BSF	FSR, 7
$0201	$0180			CLRF	INDF, 1
$0202	$083C			MOVF	FARG_Lcd8_Init, 0
$0203	$0084			MOVWF	FSR
$0204	$1180			BCF	INDF, __LCD8_RW
$0205	$1784			BSF	FSR, 7
$0206	$1100			BCF	INDF, __LCD8_RS
$0207	$1180			BCF	INDF, __LCD8_RW
$0208	$1080			BCF	INDF, __LCD8_ENABLE
$0209	$1384			BCF	FSR, 7
$020A	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$020B	$0084			MOVWF	FSR
$020C	$3030			MOVLW	48
$020D	$0080			MOVWF	INDF
$020E	$2006			CALL	delays_delay_5500us
$020F	$2006			CALL	delays_delay_5500us
$0210	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0211	$0084			MOVWF	FSR
$0212	$1480			BSF	INDF, __LCD8_ENABLE
$0213	$2004			CALL	delays_delay_1us
$0214	$1080			BCF	INDF, __LCD8_ENABLE
$0215	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0216	$0084			MOVWF	FSR
$0217	$3030			MOVLW	48
$0218	$0080			MOVWF	INDF
$0219	$2006			CALL	delays_delay_5500us
$021A	$2006			CALL	delays_delay_5500us
$021B	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$021C	$0084			MOVWF	FSR
$021D	$1480			BSF	INDF, __LCD8_ENABLE
$021E	$2004			CALL	delays_delay_1us
$021F	$1080			BCF	INDF, __LCD8_ENABLE
$0220	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0221	$0084			MOVWF	FSR
$0222	$3030			MOVLW	48
$0223	$0080			MOVWF	INDF
$0224	$2006			CALL	delays_delay_5500us
$0225	$2006			CALL	delays_delay_5500us
$0226	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0227	$0084			MOVWF	FSR
$0228	$1480			BSF	INDF, __LCD8_ENABLE
$0229	$2004			CALL	delays_delay_1us
$022A	$1080			BCF	INDF, __LCD8_ENABLE
$022B	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$022C	$0084			MOVWF	FSR
$022D	$3038			MOVLW	56
$022E	$0080			MOVWF	INDF
$022F	$2006			CALL	delays_delay_5500us
$0230	$2006			CALL	delays_delay_5500us
$0231	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0232	$0084			MOVWF	FSR
$0233	$1480			BSF	INDF, __LCD8_ENABLE
$0234	$2004			CALL	delays_delay_1us
$0235	$1080			BCF	INDF, __LCD8_ENABLE
$0236	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0237	$0084			MOVWF	FSR
$0238	$3010			MOVLW	16
$0239	$0080			MOVWF	INDF
$023A	$2006			CALL	delays_delay_5500us
$023B	$2006			CALL	delays_delay_5500us
$023C	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$023D	$0084			MOVWF	FSR
$023E	$1480			BSF	INDF, __LCD8_ENABLE
$023F	$2004			CALL	delays_delay_1us
$0240	$1080			BCF	INDF, __LCD8_ENABLE
$0241	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0242	$0084			MOVWF	FSR
$0243	$3001			MOVLW	1
$0244	$0080			MOVWF	INDF
$0245	$2006			CALL	delays_delay_5500us
$0246	$2006			CALL	delays_delay_5500us
$0247	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0248	$0084			MOVWF	FSR
$0249	$1480			BSF	INDF, __LCD8_ENABLE
$024A	$2004			CALL	delays_delay_1us
$024B	$1080			BCF	INDF, __LCD8_ENABLE
$024C	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$024D	$0084			MOVWF	FSR
$024E	$300F			MOVLW	15
$024F	$0080			MOVWF	INDF
$0250	$2006			CALL	delays_delay_5500us
$0251	$2006			CALL	delays_delay_5500us
$0252	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0253	$0084			MOVWF	FSR
$0254	$1480			BSF	INDF, __LCD8_ENABLE
$0255	$2004			CALL	delays_delay_1us
$0256	$1080			BCF	INDF, __LCD8_ENABLE
$0257	$3001			MOVLW	1
$0258	$00A2			MOVWF	lcd8bit_main_global_com
$0259	$	lcd8bit_L_22:
$0259	$0008			RETURN
$025A	$	pwmlib_p_a_pwm_init:
$025A	$1303			BCF	STATUS, RP1
$025B	$1283			BCF	STATUS, RP0
$025C	$0195			CLRF	CCPR1L, 1
$025D	$1217			BCF	CCP1CON, 4
$025E	$1297			BCF	CCP1CON, 5
$025F	$	pwmlib_p_a_L_0:
$025F	$0008			RETURN
$0260	$	Temperatura_main:
^Temperatura.pbas, 36 :: 		dim string_ad as string[10]
$0260	$	Temperatura_main_main:
^Temperatura.pbas, 62 :: 		adcon1=%10000100
$0260	$3084			MOVLW	132
$0261	$1303			BCF	STATUS, RP1
$0262	$1683			BSF	STATUS, RP0
$0263	$009F			MOVWF	ADCON1
^Temperatura.pbas, 63 :: 		adcon0=%01011001                           ' Configura o ad
$0264	$3059			MOVLW	89
$0265	$1283			BCF	STATUS, RP0
$0266	$009F			MOVWF	ADCON0
^Temperatura.pbas, 64 :: 		trisa=%11111111                            ' põe todos os pinos para entrada
$0267	$30FF			MOVLW	255
$0268	$1683			BSF	STATUS, RP0
$0269	$0085			MOVWF	TRISA
^Temperatura.pbas, 65 :: 		trisc=%00000000
$026A	$0187			CLRF	TRISC, 1
^Temperatura.pbas, 66 :: 		trisd=%00000000
$026B	$0188			CLRF	TRISD, 1
^Temperatura.pbas, 67 :: 		trise=%00000001                             'configura i/os
$026C	$3001			MOVLW	1
$026D	$0089			MOVWF	TRISE
^Temperatura.pbas, 68 :: 		option_reg=%10000000                        'configura prescaler do timer 0
$026E	$3080			MOVLW	128
$026F	$0081			MOVWF	OPTION_REG
^Temperatura.pbas, 69 :: 		Lcd8_Config(PORTE, PORTD, 2, 1, 3, 7, 6, 5, 4, 3, 2, 1, 0)
$0270	$3009			MOVLW	PORTE
$0271	$1283			BCF	STATUS, RP0
$0272	$00BC			MOVWF	farg_Lcd8_Init
$0273	$3008			MOVLW	PORTD
$0274	$00BD			MOVWF	farg_Lcd8_Init+1
$0275	$21F7			CALL	lcd8bit_lcd8_init
^Temperatura.pbas, 70 :: 		Lcd8_Cmd(LCD_CLEAR)                         'limpa o display
$0276	$3001			MOVLW	1
$0277	$00C1			MOVWF	FARG_Lcd8_Cmd
$0278	$2020			CALL	lcd8bit_lcd8_cmd
^Temperatura.pbas, 71 :: 		Lcd8_Cmd(LCD_CURSOR_OFF)                    'Desliga o cursor
$0279	$300C			MOVLW	12
$027A	$00C1			MOVWF	FARG_Lcd8_Cmd
$027B	$2020			CALL	lcd8bit_lcd8_cmd
^Temperatura.pbas, 72 :: 		Lcd8_out(1, 1, "Duty-Cycle:")                'Mostra mensagem no display
$027C	$3001			MOVLW	1
$027D	$00BC			MOVWF	FARG_Lcd8_Out
$027E	$3001			MOVLW	1
$027F	$00BD			MOVWF	FARG_Lcd8_Out+1
$0280	$3044			MOVLW	68
$0281	$00A3			MOVWF	?Local_Text+0
$0282	$3075			MOVLW	117
$0283	$00A4			MOVWF	?Local_Text+1
$0284	$3074			MOVLW	116
$0285	$00A5			MOVWF	?Local_Text+2
$0286	$3079			MOVLW	121
$0287	$00A6			MOVWF	?Local_Text+3
$0288	$302D			MOVLW	45
$0289	$00A7			MOVWF	?Local_Text+4
$028A	$3043			MOVLW	67
$028B	$00A8			MOVWF	?Local_Text+5
$028C	$3079			MOVLW	121
$028D	$00A9			MOVWF	?Local_Text+6
$028E	$3063			MOVLW	99
$028F	$00AA			MOVWF	?Local_Text+7
$0290	$306C			MOVLW	108
$0291	$00AB			MOVWF	?Local_Text+8
$0292	$3065			MOVLW	101
$0293	$00AC			MOVWF	?Local_Text+9
$0294	$303A			MOVLW	58
$0295	$00AD			MOVWF	?Local_Text+10
$0296	$01AE			CLRF	?Local_Text+11
$0297	$3023			MOVLW	?Local_Text
$0298	$00BE			MOVWF	FARG_Lcd8_Out+2
$0299	$2098			CALL	lcd8bit_lcd8_out
^Temperatura.pbas, 73 :: 		Pwm_Init(1000)                              'Configura o módulo PWM para trabalhar a 1kHz
$029A	$1412			BSF	T2CON, T2CKPS0
$029B	$30F9			MOVLW	249
$029C	$1683			BSF	STATUS, RP0
$029D	$0092			MOVWF	PR2
$029E	$225A			CALL	pwmlib_p_a_pwm_init
^Temperatura.pbas, 74 :: 		Pwm_Start                                   'Inicia o PWM
$029F	$20DA			CALL	pwmlib_p_a_pwm_start
^Temperatura.pbas, 75 :: 		RESISTOR=1                                  'liga o resistor
$02A0	$	Temperatura_L_1:
$02A0	$1487			BSF	PORTC, 1
$02A1	$	Temperatura_L_2:
^Temperatura.pbas, 81 :: 		while 1 = 1
$02A1	$	Temperatura_L_4:
^Temperatura.pbas, 83 :: 		leitura_ad= ADC_read(0) / 4             'faz a leitura do ad
$02A1	$01BC			CLRF	FARG_ADC_read, 1
$02A2	$20E2			CALL	adclib_a_c_adc_read
$02A3	$3002			MOVLW	2
$02A4	$00F4			MOVWF	STACK_4
$02A5	$0874			MOVF	STACK_4, 0
$02A6	$	L_main_0:
$02A6	$1903			BTFSC	STATUS, Z
$02A7	$2AAD			GOTO	L_main_1
$02A8	$0CF1			RRF	STACK_0+1, 1
$02A9	$0CF0			RRF	STACK_0, 1
$02AA	$13F1			BCF	STACK_0+1, 7
$02AB	$3FFF			ADDLW	255
$02AC	$2AA6			GOTO	L_main_0
$02AD	$	L_main_1:
$02AD	$0870			MOVF	STACK_0, 0
$02AE	$00AF			MOVWF	main_global_leitura_ad
$02AF	$0871			MOVF	STACK_0+1, 0
$02B0	$00B0			MOVWF	main_global_leitura_ad+1
^Temperatura.pbas, 84 :: 		Pwm_Change_Duty(leitura_ad)             'Atualiza PWM
$02B1	$0870			MOVF	STACK_0, 0
$02B2	$00BC			MOVWF	FARG_PWM_Change_Duty
$02B3	$2121			CALL	pwmlib_p_a_pwm_change_duty
^Temperatura.pbas, 85 :: 		leitura_ad=(leitura_ad * 100)/255       'Converte para faixa de 0 até 100
$02B4	$082F			MOVF	main_global_leitura_ad, 0
$02B5	$00F0			MOVWF	STACK_0
$02B6	$0830			MOVF	main_global_leitura_ad+1, 0
$02B7	$00F1			MOVWF	STACK_0+1
$02B8	$3064			MOVLW	100
$02B9	$00F4			MOVWF	STACK_4
$02BA	$01F5			CLRF	STACK_4+1
$02BB	$2050			CALL	math_mul_16x16_u
$02BC	$30FF			MOVLW	255
$02BD	$00F4			MOVWF	STACK_4
$02BE	$01F5			CLRF	STACK_4+1
$02BF	$207B			CALL	math_div_16x16_u
$02C0	$0870			MOVF	STACK_0, 0
$02C1	$00AF			MOVWF	main_global_leitura_ad
$02C2	$0871			MOVF	STACK_0+1, 0
$02C3	$00B0			MOVWF	main_global_leitura_ad+1
^Temperatura.pbas, 86 :: 		wordtostr(leitura_ad,string_ad)         'Converte para string
$02C4	$0870			MOVF	STACK_0, 0
$02C5	$00BC			MOVWF	FARG_WordToStr
$02C6	$0871			MOVF	STACK_0+1, 0
$02C7	$00BD			MOVWF	FARG_WordToStr+1
$02C8	$3031			MOVLW	main_global_string_ad
$02C9	$00BE			MOVWF	FARG_WordToStr+2
$02CA	$2169			CALL	conv_wordtostr
^Temperatura.pbas, 87 :: 		strcat(string_ad," % ")                 'concatena a string
$02CB	$3031			MOVLW	main_global_string_ad
$02CC	$00BC			MOVWF	FARG_strcat
$02CD	$3020			MOVLW	32
$02CE	$00A3			MOVWF	?Local_Text+0
$02CF	$3025			MOVLW	37
$02D0	$00A4			MOVWF	?Local_Text+1
$02D1	$3020			MOVLW	32
$02D2	$00A5			MOVWF	?Local_Text+2
$02D3	$01A6			CLRF	?Local_Text+3
$02D4	$3023			MOVLW	?Local_Text
$02D5	$00BD			MOVWF	FARG_strcat+1
$02D6	$21C3			CALL	strcat_strcat
^Temperatura.pbas, 88 :: 		Lcd8_out(1,12,string_ad)                'imprime o dado no lcd
$02D7	$3001			MOVLW	1
$02D8	$00BC			MOVWF	FARG_Lcd8_Out
$02D9	$300C			MOVLW	12
$02DA	$00BD			MOVWF	FARG_Lcd8_Out+1
$02DB	$3031			MOVLW	main_global_string_ad
$02DC	$00BE			MOVWF	FARG_Lcd8_Out+2
$02DD	$2098			CALL	lcd8bit_lcd8_out
^Temperatura.pbas, 90 :: 		leitura_ad= ADC_read(3) / 2             'faz a leitura do ad
$02DE	$3003			MOVLW	3
$02DF	$00BC			MOVWF	FARG_ADC_read
$02E0	$20E2			CALL	adclib_a_c_adc_read
$02E1	$3001			MOVLW	1
$02E2	$00F4			MOVWF	STACK_4
$02E3	$0874			MOVF	STACK_4, 0
$02E4	$	L_main_2:
$02E4	$1903			BTFSC	STATUS, Z
$02E5	$2AEB			GOTO	L_main_3
$02E6	$0CF1			RRF	STACK_0+1, 1
$02E7	$0CF0			RRF	STACK_0, 1
$02E8	$13F1			BCF	STACK_0+1, 7
$02E9	$3FFF			ADDLW	255
$02EA	$2AE4			GOTO	L_main_2
$02EB	$	L_main_3:
$02EB	$0870			MOVF	STACK_0, 0
$02EC	$00AF			MOVWF	main_global_leitura_ad
$02ED	$0871			MOVF	STACK_0+1, 0
$02EE	$00B0			MOVWF	main_global_leitura_ad+1
^Temperatura.pbas, 91 :: 		wordtostr(leitura_ad,string_ad)         'Converte para string
$02EF	$0870			MOVF	STACK_0, 0
$02F0	$00BC			MOVWF	FARG_WordToStr
$02F1	$0871			MOVF	STACK_0+1, 0
$02F2	$00BD			MOVWF	FARG_WordToStr+1
$02F3	$3031			MOVLW	main_global_string_ad
$02F4	$00BE			MOVWF	FARG_WordToStr+2
$02F5	$2169			CALL	conv_wordtostr
^Temperatura.pbas, 92 :: 		strcat(string_ad," C ")                 'concatena a string
$02F6	$3031			MOVLW	main_global_string_ad
$02F7	$00BC			MOVWF	FARG_strcat
$02F8	$3020			MOVLW	32
$02F9	$00A3			MOVWF	?Local_Text+0
$02FA	$3043			MOVLW	67
$02FB	$00A4			MOVWF	?Local_Text+1
$02FC	$3020			MOVLW	32
$02FD	$00A5			MOVWF	?Local_Text+2
$02FE	$01A6			CLRF	?Local_Text+3
$02FF	$3023			MOVLW	?Local_Text
$0300	$00BD			MOVWF	FARG_strcat+1
$0301	$21C3			CALL	strcat_strcat
^Temperatura.pbas, 93 :: 		Lcd8_out(2,1,"Temp: ")                  'imprime o dado no lcd
$0302	$3002			MOVLW	2
$0303	$00BC			MOVWF	FARG_Lcd8_Out
$0304	$3001			MOVLW	1
$0305	$00BD			MOVWF	FARG_Lcd8_Out+1
$0306	$3054			MOVLW	84
$0307	$00A3			MOVWF	?Local_Text+0
$0308	$3065			MOVLW	101
$0309	$00A4			MOVWF	?Local_Text+1
$030A	$306D			MOVLW	109
$030B	$00A5			MOVWF	?Local_Text+2
$030C	$3070			MOVLW	112
$030D	$00A6			MOVWF	?Local_Text+3
$030E	$303A			MOVLW	58
$030F	$00A7			MOVWF	?Local_Text+4
$0310	$3020			MOVLW	32
$0311	$00A8			MOVWF	?Local_Text+5
$0312	$01A9			CLRF	?Local_Text+6
$0313	$3023			MOVLW	?Local_Text
$0314	$00BE			MOVWF	FARG_Lcd8_Out+2
$0315	$2098			CALL	lcd8bit_lcd8_out
^Temperatura.pbas, 94 :: 		lcd8_out(2,7,string_ad)                 'mostra o dado no lcd
$0316	$3002			MOVLW	2
$0317	$00BC			MOVWF	FARG_Lcd8_Out
$0318	$3007			MOVLW	7
$0319	$00BD			MOVWF	FARG_Lcd8_Out+1
$031A	$3031			MOVLW	main_global_string_ad
$031B	$00BE			MOVWF	FARG_Lcd8_Out+2
$031C	$2098			CALL	lcd8bit_lcd8_out
$031D	$2AA1			GOTO	Temperatura_L_4
^Temperatura.pbas, 96 :: 		wend
$031E	$2B1E			GOTO	$
