;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 4/3/2008 13:21:02
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2A3F			GOTO	_main
$0004	$	_delay_1us:
;Delays.ppas,6 :: 		begin
;Delays.ppas,7 :: 		Delay_us(1);
$0004	$0000			NOP
$0005	$	Delays_L_0:
;Delays.ppas,8 :: 		end;
$0005	$0008			RETURN
$0006	$	_delay_5500us:
;Delays.ppas,36 :: 		begin
;Delays.ppas,37 :: 		Delay_us(5500);
$0006	$3008			MOVLW	8
$0007	$1303			BCF	STATUS, RP1
$0008	$1283			BCF	STATUS, RP0
$0009	$00FB			MOVWF	STACK_11
$000A	$30FF			MOVLW	255
$000B	$00FA			MOVWF	STACK_10
$000C	$0BFB			DECFSZ	STACK_11, F
$000D	$280F			GOTO	$+2
$000E	$2812			GOTO	$+4
$000F	$0BFA			DECFSZ	STACK_10, F
$0010	$280F			GOTO	$-1
$0011	$280C			GOTO	$-5
$0012	$301E			MOVLW	30
$0013	$00FA			MOVWF	STACK_10
$0014	$0BFA			DECFSZ	STACK_10, F
$0015	$2814			GOTO	$-1
$0016	$	Delays_L_6:
;Delays.ppas,38 :: 		end;
$0016	$0008			RETURN
$0017	$	_delay_50us:
;Delays.ppas,21 :: 		begin
;Delays.ppas,22 :: 		Delay_us(50);
$0017	$3010			MOVLW	16
$0018	$1303			BCF	STATUS, RP1
$0019	$1283			BCF	STATUS, RP0
$001A	$00FA			MOVWF	STACK_10
$001B	$0BFA			DECFSZ	STACK_10, F
$001C	$281B			GOTO	$-1
$001D	$0000			NOP
$001E	$	Delays_L_3:
;Delays.ppas,23 :: 		end;
$001E	$0008			RETURN
$001F	$	_lcd8_cmd:
;__Lib_Lcd8Custom.ppas,57 :: 		
;__Lib_Lcd8Custom.ppas,58 :: 		
$001F	$1303			BCF	STATUS, RP1
$0020	$1283			BCF	STATUS, RP0
$0021	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0022	$0084			MOVWF	FSR
$0023	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0024	$0084			MOVWF	FSR
$0025	$0180			CLRF	INDF, 1
;__Lib_Lcd8Custom.ppas,59 :: 		
$0026	$3000			MOVLW	0
$0027	$1BD1			BTFSC	FARG_Lcd8_Cmd, 7
$0028	$3001			MOVLW	1
$0029	$00F1			MOVWF	STACK_1
$002A	$0871			MOVF	STACK_1, 0
$002B	$3A00			XORLW	0
$002C	$1903			BTFSC	STATUS, Z
$002D	$283A			GOTO	__Lib_Lcd8Custom_L_2
$002E	$	__Lib_Lcd8Custom_L_1:
;__Lib_Lcd8Custom.ppas,60 :: 		
$002E	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$002F	$0084			MOVWF	FSR
$0030	$0800			MOVF	INDF, 0
$0031	$00F0			MOVWF	STACK_0
$0032	$0822			MOVF	__lib_lcd8custom___lcd8_db7, 0
$0033	$04F0			IORWF	STACK_0, 1
$0034	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0035	$0084			MOVWF	FSR
$0036	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0037	$0084			MOVWF	FSR
$0038	$0870			MOVF	STACK_0, 0
$0039	$0080			MOVWF	INDF
$003A	$	__Lib_Lcd8Custom_L_2:
$003A	$	__Lib_Lcd8Custom_L_3:
;__Lib_Lcd8Custom.ppas,61 :: 		
$003A	$3000			MOVLW	0
$003B	$1B51			BTFSC	FARG_Lcd8_Cmd, 6
$003C	$3001			MOVLW	1
$003D	$00F1			MOVWF	STACK_1
$003E	$0871			MOVF	STACK_1, 0
$003F	$3A00			XORLW	0
$0040	$1903			BTFSC	STATUS, Z
$0041	$284E			GOTO	__Lib_Lcd8Custom_L_5
$0042	$	__Lib_Lcd8Custom_L_4:
;__Lib_Lcd8Custom.ppas,62 :: 		
$0042	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$0043	$0084			MOVWF	FSR
$0044	$0800			MOVF	INDF, 0
$0045	$00F0			MOVWF	STACK_0
$0046	$0823			MOVF	__lib_lcd8custom___lcd8_db6, 0
$0047	$04F0			IORWF	STACK_0, 1
$0048	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0049	$0084			MOVWF	FSR
$004A	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$004B	$0084			MOVWF	FSR
$004C	$0870			MOVF	STACK_0, 0
$004D	$0080			MOVWF	INDF
$004E	$	__Lib_Lcd8Custom_L_5:
$004E	$	__Lib_Lcd8Custom_L_6:
;__Lib_Lcd8Custom.ppas,63 :: 		
$004E	$3000			MOVLW	0
$004F	$1AD1			BTFSC	FARG_Lcd8_Cmd, 5
$0050	$3001			MOVLW	1
$0051	$00F1			MOVWF	STACK_1
$0052	$0871			MOVF	STACK_1, 0
$0053	$3A00			XORLW	0
$0054	$1903			BTFSC	STATUS, Z
$0055	$2862			GOTO	__Lib_Lcd8Custom_L_8
$0056	$	__Lib_Lcd8Custom_L_7:
;__Lib_Lcd8Custom.ppas,64 :: 		
$0056	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$0057	$0084			MOVWF	FSR
$0058	$0800			MOVF	INDF, 0
$0059	$00F0			MOVWF	STACK_0
$005A	$0824			MOVF	__lib_lcd8custom___lcd8_db5, 0
$005B	$04F0			IORWF	STACK_0, 1
$005C	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$005D	$0084			MOVWF	FSR
$005E	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$005F	$0084			MOVWF	FSR
$0060	$0870			MOVF	STACK_0, 0
$0061	$0080			MOVWF	INDF
$0062	$	__Lib_Lcd8Custom_L_8:
$0062	$	__Lib_Lcd8Custom_L_9:
;__Lib_Lcd8Custom.ppas,65 :: 		
$0062	$3000			MOVLW	0
$0063	$1A51			BTFSC	FARG_Lcd8_Cmd, 4
$0064	$3001			MOVLW	1
$0065	$00F1			MOVWF	STACK_1
$0066	$0871			MOVF	STACK_1, 0
$0067	$3A00			XORLW	0
$0068	$1903			BTFSC	STATUS, Z
$0069	$2876			GOTO	__Lib_Lcd8Custom_L_11
$006A	$	__Lib_Lcd8Custom_L_10:
;__Lib_Lcd8Custom.ppas,66 :: 		
$006A	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$006B	$0084			MOVWF	FSR
$006C	$0800			MOVF	INDF, 0
$006D	$00F0			MOVWF	STACK_0
$006E	$0825			MOVF	__lib_lcd8custom___lcd8_db4, 0
$006F	$04F0			IORWF	STACK_0, 1
$0070	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0071	$0084			MOVWF	FSR
$0072	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0073	$0084			MOVWF	FSR
$0074	$0870			MOVF	STACK_0, 0
$0075	$0080			MOVWF	INDF
$0076	$	__Lib_Lcd8Custom_L_11:
$0076	$	__Lib_Lcd8Custom_L_12:
;__Lib_Lcd8Custom.ppas,67 :: 		
$0076	$3000			MOVLW	0
$0077	$19D1			BTFSC	FARG_Lcd8_Cmd, 3
$0078	$3001			MOVLW	1
$0079	$00F1			MOVWF	STACK_1
$007A	$0871			MOVF	STACK_1, 0
$007B	$3A00			XORLW	0
$007C	$1903			BTFSC	STATUS, Z
$007D	$288A			GOTO	__Lib_Lcd8Custom_L_14
$007E	$	__Lib_Lcd8Custom_L_13:
;__Lib_Lcd8Custom.ppas,68 :: 		
$007E	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$007F	$0084			MOVWF	FSR
$0080	$0800			MOVF	INDF, 0
$0081	$00F0			MOVWF	STACK_0
$0082	$0826			MOVF	__lib_lcd8custom___lcd8_db3, 0
$0083	$04F0			IORWF	STACK_0, 1
$0084	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0085	$0084			MOVWF	FSR
$0086	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0087	$0084			MOVWF	FSR
$0088	$0870			MOVF	STACK_0, 0
$0089	$0080			MOVWF	INDF
$008A	$	__Lib_Lcd8Custom_L_14:
$008A	$	__Lib_Lcd8Custom_L_15:
;__Lib_Lcd8Custom.ppas,69 :: 		
$008A	$3000			MOVLW	0
$008B	$1951			BTFSC	FARG_Lcd8_Cmd, 2
$008C	$3001			MOVLW	1
$008D	$00F1			MOVWF	STACK_1
$008E	$0871			MOVF	STACK_1, 0
$008F	$3A00			XORLW	0
$0090	$1903			BTFSC	STATUS, Z
$0091	$289E			GOTO	__Lib_Lcd8Custom_L_17
$0092	$	__Lib_Lcd8Custom_L_16:
;__Lib_Lcd8Custom.ppas,70 :: 		
$0092	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$0093	$0084			MOVWF	FSR
$0094	$0800			MOVF	INDF, 0
$0095	$00F0			MOVWF	STACK_0
$0096	$0827			MOVF	__lib_lcd8custom___lcd8_db2, 0
$0097	$04F0			IORWF	STACK_0, 1
$0098	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$0099	$0084			MOVWF	FSR
$009A	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$009B	$0084			MOVWF	FSR
$009C	$0870			MOVF	STACK_0, 0
$009D	$0080			MOVWF	INDF
$009E	$	__Lib_Lcd8Custom_L_17:
$009E	$	__Lib_Lcd8Custom_L_18:
;__Lib_Lcd8Custom.ppas,71 :: 		
$009E	$3000			MOVLW	0
$009F	$18D1			BTFSC	FARG_Lcd8_Cmd, 1
$00A0	$3001			MOVLW	1
$00A1	$00F1			MOVWF	STACK_1
$00A2	$0871			MOVF	STACK_1, 0
$00A3	$3A00			XORLW	0
$00A4	$1903			BTFSC	STATUS, Z
$00A5	$28B2			GOTO	__Lib_Lcd8Custom_L_20
$00A6	$	__Lib_Lcd8Custom_L_19:
;__Lib_Lcd8Custom.ppas,72 :: 		
$00A6	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$00A7	$0084			MOVWF	FSR
$00A8	$0800			MOVF	INDF, 0
$00A9	$00F0			MOVWF	STACK_0
$00AA	$0828			MOVF	__lib_lcd8custom___lcd8_db1, 0
$00AB	$04F0			IORWF	STACK_0, 1
$00AC	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$00AD	$0084			MOVWF	FSR
$00AE	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$00AF	$0084			MOVWF	FSR
$00B0	$0870			MOVF	STACK_0, 0
$00B1	$0080			MOVWF	INDF
$00B2	$	__Lib_Lcd8Custom_L_20:
$00B2	$	__Lib_Lcd8Custom_L_21:
;__Lib_Lcd8Custom.ppas,73 :: 		
$00B2	$3001			MOVLW	1
$00B3	$0551			ANDWF	FARG_Lcd8_Cmd, 0
$00B4	$00F1			MOVWF	STACK_1
$00B5	$0871			MOVF	STACK_1, 0
$00B6	$3A00			XORLW	0
$00B7	$1903			BTFSC	STATUS, Z
$00B8	$28C5			GOTO	__Lib_Lcd8Custom_L_23
$00B9	$	__Lib_Lcd8Custom_L_22:
;__Lib_Lcd8Custom.ppas,74 :: 		
$00B9	$0821			MOVF	__lib_lcd8custom__port_dataaddress, 0
$00BA	$0084			MOVWF	FSR
$00BB	$0800			MOVF	INDF, 0
$00BC	$00F0			MOVWF	STACK_0
$00BD	$0829			MOVF	__lib_lcd8custom___lcd8_db0, 0
$00BE	$04F0			IORWF	STACK_0, 1
$00BF	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$00C0	$0084			MOVWF	FSR
$00C1	$0820			MOVF	__lib_lcd8custom__lat_dataaddress, 0
$00C2	$0084			MOVWF	FSR
$00C3	$0870			MOVF	STACK_0, 0
$00C4	$0080			MOVWF	INDF
$00C5	$	__Lib_Lcd8Custom_L_23:
$00C5	$	__Lib_Lcd8Custom_L_24:
;__Lib_Lcd8Custom.ppas,76 :: 		
$00C5	$082A			MOVF	__lib_lcd8custom__cmd, 0
$00C6	$3A01			XORLW	1
$00C7	$1D03			BTFSS	STATUS, Z
$00C8	$28D8			GOTO	__Lib_Lcd8Custom_L_26
$00C9	$	__Lib_Lcd8Custom_L_25:
;__Lib_Lcd8Custom.ppas,77 :: 		
$00C9	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00CA	$0084			MOVWF	FSR
$00CB	$0800			MOVF	INDF, 0
$00CC	$00F1			MOVWF	STACK_1
$00CD	$092C			COMF	__lib_lcd8custom___lcd8_rs, W
$00CE	$00F0			MOVWF	STACK_0
$00CF	$0871			MOVF	STACK_1, 0
$00D0	$05F0			ANDWF	STACK_0, 1
$00D1	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00D2	$0084			MOVWF	FSR
$00D3	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00D4	$0084			MOVWF	FSR
$00D5	$0870			MOVF	STACK_0, 0
$00D6	$0080			MOVWF	INDF
$00D7	$28E4			GOTO	__Lib_Lcd8Custom_L_27
;__Lib_Lcd8Custom.ppas,78 :: 		
$00D8	$	__Lib_Lcd8Custom_L_26:
;__Lib_Lcd8Custom.ppas,79 :: 		
$00D8	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00D9	$0084			MOVWF	FSR
$00DA	$0800			MOVF	INDF, 0
$00DB	$00F0			MOVWF	STACK_0
$00DC	$082C			MOVF	__lib_lcd8custom___lcd8_rs, 0
$00DD	$04F0			IORWF	STACK_0, 1
$00DE	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00DF	$0084			MOVWF	FSR
$00E0	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00E1	$0084			MOVWF	FSR
$00E2	$0870			MOVF	STACK_0, 0
$00E3	$0080			MOVWF	INDF
$00E4	$	__Lib_Lcd8Custom_L_27:
;__Lib_Lcd8Custom.ppas,81 :: 		
$00E4	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00E5	$0084			MOVWF	FSR
$00E6	$0800			MOVF	INDF, 0
$00E7	$00F0			MOVWF	STACK_0
$00E8	$082D			MOVF	__lib_lcd8custom___lcd8_enable, 0
$00E9	$04F0			IORWF	STACK_0, 1
$00EA	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00EB	$0084			MOVWF	FSR
$00EC	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00ED	$0084			MOVWF	FSR
$00EE	$0870			MOVF	STACK_0, 0
$00EF	$0080			MOVWF	INDF
;__Lib_Lcd8Custom.ppas,82 :: 		
$00F0	$2004			CALL	_delay_1us
;__Lib_Lcd8Custom.ppas,83 :: 		
$00F1	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00F2	$0084			MOVWF	FSR
$00F3	$0800			MOVF	INDF, 0
$00F4	$00F1			MOVWF	STACK_1
$00F5	$092D			COMF	__lib_lcd8custom___lcd8_enable, W
$00F6	$00F0			MOVWF	STACK_0
$00F7	$0871			MOVF	STACK_1, 0
$00F8	$05F0			ANDWF	STACK_0, 1
$00F9	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00FA	$0084			MOVWF	FSR
$00FB	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$00FC	$0084			MOVWF	FSR
$00FD	$0870			MOVF	STACK_0, 0
$00FE	$0080			MOVWF	INDF
;__Lib_Lcd8Custom.ppas,84 :: 		
$00FF	$2004			CALL	_delay_1us
;__Lib_Lcd8Custom.ppas,86 :: 		
$0100	$082A			MOVF	__lib_lcd8custom__cmd, 0
$0101	$3A01			XORLW	1
$0102	$1D03			BTFSS	STATUS, Z
$0103	$2906			GOTO	__Lib_Lcd8Custom_L_29
$0104	$	__Lib_Lcd8Custom_L_28:
;__Lib_Lcd8Custom.ppas,87 :: 		
$0104	$2006			CALL	_delay_5500us
$0105	$2907			GOTO	__Lib_Lcd8Custom_L_30
;__Lib_Lcd8Custom.ppas,88 :: 		
$0106	$	__Lib_Lcd8Custom_L_29:
;__Lib_Lcd8Custom.ppas,89 :: 		
$0106	$2017			CALL	_delay_50us
$0107	$	__Lib_Lcd8Custom_L_30:
$0107	$	__Lib_Lcd8Custom_L_0:
;__Lib_Lcd8Custom.ppas,90 :: 		
$0107	$0008			RETURN
$0108	$	_lcd8_config:
;__Lib_Lcd8Custom.ppas,126 :: 		
;__Lib_Lcd8Custom.ppas,127 :: 		
$0108	$2006			CALL	_delay_5500us
;__Lib_Lcd8Custom.ppas,128 :: 		
$0109	$2006			CALL	_delay_5500us
;__Lib_Lcd8Custom.ppas,129 :: 		
$010A	$2006			CALL	_delay_5500us
;__Lib_Lcd8Custom.ppas,131 :: 		
$010B	$0849			MOVF	FARG_Lcd8_Config+5, 0
$010C	$00F0			MOVWF	STACK_0
$010D	$3001			MOVLW	1
$010E	$00A2			MOVWF	__lib_lcd8custom___lcd8_db7
$010F	$0870			MOVF	STACK_0, 0
$0110	$	L_Lcd8_Config_0:
$0110	$1903			BTFSC	STATUS, Z
$0111	$2916			GOTO	L_Lcd8_Config_1
$0112	$0DA2			RLF	__lib_lcd8custom___lcd8_db7, 1
$0113	$1022			BCF	__lib_lcd8custom___lcd8_db7, 0
$0114	$3FFF			ADDLW	255
$0115	$2910			GOTO	L_Lcd8_Config_0
$0116	$	L_Lcd8_Config_1:
;__Lib_Lcd8Custom.ppas,132 :: 		
$0116	$084A			MOVF	FARG_Lcd8_Config+6, 0
$0117	$00F0			MOVWF	STACK_0
$0118	$3001			MOVLW	1
$0119	$00A3			MOVWF	__lib_lcd8custom___lcd8_db6
$011A	$0870			MOVF	STACK_0, 0
$011B	$	L_Lcd8_Config_2:
$011B	$1903			BTFSC	STATUS, Z
$011C	$2921			GOTO	L_Lcd8_Config_3
$011D	$0DA3			RLF	__lib_lcd8custom___lcd8_db6, 1
$011E	$1023			BCF	__lib_lcd8custom___lcd8_db6, 0
$011F	$3FFF			ADDLW	255
$0120	$291B			GOTO	L_Lcd8_Config_2
$0121	$	L_Lcd8_Config_3:
;__Lib_Lcd8Custom.ppas,133 :: 		
$0121	$084B			MOVF	FARG_Lcd8_Config+7, 0
$0122	$00F0			MOVWF	STACK_0
$0123	$3001			MOVLW	1
$0124	$00A4			MOVWF	__lib_lcd8custom___lcd8_db5
$0125	$0870			MOVF	STACK_0, 0
$0126	$	L_Lcd8_Config_4:
$0126	$1903			BTFSC	STATUS, Z
$0127	$292C			GOTO	L_Lcd8_Config_5
$0128	$0DA4			RLF	__lib_lcd8custom___lcd8_db5, 1
$0129	$1024			BCF	__lib_lcd8custom___lcd8_db5, 0
$012A	$3FFF			ADDLW	255
$012B	$2926			GOTO	L_Lcd8_Config_4
$012C	$	L_Lcd8_Config_5:
;__Lib_Lcd8Custom.ppas,134 :: 		
$012C	$084C			MOVF	FARG_Lcd8_Config+8, 0
$012D	$00F0			MOVWF	STACK_0
$012E	$3001			MOVLW	1
$012F	$00A5			MOVWF	__lib_lcd8custom___lcd8_db4
$0130	$0870			MOVF	STACK_0, 0
$0131	$	L_Lcd8_Config_6:
$0131	$1903			BTFSC	STATUS, Z
$0132	$2937			GOTO	L_Lcd8_Config_7
$0133	$0DA5			RLF	__lib_lcd8custom___lcd8_db4, 1
$0134	$1025			BCF	__lib_lcd8custom___lcd8_db4, 0
$0135	$3FFF			ADDLW	255
$0136	$2931			GOTO	L_Lcd8_Config_6
$0137	$	L_Lcd8_Config_7:
;__Lib_Lcd8Custom.ppas,135 :: 		
$0137	$084D			MOVF	FARG_Lcd8_Config+9, 0
$0138	$00F0			MOVWF	STACK_0
$0139	$3001			MOVLW	1
$013A	$00A6			MOVWF	__lib_lcd8custom___lcd8_db3
$013B	$0870			MOVF	STACK_0, 0
$013C	$	L_Lcd8_Config_8:
$013C	$1903			BTFSC	STATUS, Z
$013D	$2942			GOTO	L_Lcd8_Config_9
$013E	$0DA6			RLF	__lib_lcd8custom___lcd8_db3, 1
$013F	$1026			BCF	__lib_lcd8custom___lcd8_db3, 0
$0140	$3FFF			ADDLW	255
$0141	$293C			GOTO	L_Lcd8_Config_8
$0142	$	L_Lcd8_Config_9:
;__Lib_Lcd8Custom.ppas,136 :: 		
$0142	$084E			MOVF	FARG_Lcd8_Config+10, 0
$0143	$00F0			MOVWF	STACK_0
$0144	$3001			MOVLW	1
$0145	$00A7			MOVWF	__lib_lcd8custom___lcd8_db2
$0146	$0870			MOVF	STACK_0, 0
$0147	$	L_Lcd8_Config_10:
$0147	$1903			BTFSC	STATUS, Z
$0148	$294D			GOTO	L_Lcd8_Config_11
$0149	$0DA7			RLF	__lib_lcd8custom___lcd8_db2, 1
$014A	$1027			BCF	__lib_lcd8custom___lcd8_db2, 0
$014B	$3FFF			ADDLW	255
$014C	$2947			GOTO	L_Lcd8_Config_10
$014D	$	L_Lcd8_Config_11:
;__Lib_Lcd8Custom.ppas,137 :: 		
$014D	$084F			MOVF	FARG_Lcd8_Config+11, 0
$014E	$00F0			MOVWF	STACK_0
$014F	$3001			MOVLW	1
$0150	$00A8			MOVWF	__lib_lcd8custom___lcd8_db1
$0151	$0870			MOVF	STACK_0, 0
$0152	$	L_Lcd8_Config_12:
$0152	$1903			BTFSC	STATUS, Z
$0153	$2958			GOTO	L_Lcd8_Config_13
$0154	$0DA8			RLF	__lib_lcd8custom___lcd8_db1, 1
$0155	$1028			BCF	__lib_lcd8custom___lcd8_db1, 0
$0156	$3FFF			ADDLW	255
$0157	$2952			GOTO	L_Lcd8_Config_12
$0158	$	L_Lcd8_Config_13:
;__Lib_Lcd8Custom.ppas,138 :: 		
$0158	$0850			MOVF	FARG_Lcd8_Config+12, 0
$0159	$00F0			MOVWF	STACK_0
$015A	$3001			MOVLW	1
$015B	$00A9			MOVWF	__lib_lcd8custom___lcd8_db0
$015C	$0870			MOVF	STACK_0, 0
$015D	$	L_Lcd8_Config_14:
$015D	$1903			BTFSC	STATUS, Z
$015E	$2963			GOTO	L_Lcd8_Config_15
$015F	$0DA9			RLF	__lib_lcd8custom___lcd8_db0, 1
$0160	$1029			BCF	__lib_lcd8custom___lcd8_db0, 0
$0161	$3FFF			ADDLW	255
$0162	$295D			GOTO	L_Lcd8_Config_14
$0163	$	L_Lcd8_Config_15:
;__Lib_Lcd8Custom.ppas,139 :: 		
$0163	$0846			MOVF	FARG_Lcd8_Config+2, 0
$0164	$00F0			MOVWF	STACK_0
$0165	$3001			MOVLW	1
$0166	$00AC			MOVWF	__lib_lcd8custom___lcd8_rs
$0167	$0870			MOVF	STACK_0, 0
$0168	$	L_Lcd8_Config_16:
$0168	$1903			BTFSC	STATUS, Z
$0169	$296E			GOTO	L_Lcd8_Config_17
$016A	$0DAC			RLF	__lib_lcd8custom___lcd8_rs, 1
$016B	$102C			BCF	__lib_lcd8custom___lcd8_rs, 0
$016C	$3FFF			ADDLW	255
$016D	$2968			GOTO	L_Lcd8_Config_16
$016E	$	L_Lcd8_Config_17:
;__Lib_Lcd8Custom.ppas,140 :: 		
$016E	$0847			MOVF	FARG_Lcd8_Config+3, 0
$016F	$00F0			MOVWF	STACK_0
$0170	$3001			MOVLW	1
$0171	$00AE			MOVWF	__lib_lcd8custom___lcd8_rw
$0172	$0870			MOVF	STACK_0, 0
$0173	$	L_Lcd8_Config_18:
$0173	$1903			BTFSC	STATUS, Z
$0174	$2979			GOTO	L_Lcd8_Config_19
$0175	$0DAE			RLF	__lib_lcd8custom___lcd8_rw, 1
$0176	$102E			BCF	__lib_lcd8custom___lcd8_rw, 0
$0177	$3FFF			ADDLW	255
$0178	$2973			GOTO	L_Lcd8_Config_18
$0179	$	L_Lcd8_Config_19:
;__Lib_Lcd8Custom.ppas,141 :: 		
$0179	$0848			MOVF	FARG_Lcd8_Config+4, 0
$017A	$00F0			MOVWF	STACK_0
$017B	$3001			MOVLW	1
$017C	$00AD			MOVWF	__lib_lcd8custom___lcd8_enable
$017D	$0870			MOVF	STACK_0, 0
$017E	$	L_Lcd8_Config_20:
$017E	$1903			BTFSC	STATUS, Z
$017F	$2984			GOTO	L_Lcd8_Config_21
$0180	$0DAD			RLF	__lib_lcd8custom___lcd8_enable, 1
$0181	$102D			BCF	__lib_lcd8custom___lcd8_enable, 0
$0182	$3FFF			ADDLW	255
$0183	$297E			GOTO	L_Lcd8_Config_20
$0184	$	L_Lcd8_Config_21:
;__Lib_Lcd8Custom.ppas,143 :: 		
$0184	$0845			MOVF	FARG_Lcd8_Config+1, 0
$0185	$00A0			MOVWF	__lib_lcd8custom__lat_dataaddress
;__Lib_Lcd8Custom.ppas,144 :: 		
$0186	$0845			MOVF	FARG_Lcd8_Config+1, 0
$0187	$00A1			MOVWF	__lib_lcd8custom__port_dataaddress
;__Lib_Lcd8Custom.ppas,145 :: 		
$0188	$0844			MOVF	FARG_Lcd8_Config, 0
$0189	$00AB			MOVWF	__lib_lcd8custom__ctrladdress
;__Lib_Lcd8Custom.ppas,147 :: 		
$018A	$0845			MOVF	FARG_Lcd8_Config+1, 0
$018B	$0084			MOVWF	FSR
$018C	$0845			MOVF	FARG_Lcd8_Config+1, 0
$018D	$0084			MOVWF	FSR
$018E	$0180			CLRF	INDF, 1
;__Lib_Lcd8Custom.ppas,148 :: 		
$018F	$3080			MOVLW	128
$0190	$0445			IORWF	FARG_Lcd8_Config+1, 0
$0191	$00F0			MOVWF	STACK_0
$0192	$0870			MOVF	STACK_0, 0
$0193	$00A0			MOVWF	__lib_lcd8custom__lat_dataaddress
;__Lib_Lcd8Custom.ppas,149 :: 		
$0194	$0870			MOVF	STACK_0, 0
$0195	$0084			MOVWF	FSR
$0196	$0870			MOVF	STACK_0, 0
$0197	$0084			MOVWF	FSR
$0198	$0180			CLRF	INDF, 1
;__Lib_Lcd8Custom.ppas,150 :: 		
$0199	$0845			MOVF	FARG_Lcd8_Config+1, 0
$019A	$00A0			MOVWF	__lib_lcd8custom__lat_dataaddress
;__Lib_Lcd8Custom.ppas,152 :: 		
$019B	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$019C	$0084			MOVWF	FSR
$019D	$0800			MOVF	INDF, 0
$019E	$00F1			MOVWF	STACK_1
$019F	$082D			MOVF	__lib_lcd8custom___lcd8_enable, 0
$01A0	$042C			IORWF	__lib_lcd8custom___lcd8_rs, 0
$01A1	$00F0			MOVWF	STACK_0
$01A2	$082E			MOVF	__lib_lcd8custom___lcd8_rw, 0
$01A3	$04F0			IORWF	STACK_0, 1
$01A4	$09F0			COMF	STACK_0, F
$01A5	$0871			MOVF	STACK_1, 0
$01A6	$05F0			ANDWF	STACK_0, 1
$01A7	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$01A8	$0084			MOVWF	FSR
$01A9	$082B			MOVF	__lib_lcd8custom__ctrladdress, 0
$01AA	$0084			MOVWF	FSR
$01AB	$0870			MOVF	STACK_0, 0
$01AC	$0080			MOVWF	INDF
;__Lib_Lcd8Custom.ppas,153 :: 		
$01AD	$3080			MOVLW	128
$01AE	$042B			IORWF	__lib_lcd8custom__ctrladdress, 0
$01AF	$00F2			MOVWF	STACK_2
$01B0	$0872			MOVF	STACK_2, 0
$01B1	$00AB			MOVWF	__lib_lcd8custom__ctrladdress
;__Lib_Lcd8Custom.ppas,154 :: 		
$01B2	$0872			MOVF	STACK_2, 0
$01B3	$0084			MOVWF	FSR
$01B4	$0800			MOVF	INDF, 0
$01B5	$00F1			MOVWF	STACK_1
$01B6	$082D			MOVF	__lib_lcd8custom___lcd8_enable, 0
$01B7	$042C			IORWF	__lib_lcd8custom___lcd8_rs, 0
$01B8	$00F0			MOVWF	STACK_0
$01B9	$082E			MOVF	__lib_lcd8custom___lcd8_rw, 0
$01BA	$04F0			IORWF	STACK_0, 1
$01BB	$09F0			COMF	STACK_0, F
$01BC	$0871			MOVF	STACK_1, 0
$01BD	$05F0			ANDWF	STACK_0, 1
$01BE	$0872			MOVF	STACK_2, 0
$01BF	$0084			MOVWF	FSR
$01C0	$0872			MOVF	STACK_2, 0
$01C1	$0084			MOVWF	FSR
$01C2	$0870			MOVF	STACK_0, 0
$01C3	$0080			MOVWF	INDF
;__Lib_Lcd8Custom.ppas,155 :: 		
$01C4	$3080			MOVLW	128
$01C5	$06AB			XORWF	__lib_lcd8custom__ctrladdress, 1
;__Lib_Lcd8Custom.ppas,157 :: 		
$01C6	$3030			MOVLW	48
$01C7	$00D1			MOVWF	FARG_Lcd8_Cmd
$01C8	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,158 :: 		
$01C9	$3030			MOVLW	48
$01CA	$00D1			MOVWF	FARG_Lcd8_Cmd
$01CB	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,159 :: 		
$01CC	$3030			MOVLW	48
$01CD	$00D1			MOVWF	FARG_Lcd8_Cmd
$01CE	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,160 :: 		
$01CF	$3038			MOVLW	56
$01D0	$00D1			MOVWF	FARG_Lcd8_Cmd
$01D1	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,161 :: 		
$01D2	$3008			MOVLW	8
$01D3	$00D1			MOVWF	FARG_Lcd8_Cmd
$01D4	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,162 :: 		
$01D5	$3001			MOVLW	1
$01D6	$00D1			MOVWF	FARG_Lcd8_Cmd
$01D7	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,163 :: 		
$01D8	$3006			MOVLW	6
$01D9	$00D1			MOVWF	FARG_Lcd8_Cmd
$01DA	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,164 :: 		
$01DB	$300C			MOVLW	12
$01DC	$00D1			MOVWF	FARG_Lcd8_Cmd
$01DD	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,165 :: 		
$01DE	$3001			MOVLW	1
$01DF	$00AA			MOVWF	__lib_lcd8custom__cmd
$01E0	$	__Lib_Lcd8Custom_L_46:
;__Lib_Lcd8Custom.ppas,166 :: 		
$01E0	$0008			RETURN
$01E1	$	_lcd8_init:
;__Lib_Lcd8Custom.ppas,169 :: 		
;__Lib_Lcd8Custom.ppas,170 :: 		
$01E1	$1303			BCF	STATUS, RP1
$01E2	$1283			BCF	STATUS, RP0
$01E3	$0840			MOVF	FARG_Lcd8_Init, 0
$01E4	$00C4			MOVWF	FARG_Lcd8_Config
$01E5	$0841			MOVF	FARG_Lcd8_Init+1, 0
$01E6	$00C5			MOVWF	FARG_Lcd8_Config+1
$01E7	$3004			MOVLW	4
$01E8	$00C6			MOVWF	FARG_Lcd8_Config+2
$01E9	$3005			MOVLW	5
$01EA	$00C7			MOVWF	FARG_Lcd8_Config+3
$01EB	$3006			MOVLW	6
$01EC	$00C8			MOVWF	FARG_Lcd8_Config+4
$01ED	$3007			MOVLW	7
$01EE	$00C9			MOVWF	FARG_Lcd8_Config+5
$01EF	$3006			MOVLW	6
$01F0	$00CA			MOVWF	FARG_Lcd8_Config+6
$01F1	$3005			MOVLW	5
$01F2	$00CB			MOVWF	FARG_Lcd8_Config+7
$01F3	$3004			MOVLW	4
$01F4	$00CC			MOVWF	FARG_Lcd8_Config+8
$01F5	$3003			MOVLW	3
$01F6	$00CD			MOVWF	FARG_Lcd8_Config+9
$01F7	$3002			MOVLW	2
$01F8	$00CE			MOVWF	FARG_Lcd8_Config+10
$01F9	$3001			MOVLW	1
$01FA	$00CF			MOVWF	FARG_Lcd8_Config+11
$01FB	$01D0			CLRF	FARG_Lcd8_Config+12, 1
$01FC	$2108			CALL	_lcd8_config
$01FD	$	__Lib_Lcd8Custom_L_47:
;__Lib_Lcd8Custom.ppas,171 :: 		
$01FD	$0008			RETURN
$01FE	$	_lcd8_out:
;__Lib_Lcd8Custom.ppas,175 :: 		
;__Lib_Lcd8Custom.ppas,177 :: 		
$01FE	$	__Lib_Lcd8Custom_L_51:
$01FE	$1303			BCF	STATUS, RP1
$01FF	$1283			BCF	STATUS, RP0
$0200	$0840			MOVF	FARG_Lcd8_Out, 0
$0201	$3A01			XORLW	1
$0202	$1D03			BTFSS	STATUS, Z
$0203	$2A07			GOTO	__Lib_Lcd8Custom_L_52
$0204	$	__Lib_Lcd8Custom_L_50:
$0204	$3080			MOVLW	128
$0205	$00C0			MOVWF	FARG_Lcd8_Out
$0206	$2A1E			GOTO	__Lib_Lcd8Custom_L_49
$0207	$	__Lib_Lcd8Custom_L_52:
;__Lib_Lcd8Custom.ppas,178 :: 		
$0207	$	__Lib_Lcd8Custom_L_54:
$0207	$0840			MOVF	FARG_Lcd8_Out, 0
$0208	$3A02			XORLW	2
$0209	$1D03			BTFSS	STATUS, Z
$020A	$2A0E			GOTO	__Lib_Lcd8Custom_L_55
$020B	$	__Lib_Lcd8Custom_L_53:
$020B	$30C0			MOVLW	192
$020C	$00C0			MOVWF	FARG_Lcd8_Out
$020D	$2A1E			GOTO	__Lib_Lcd8Custom_L_49
$020E	$	__Lib_Lcd8Custom_L_55:
;__Lib_Lcd8Custom.ppas,179 :: 		
$020E	$	__Lib_Lcd8Custom_L_57:
$020E	$0840			MOVF	FARG_Lcd8_Out, 0
$020F	$3A03			XORLW	3
$0210	$1D03			BTFSS	STATUS, Z
$0211	$2A15			GOTO	__Lib_Lcd8Custom_L_58
$0212	$	__Lib_Lcd8Custom_L_56:
$0212	$3094			MOVLW	148
$0213	$00C0			MOVWF	FARG_Lcd8_Out
$0214	$2A1E			GOTO	__Lib_Lcd8Custom_L_49
$0215	$	__Lib_Lcd8Custom_L_58:
;__Lib_Lcd8Custom.ppas,180 :: 		
$0215	$	__Lib_Lcd8Custom_L_60:
$0215	$0840			MOVF	FARG_Lcd8_Out, 0
$0216	$3A04			XORLW	4
$0217	$1D03			BTFSS	STATUS, Z
$0218	$2A1C			GOTO	__Lib_Lcd8Custom_L_61
$0219	$	__Lib_Lcd8Custom_L_59:
$0219	$30D4			MOVLW	212
$021A	$00C0			MOVWF	FARG_Lcd8_Out
;__Lib_Lcd8Custom.ppas,181 :: 		
$021B	$2A1E			GOTO	__Lib_Lcd8Custom_L_49
$021C	$	__Lib_Lcd8Custom_L_61:
;__Lib_Lcd8Custom.ppas,182 :: 		
$021C	$3080			MOVLW	128
$021D	$00C0			MOVWF	FARG_Lcd8_Out
$021E	$	__Lib_Lcd8Custom_L_49:
;__Lib_Lcd8Custom.ppas,185 :: 		
$021E	$0841			MOVF	FARG_Lcd8_Out+1, 0
$021F	$0740			ADDWF	FARG_Lcd8_Out, 0
$0220	$00F0			MOVWF	STACK_0
$0221	$03F0			DECF	STACK_0, 1
$0222	$0870			MOVF	STACK_0, 0
$0223	$00C0			MOVWF	FARG_Lcd8_Out
;__Lib_Lcd8Custom.ppas,186 :: 		
$0224	$3001			MOVLW	1
$0225	$00AA			MOVWF	__lib_lcd8custom__cmd
;__Lib_Lcd8Custom.ppas,187 :: 		
$0226	$0870			MOVF	STACK_0, 0
$0227	$00D1			MOVWF	FARG_Lcd8_Cmd
$0228	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,189 :: 		
$0229	$01AA			CLRF	__lib_lcd8custom__cmd, 1
;__Lib_Lcd8Custom.ppas,190 :: 		
$022A	$01C3			CLRF	_lcd8_out_local_i, 1
;__Lib_Lcd8Custom.ppas,191 :: 		
$022B	$	__Lib_Lcd8Custom_L_63:
$022B	$0843			MOVF	_lcd8_out_local_i, 0
$022C	$0742			ADDWF	FARG_Lcd8_Out+2, 0
$022D	$0084			MOVWF	FSR
$022E	$0800			MOVF	INDF, 0
$022F	$00F2			MOVWF	STACK_2
$0230	$0872			MOVF	STACK_2, 0
$0231	$3A00			XORLW	0
$0232	$1903			BTFSC	STATUS, Z
$0233	$2A3C			GOTO	__Lib_Lcd8Custom_L_64
;__Lib_Lcd8Custom.ppas,193 :: 		
$0234	$0843			MOVF	_lcd8_out_local_i, 0
$0235	$0742			ADDWF	FARG_Lcd8_Out+2, 0
$0236	$0084			MOVWF	FSR
$0237	$0800			MOVF	INDF, 0
$0238	$00D1			MOVWF	FARG_Lcd8_Cmd
$0239	$201F			CALL	_lcd8_cmd
;__Lib_Lcd8Custom.ppas,194 :: 		
$023A	$0AC3			INCF	_lcd8_out_local_i, 1
;__Lib_Lcd8Custom.ppas,195 :: 		
$023B	$2A2B			GOTO	__Lib_Lcd8Custom_L_63
$023C	$	__Lib_Lcd8Custom_L_64:
;__Lib_Lcd8Custom.ppas,196 :: 		
$023C	$3001			MOVLW	1
$023D	$00AA			MOVWF	__lib_lcd8custom__cmd
$023E	$	__Lib_Lcd8Custom_L_48:
;__Lib_Lcd8Custom.ppas,197 :: 		
$023E	$0008			RETURN
$023F	$	_main:
;DisplayLCD.ppas,3 :: 		begin
;DisplayLCD.ppas,5 :: 		trisd:=0;                        //Configura o PORTD como saída
$023F	$1303			BCF	STATUS, RP1
$0240	$1683			BSF	STATUS, RP0
$0241	$0188			CLRF	TRISD, 1
;DisplayLCD.ppas,6 :: 		trise:=0;                        //Configura o PORTE como saída
$0242	$0189			CLRF	TRISE, 1
;DisplayLCD.ppas,7 :: 		trisb:=0;                        //Configura o PORTB como saída
$0243	$0186			CLRF	TRISB, 1
;DisplayLCD.ppas,8 :: 		adcon1:=7;                       //Configura o ad como pinos digitais
$0244	$3007			MOVLW	7
$0245	$009F			MOVWF	ADCON1
;DisplayLCD.ppas,10 :: 		delay_ms(1000);
$0246	$3006			MOVLW	6
$0247	$00FC			MOVWF	STACK_12
$0248	$30FF			MOVLW	255
$0249	$00FB			MOVWF	STACK_11
$024A	$30FF			MOVLW	255
$024B	$00FA			MOVWF	STACK_10
$024C	$0BFC			DECFSZ	STACK_12, F
$024D	$2A4F			GOTO	$+2
$024E	$2A56			GOTO	$+8
$024F	$0BFB			DECFSZ	STACK_11, F
$0250	$2A52			GOTO	$+2
$0251	$2A55			GOTO	$+4
$0252	$0BFA			DECFSZ	STACK_10, F
$0253	$2A52			GOTO	$-1
$0254	$2A4F			GOTO	$-5
$0255	$2A4C			GOTO	$-9
$0256	$301A			MOVLW	26
$0257	$00FB			MOVWF	STACK_11
$0258	$30FF			MOVLW	255
$0259	$00FA			MOVWF	STACK_10
$025A	$0BFB			DECFSZ	STACK_11, F
$025B	$2A5D			GOTO	$+2
$025C	$2A60			GOTO	$+4
$025D	$0BFA			DECFSZ	STACK_10, F
$025E	$2A5D			GOTO	$-1
$025F	$2A5A			GOTO	$-5
$0260	$3042			MOVLW	66
$0261	$00FA			MOVWF	STACK_10
$0262	$0BFA			DECFSZ	STACK_10, F
$0263	$2A62			GOTO	$-1
;DisplayLCD.ppas,11 :: 		Lcd8_Config(PORTE, PORTD, 1, 0, 2, 7, 6, 5, 4, 3, 2, 1, 0);  //Configura os pinos do display
$0264	$3009			MOVLW	PORTE
$0265	$1283			BCF	STATUS, RP0
$0266	$00C4			MOVWF	FARG_Lcd8_Config
$0267	$3008			MOVLW	PORTD
$0268	$00C5			MOVWF	FARG_Lcd8_Config+1
$0269	$3001			MOVLW	1
$026A	$00C6			MOVWF	FARG_Lcd8_Config+2
$026B	$01C7			CLRF	FARG_Lcd8_Config+3, 1
$026C	$3002			MOVLW	2
$026D	$00C8			MOVWF	FARG_Lcd8_Config+4
$026E	$3007			MOVLW	7
$026F	$00C9			MOVWF	FARG_Lcd8_Config+5
$0270	$3006			MOVLW	6
$0271	$00CA			MOVWF	FARG_Lcd8_Config+6
$0272	$3005			MOVLW	5
$0273	$00CB			MOVWF	FARG_Lcd8_Config+7
$0274	$3004			MOVLW	4
$0275	$00CC			MOVWF	FARG_Lcd8_Config+8
$0276	$3003			MOVLW	3
$0277	$00CD			MOVWF	FARG_Lcd8_Config+9
$0278	$3002			MOVLW	2
$0279	$00CE			MOVWF	FARG_Lcd8_Config+10
$027A	$3001			MOVLW	1
$027B	$00CF			MOVWF	FARG_Lcd8_Config+11
$027C	$01D0			CLRF	FARG_Lcd8_Config+12, 1
$027D	$2108			CALL	_lcd8_config
;DisplayLCD.ppas,12 :: 		Lcd8_init(PORTE,PORTD);             //Inicializa o display
$027E	$3009			MOVLW	PORTE
$027F	$00C0			MOVWF	FARG_Lcd8_Init
$0280	$3008			MOVLW	PORTD
$0281	$00C1			MOVWF	FARG_Lcd8_Init+1
$0282	$21E1			CALL	_lcd8_init
;DisplayLCD.ppas,13 :: 		Lcd8_out(1, 1, 'Teste do Display'); //Mostra mensagem no display
$0283	$3001			MOVLW	1
$0284	$00C0			MOVWF	FARG_Lcd8_Out
$0285	$3001			MOVLW	1
$0286	$00C1			MOVWF	FARG_Lcd8_Out+1
$0287	$3054			MOVLW	84
$0288	$00AF			MOVWF	?main_Local_Text+0
$0289	$3065			MOVLW	101
$028A	$00B0			MOVWF	?main_Local_Text+1
$028B	$3073			MOVLW	115
$028C	$00B1			MOVWF	?main_Local_Text+2
$028D	$3074			MOVLW	116
$028E	$00B2			MOVWF	?main_Local_Text+3
$028F	$3065			MOVLW	101
$0290	$00B3			MOVWF	?main_Local_Text+4
$0291	$3020			MOVLW	32
$0292	$00B4			MOVWF	?main_Local_Text+5
$0293	$3064			MOVLW	100
$0294	$00B5			MOVWF	?main_Local_Text+6
$0295	$306F			MOVLW	111
$0296	$00B6			MOVWF	?main_Local_Text+7
$0297	$3020			MOVLW	32
$0298	$00B7			MOVWF	?main_Local_Text+8
$0299	$3044			MOVLW	68
$029A	$00B8			MOVWF	?main_Local_Text+9
$029B	$3069			MOVLW	105
$029C	$00B9			MOVWF	?main_Local_Text+10
$029D	$3073			MOVLW	115
$029E	$00BA			MOVWF	?main_Local_Text+11
$029F	$3070			MOVLW	112
$02A0	$00BB			MOVWF	?main_Local_Text+12
$02A1	$306C			MOVLW	108
$02A2	$00BC			MOVWF	?main_Local_Text+13
$02A3	$3061			MOVLW	97
$02A4	$00BD			MOVWF	?main_Local_Text+14
$02A5	$3079			MOVLW	121
$02A6	$00BE			MOVWF	?main_Local_Text+15
$02A7	$01BF			CLRF	?main_Local_Text+16
$02A8	$302F			MOVLW	?main_Local_Text
$02A9	$00C2			MOVWF	FARG_Lcd8_Out+2
$02AA	$21FE			CALL	_lcd8_out
;DisplayLCD.ppas,14 :: 		Lcd8_out(2, 1, 'Cerne Tecnologia'); //Mostra mensagem no display
$02AB	$3002			MOVLW	2
$02AC	$00C0			MOVWF	FARG_Lcd8_Out
$02AD	$3001			MOVLW	1
$02AE	$00C1			MOVWF	FARG_Lcd8_Out+1
$02AF	$3043			MOVLW	67
$02B0	$00AF			MOVWF	?main_Local_Text+0
$02B1	$3065			MOVLW	101
$02B2	$00B0			MOVWF	?main_Local_Text+1
$02B3	$3072			MOVLW	114
$02B4	$00B1			MOVWF	?main_Local_Text+2
$02B5	$306E			MOVLW	110
$02B6	$00B2			MOVWF	?main_Local_Text+3
$02B7	$3065			MOVLW	101
$02B8	$00B3			MOVWF	?main_Local_Text+4
$02B9	$3020			MOVLW	32
$02BA	$00B4			MOVWF	?main_Local_Text+5
$02BB	$3054			MOVLW	84
$02BC	$00B5			MOVWF	?main_Local_Text+6
$02BD	$3065			MOVLW	101
$02BE	$00B6			MOVWF	?main_Local_Text+7
$02BF	$3063			MOVLW	99
$02C0	$00B7			MOVWF	?main_Local_Text+8
$02C1	$306E			MOVLW	110
$02C2	$00B8			MOVWF	?main_Local_Text+9
$02C3	$306F			MOVLW	111
$02C4	$00B9			MOVWF	?main_Local_Text+10
$02C5	$306C			MOVLW	108
$02C6	$00BA			MOVWF	?main_Local_Text+11
$02C7	$306F			MOVLW	111
$02C8	$00BB			MOVWF	?main_Local_Text+12
$02C9	$3067			MOVLW	103
$02CA	$00BC			MOVWF	?main_Local_Text+13
$02CB	$3069			MOVLW	105
$02CC	$00BD			MOVWF	?main_Local_Text+14
$02CD	$3061			MOVLW	97
$02CE	$00BE			MOVWF	?main_Local_Text+15
$02CF	$01BF			CLRF	?main_Local_Text+16
$02D0	$302F			MOVLW	?main_Local_Text
$02D1	$00C2			MOVWF	FARG_Lcd8_Out+2
$02D2	$21FE			CALL	_lcd8_out
$02D3	$	DisplayLCD_L_0:
;DisplayLCD.ppas,16 :: 		end.
$02D3	$2AD3			GOTO	$
