CREATE TABLE VENDAS (
    CD_VEN NUMBER(5),
	DT_VEN DATE,
	VL_VEN NUMBER(9,2)
);

CREATE TABLE CONTABILIZACAO (
    DT DATE,
	VALOR_TOTAL NUMBER(9,2)
);

SELECT * FROM VENDAS ORDER BY CD_VEN;
SELECT * FROM CONTABILIZACAO ORDER BY DT;

INSERT INTO VENDAS VALUES (1, SYSDATE, 100);
INSERT INTO VENDAS VALUES (2, SYSDATE-1, 50);
INSERT INTO VENDAS VALUES (3, SYSDATE-1, 45);

DELETE FROM VENDAS WHERE CD_VEN=2;

UPDATE VENDAS SET VL_VEN = VL_VEN-20 WHERE CD_VEN = 3;