CREATE OR REPLACE TRIGGER TRG02
AFTER DELETE ON VENDAS
FOR EACH ROW

DECLARE
  WVALOR NUMBER(9,2);
BEGIN
  
  SELECT VALOR_TOTAL INTO WVALOR
   FROM CONTABILIZACAO
   WHERE TRUNC(DT) = TRUNC(:OLD.DT_VEN)
  ;
  
  IF WVALOR - :OLD.VL_VEN = 0 THEN

    DELETE FROM CONTABILIZACAO
     WHERE TRUNC(DT) = TRUNC(:OLD.DT_VEN)
	;
	
  ELSE
  
    UPDATE CONTABILIZACAO
     SET VALOR_TOTAL = VALOR_TOTAL - :OLD.VL_VEN
     WHERE TRUNC(DT) = TRUNC(:OLD.DT_VEN);
	
  END IF;

END;