CREATE OR REPLACE TRIGGER TRG01
AFTER INSERT ON VENDAS
FOR EACH ROW

DECLARE
  
  WEXISTE NUMBER(1);
  
BEGIN
  
  SELECT COUNT(*) INTO WEXISTE
   FROM CONTABILIZACAO
   WHERE TRUNC(DT) = TRUNC(:NEW.DT_VEN)
  ;
  
  IF WEXISTE = 0 THEN
    
	INSERT INTO CONTABILIZACAO(DT, VALOR_TOTAL)
	   VALUES(:NEW.DT_VEN, :NEW.VL_VEN);

  ELSE
  
    UPDATE CONTABILIZACAO
	 SET VALOR_TOTAL = VALOR_TOTAL + :NEW.VL_VEN
	 WHERE TRUNC(DT) = TRUNC(:NEW.DT_VEN);
	 
  END IF;

END;