CREATE OR REPLACE TRIGGER TRG03
AFTER UPDATE ON VENDAS
FOR EACH ROW

DECLARE

BEGIN

  UPDATE CONTABILIZACAO
   SET VALOR_TOTAL = VALOR_TOTAL - 
       (:OLD.VL_VEN - :NEW.VL_VEN)
   WHERE TRUNC(DT) = TRUNC(:OLD.DT_VEN)
  ;

END;