;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 4/3/2008 13:16:38
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;Pisca.ppas,3 :: 		begin
;Pisca.ppas,5 :: 		trisd:=%00000000;       //Configura todo o PORTD como saída
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0188			CLRF	TRISD, 1
;Pisca.ppas,6 :: 		trisb:=%00000000;       //Configura todo o PORTB como saída
$0007	$0186			CLRF	TRISB, 1
;Pisca.ppas,7 :: 		portb:=%00100000;       //Liga o pino RB5 para acionar a linha de seleção dos leds
$0008	$3020			MOVLW	32
$0009	$1283			BCF	STATUS, RP0
$000A	$0086			MOVWF	PORTB
;Pisca.ppas,9 :: 		while true do
$000B	$	Pisca_L_2:
;Pisca.ppas,11 :: 		portd:=%00000001;       //Deixa o pino RD0 em nível alto
$000B	$3001			MOVLW	1
$000C	$0088			MOVWF	PORTD
;Pisca.ppas,12 :: 		delay_ms(250);          //Aguarda 250 ms
$000D	$3002			MOVLW	2
$000E	$00FC			MOVWF	STACK_12
$000F	$30FF			MOVLW	255
$0010	$00FB			MOVWF	STACK_11
$0011	$30FF			MOVLW	255
$0012	$00FA			MOVWF	STACK_10
$0013	$0BFC			DECFSZ	STACK_12, F
$0014	$2816			GOTO	$+2
$0015	$281D			GOTO	$+8
$0016	$0BFB			DECFSZ	STACK_11, F
$0017	$2819			GOTO	$+2
$0018	$281C			GOTO	$+4
$0019	$0BFA			DECFSZ	STACK_10, F
$001A	$2819			GOTO	$-1
$001B	$2816			GOTO	$-5
$001C	$2813			GOTO	$-9
$001D	$3046			MOVLW	70
$001E	$00FB			MOVWF	STACK_11
$001F	$30FF			MOVLW	255
$0020	$00FA			MOVWF	STACK_10
$0021	$0BFB			DECFSZ	STACK_11, F
$0022	$2824			GOTO	$+2
$0023	$2827			GOTO	$+4
$0024	$0BFA			DECFSZ	STACK_10, F
$0025	$2824			GOTO	$-1
$0026	$2821			GOTO	$-5
$0027	$30CF			MOVLW	207
$0028	$00FA			MOVWF	STACK_10
$0029	$0BFA			DECFSZ	STACK_10, F
$002A	$2829			GOTO	$-1
$002B	$0000			NOP
;Pisca.ppas,13 :: 		portd:=%00000000;       //Deixa o pino RD0 em nível baixo
$002C	$0188			CLRF	PORTD, 1
;Pisca.ppas,14 :: 		delay_ms(250);          //Aguarda 250 ms
$002D	$3002			MOVLW	2
$002E	$00FC			MOVWF	STACK_12
$002F	$30FF			MOVLW	255
$0030	$00FB			MOVWF	STACK_11
$0031	$30FF			MOVLW	255
$0032	$00FA			MOVWF	STACK_10
$0033	$0BFC			DECFSZ	STACK_12, F
$0034	$2836			GOTO	$+2
$0035	$283D			GOTO	$+8
$0036	$0BFB			DECFSZ	STACK_11, F
$0037	$2839			GOTO	$+2
$0038	$283C			GOTO	$+4
$0039	$0BFA			DECFSZ	STACK_10, F
$003A	$2839			GOTO	$-1
$003B	$2836			GOTO	$-5
$003C	$2833			GOTO	$-9
$003D	$3046			MOVLW	70
$003E	$00FB			MOVWF	STACK_11
$003F	$30FF			MOVLW	255
$0040	$00FA			MOVWF	STACK_10
$0041	$0BFB			DECFSZ	STACK_11, F
$0042	$2844			GOTO	$+2
$0043	$2847			GOTO	$+4
$0044	$0BFA			DECFSZ	STACK_10, F
$0045	$2844			GOTO	$-1
$0046	$2841			GOTO	$-5
$0047	$30CF			MOVLW	207
$0048	$00FA			MOVWF	STACK_10
$0049	$0BFA			DECFSZ	STACK_10, F
$004A	$2849			GOTO	$-1
$004B	$0000			NOP
;Pisca.ppas,15 :: 		end;
$004C	$280B			GOTO	Pisca_L_2
;Pisca.ppas,16 :: 		end.
$004D	$284D			GOTO	$
