;  Assembly code generated by mikroVirtualMachine - V. 5.0.0.3
;  Date/Time: 4/3/2008 13:17:54
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2804			GOTO	_main
$0004	$	_main:
;Display.ppas,3 :: 		begin
;Display.ppas,4 :: 		trisd:=%00000000;       //Configura todo o PORTD como saída
$0004	$1303			BCF	STATUS, RP1
$0005	$1683			BSF	STATUS, RP0
$0006	$0188			CLRF	TRISD, 1
;Display.ppas,5 :: 		trisb:=%00000000;       //Configura todo o PORTB como saída
$0007	$0186			CLRF	TRISB, 1
;Display.ppas,6 :: 		portd:=79;              //Carrega no barramento o valor referente ao digito 3
$0008	$304F			MOVLW	79
$0009	$1283			BCF	STATUS, RP0
$000A	$0088			MOVWF	PORTD
;Display.ppas,7 :: 		portb:=%00010000;       //Liga um display do barramento
$000B	$3010			MOVLW	16
$000C	$0086			MOVWF	PORTB
$000D	$	Display_L_0:
;Display.ppas,8 :: 		end.
$000D	$280D			GOTO	$
