;  ASM code generated by mikroVirtualMachine for PIC - V. 6.2.1.0
;  Date/Time: 29/7/2007 14:16:40
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$2922			GOTO	_main
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00AC			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00AB			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00AD			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0870			MOVF	STACK_0, 0
$000E	$00AF			MOVWF	STSAVED_0
;usart.c,102 :: 		void interrupt(void)
;usart.c,105 :: 		if (intcon.t0if == 1)             //Tratamento da interrupção
$000F	$3000			MOVLW	0
$0010	$190B			BTFSC	INTCON, 2
$0011	$3001			MOVLW	1
$0012	$00F2			MOVWF	STACK_2
$0013	$0872			MOVF	STACK_2, 0
$0014	$3A01			XORLW	1
$0015	$1D03			BTFSS	STATUS, Z
$0016	$2868			GOTO	L_interrupt_18
;usart.c,107 :: 		intcon.t0if=0;                //de timer 0
$0017	$110B			BCF	INTCON, 2
;usart.c,108 :: 		indice++;
$0018	$0AA0			INCF	_indice, 1
;usart.c,110 :: 		switch(indice)
$0019	$2857			GOTO	L_interrupt_19
;usart.c,112 :: 		case 1:
$001A	$	L_interrupt_21:
;usart.c,113 :: 		portb.f4=0;
$001A	$1206			BCF	PORTB, 4
;usart.c,114 :: 		portd=vetor_display[indice-1];
$001B	$3001			MOVLW	1
$001C	$0220			SUBWF	_indice, 0
$001D	$00F0			MOVWF	STACK_0
$001E	$01F1			CLRF	STACK_0+1
$001F	$1C03			BTFSS	STATUS, C
$0020	$03F1			DECF	STACK_0+1, 1
$0021	$0870			MOVF	STACK_0, 0
$0022	$3F21			ADDLW	_vetor_display
$0023	$0084			MOVWF	FSR
$0024	$0800			MOVF	INDF, 0
$0025	$0088			MOVWF	PORTD
;usart.c,115 :: 		portb.f1=1;
$0026	$1486			BSF	PORTB, 1
;usart.c,116 :: 		break;
$0027	$2867			GOTO	L_interrupt_20
;usart.c,118 :: 		case 2:
$0028	$	L_interrupt_22:
;usart.c,119 :: 		portb.f1=0;
$0028	$1086			BCF	PORTB, 1
;usart.c,120 :: 		portd=vetor_display[indice-1];
$0029	$3001			MOVLW	1
$002A	$0220			SUBWF	_indice, 0
$002B	$00F0			MOVWF	STACK_0
$002C	$01F1			CLRF	STACK_0+1
$002D	$1C03			BTFSS	STATUS, C
$002E	$03F1			DECF	STACK_0+1, 1
$002F	$0870			MOVF	STACK_0, 0
$0030	$3F21			ADDLW	_vetor_display
$0031	$0084			MOVWF	FSR
$0032	$0800			MOVF	INDF, 0
$0033	$0088			MOVWF	PORTD
;usart.c,121 :: 		portb.f2=1;
$0034	$1506			BSF	PORTB, 2
;usart.c,122 :: 		if (pisca) portd.f7=1;        //Seta o pino para piscar o display
$0035	$0825			MOVF	_pisca, 0
$0036	$1903			BTFSC	STATUS, Z
$0037	$2839			GOTO	L_interrupt_23
$0038	$1788			BSF	PORTD, 7
$0039	$	L_interrupt_23:
;usart.c,123 :: 		break;
$0039	$2867			GOTO	L_interrupt_20
;usart.c,125 :: 		case 3:
$003A	$	L_interrupt_24:
;usart.c,126 :: 		portb.f2=0;
$003A	$1106			BCF	PORTB, 2
;usart.c,127 :: 		portd=vetor_display[indice-1];
$003B	$3001			MOVLW	1
$003C	$0220			SUBWF	_indice, 0
$003D	$00F0			MOVWF	STACK_0
$003E	$01F1			CLRF	STACK_0+1
$003F	$1C03			BTFSS	STATUS, C
$0040	$03F1			DECF	STACK_0+1, 1
$0041	$0870			MOVF	STACK_0, 0
$0042	$3F21			ADDLW	_vetor_display
$0043	$0084			MOVWF	FSR
$0044	$0800			MOVF	INDF, 0
$0045	$0088			MOVWF	PORTD
;usart.c,128 :: 		portb.f3=1;
$0046	$1586			BSF	PORTB, 3
;usart.c,129 :: 		break;
$0047	$2867			GOTO	L_interrupt_20
;usart.c,131 :: 		case 4:
$0048	$	L_interrupt_25:
;usart.c,132 :: 		portb.f3=0;
$0048	$1186			BCF	PORTB, 3
;usart.c,133 :: 		portd=vetor_display[indice-1];
$0049	$3001			MOVLW	1
$004A	$0220			SUBWF	_indice, 0
$004B	$00F0			MOVWF	STACK_0
$004C	$01F1			CLRF	STACK_0+1
$004D	$1C03			BTFSS	STATUS, C
$004E	$03F1			DECF	STACK_0+1, 1
$004F	$0870			MOVF	STACK_0, 0
$0050	$3F21			ADDLW	_vetor_display
$0051	$0084			MOVWF	FSR
$0052	$0800			MOVF	INDF, 0
$0053	$0088			MOVWF	PORTD
;usart.c,134 :: 		portb.f4=1;
$0054	$1606			BSF	PORTB, 4
;usart.c,135 :: 		indice=0;
$0055	$01A0			CLRF	_indice, 1
;usart.c,136 :: 		break;
$0056	$2867			GOTO	L_interrupt_20
;usart.c,138 :: 		}
$0057	$	L_interrupt_19:
$0057	$0820			MOVF	_indice, 0
$0058	$3A01			XORLW	1
$0059	$1903			BTFSC	STATUS, Z
$005A	$281A			GOTO	L_interrupt_21
$005B	$0820			MOVF	_indice, 0
$005C	$3A02			XORLW	2
$005D	$1903			BTFSC	STATUS, Z
$005E	$2828			GOTO	L_interrupt_22
$005F	$0820			MOVF	_indice, 0
$0060	$3A03			XORLW	3
$0061	$1903			BTFSC	STATUS, Z
$0062	$283A			GOTO	L_interrupt_24
$0063	$0820			MOVF	_indice, 0
$0064	$3A04			XORLW	4
$0065	$1903			BTFSC	STATUS, Z
$0066	$2848			GOTO	L_interrupt_25
$0067	$	L_interrupt_20:
;usart.c,139 :: 		}
$0067	$2896			GOTO	L_interrupt_26
$0068	$	L_interrupt_18:
;usart.c,142 :: 		tmr1h=0X0B;
$0068	$300B			MOVLW	11
$0069	$008F			MOVWF	TMR1H
;usart.c,143 :: 		tmr1l=0XDC;
$006A	$30DC			MOVLW	220
$006B	$008E			MOVWF	TMR1L
;usart.c,144 :: 		pir1.tmr1if=0;            //limpa flag de interrupção
$006C	$100C			BCF	PIR1, 0
;usart.c,145 :: 		pisca=!pisca;           //inverte o estado do pisca
$006D	$0825			MOVF	_pisca, 0
$006E	$3001			MOVLW	1
$006F	$1D03			BTFSS	STATUS, Z
$0070	$3000			MOVLW	0
$0071	$00A5			MOVWF	_pisca
;usart.c,146 :: 		vezes_tmr1--;            //decrementa variável para dar 1 segundo
$0072	$03A6			DECF	_vezes_tmr1, 1
;usart.c,148 :: 		if (vezes_tmr1==0)
$0073	$0826			MOVF	_vezes_tmr1, 0
$0074	$3A00			XORLW	0
$0075	$1D03			BTFSS	STATUS, Z
$0076	$2896			GOTO	L_interrupt_27
;usart.c,150 :: 		vezes_tmr1=120;
$0077	$3078			MOVLW	120
$0078	$00A6			MOVWF	_vezes_tmr1
;usart.c,151 :: 		minuto_lsb++;
$0079	$0AA7			INCF	_minuto_lsb, 1
;usart.c,153 :: 		if (minuto_lsb==10)
$007A	$0827			MOVF	_minuto_lsb, 0
$007B	$3A0A			XORLW	10
$007C	$1D03			BTFSS	STATUS, Z
$007D	$2896			GOTO	L_interrupt_28
;usart.c,155 :: 		minuto_lsb=0;
$007E	$01A7			CLRF	_minuto_lsb, 1
;usart.c,156 :: 		minuto_msb++;
$007F	$0AA8			INCF	_minuto_msb, 1
;usart.c,157 :: 		if (minuto_msb==6)
$0080	$0828			MOVF	_minuto_msb, 0
$0081	$3A06			XORLW	6
$0082	$1D03			BTFSS	STATUS, Z
$0083	$2896			GOTO	L_interrupt_29
;usart.c,159 :: 		minuto_msb=0;
$0084	$01A8			CLRF	_minuto_msb, 1
;usart.c,160 :: 		hora_lsb++;
$0085	$0AA9			INCF	_hora_lsb, 1
;usart.c,161 :: 		if (hora_msb==2)
$0086	$082A			MOVF	_hora_msb, 0
$0087	$3A02			XORLW	2
$0088	$1D03			BTFSS	STATUS, Z
$0089	$2890			GOTO	L_interrupt_30
;usart.c,163 :: 		if (hora_lsb==4)
$008A	$0829			MOVF	_hora_lsb, 0
$008B	$3A04			XORLW	4
$008C	$1D03			BTFSS	STATUS, Z
$008D	$2890			GOTO	L_interrupt_31
;usart.c,165 :: 		hora_msb=0;
$008E	$01AA			CLRF	_hora_msb, 1
;usart.c,166 :: 		hora_lsb=0;
$008F	$01A9			CLRF	_hora_lsb, 1
;usart.c,167 :: 		}
$0090	$	L_interrupt_31:
;usart.c,168 :: 		}
$0090	$	L_interrupt_30:
;usart.c,169 :: 		if (hora_lsb==10)
$0090	$0829			MOVF	_hora_lsb, 0
$0091	$3A0A			XORLW	10
$0092	$1D03			BTFSS	STATUS, Z
$0093	$2896			GOTO	L_interrupt_32
;usart.c,171 :: 		hora_lsb=0;
$0094	$01A9			CLRF	_hora_lsb, 1
;usart.c,172 :: 		hora_msb++;
$0095	$0AAA			INCF	_hora_msb, 1
;usart.c,173 :: 		}
$0096	$	L_interrupt_32:
;usart.c,174 :: 		}
$0096	$	L_interrupt_29:
;usart.c,175 :: 		}
$0096	$	L_interrupt_28:
;usart.c,177 :: 		}
$0096	$	L_interrupt_27:
;usart.c,178 :: 		}
$0096	$	L_interrupt_26:
;usart.c,179 :: 		}
$0096	$	L_Interrupt_end:
$0096	$082F			MOVF	STSAVED_0, 0
$0097	$00F0			MOVWF	STACK_0
$0098	$082D			MOVF	?savePCLATH, 0
$0099	$008A			MOVWF	PCLATH
$009A	$082B			MOVF	?saveFSR, 0
$009B	$0084			MOVWF	FSR
$009C	$0E2C			SWAPF	?saveSTATUS, 0
$009D	$0083			MOVWF	STATUS
$009E	$0EFF			SWAPF	STACK_15, 1
$009F	$0E7F			SWAPF	STACK_15, 0
$00A0	$0009			RETFIE
$00A1	$	_Converte_to_7seg:
;usart.c,59 :: 		unsigned char Converte_to_7seg (char dado)
;usart.c,61 :: 		switch(dado)           //tabela de conversão para display de 7 segmentos
$00A1	$28D4			GOTO	L_Converte_to_7seg_0
;usart.c,63 :: 		case 0 : return(CHR_0);
$00A2	$	L_Converte_to_7seg_2:
$00A2	$303F			MOVLW	63
$00A3	$1303			BCF	STATUS, RP1
$00A4	$1283			BCF	STATUS, RP0
$00A5	$00F0			MOVWF	STACK_0
$00A6	$0008			RETURN
;usart.c,65 :: 		case 1 : return(CHR_1);
$00A7	$	L_Converte_to_7seg_3:
$00A7	$3006			MOVLW	6
$00A8	$00F0			MOVWF	STACK_0
$00A9	$0008			RETURN
;usart.c,67 :: 		case 2 : return(CHR_2);
$00AA	$	L_Converte_to_7seg_4:
$00AA	$305B			MOVLW	91
$00AB	$00F0			MOVWF	STACK_0
$00AC	$0008			RETURN
;usart.c,69 :: 		case 3 : return(CHR_3);
$00AD	$	L_Converte_to_7seg_5:
$00AD	$304F			MOVLW	79
$00AE	$00F0			MOVWF	STACK_0
$00AF	$0008			RETURN
;usart.c,71 :: 		case 4 : return(CHR_4);
$00B0	$	L_Converte_to_7seg_6:
$00B0	$3066			MOVLW	102
$00B1	$00F0			MOVWF	STACK_0
$00B2	$0008			RETURN
;usart.c,73 :: 		case 5 : return(CHR_5);
$00B3	$	L_Converte_to_7seg_7:
$00B3	$306D			MOVLW	109
$00B4	$00F0			MOVWF	STACK_0
$00B5	$0008			RETURN
;usart.c,75 :: 		case 6 : return(CHR_6);
$00B6	$	L_Converte_to_7seg_8:
$00B6	$307D			MOVLW	125
$00B7	$00F0			MOVWF	STACK_0
$00B8	$0008			RETURN
;usart.c,77 :: 		case 7 : return(CHR_7);
$00B9	$	L_Converte_to_7seg_9:
$00B9	$3007			MOVLW	7
$00BA	$00F0			MOVWF	STACK_0
$00BB	$0008			RETURN
;usart.c,79 :: 		case 8 : return(CHR_8);
$00BC	$	L_Converte_to_7seg_10:
$00BC	$307F			MOVLW	127
$00BD	$00F0			MOVWF	STACK_0
$00BE	$0008			RETURN
;usart.c,81 :: 		case 9 : return(CHR_9);
$00BF	$	L_Converte_to_7seg_11:
$00BF	$306F			MOVLW	111
$00C0	$00F0			MOVWF	STACK_0
$00C1	$0008			RETURN
;usart.c,83 :: 		case 10 : return(CHR_A);
$00C2	$	L_Converte_to_7seg_12:
$00C2	$3077			MOVLW	119
$00C3	$00F0			MOVWF	STACK_0
$00C4	$0008			RETURN
;usart.c,85 :: 		case 11 : return(CHR_B);
$00C5	$	L_Converte_to_7seg_13:
$00C5	$307C			MOVLW	124
$00C6	$00F0			MOVWF	STACK_0
$00C7	$0008			RETURN
;usart.c,87 :: 		case 12 : return(CHR_C);
$00C8	$	L_Converte_to_7seg_14:
$00C8	$3039			MOVLW	57
$00C9	$00F0			MOVWF	STACK_0
$00CA	$0008			RETURN
;usart.c,89 :: 		case 13 : return(CHR_D);
$00CB	$	L_Converte_to_7seg_15:
$00CB	$305E			MOVLW	94
$00CC	$00F0			MOVWF	STACK_0
$00CD	$0008			RETURN
;usart.c,91 :: 		case 14 : return(CHR_E);
$00CE	$	L_Converte_to_7seg_16:
$00CE	$3079			MOVLW	121
$00CF	$00F0			MOVWF	STACK_0
$00D0	$0008			RETURN
;usart.c,93 :: 		case 15 : return(CHR_F);
$00D1	$	L_Converte_to_7seg_17:
$00D1	$3071			MOVLW	113
$00D2	$00F0			MOVWF	STACK_0
$00D3	$0008			RETURN
;usart.c,95 :: 		}
$00D4	$	L_Converte_to_7seg_0:
$00D4	$1303			BCF	STATUS, RP1
$00D5	$1283			BCF	STATUS, RP0
$00D6	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00D7	$3A00			XORLW	0
$00D8	$1903			BTFSC	STATUS, Z
$00D9	$28A2			GOTO	L_Converte_to_7seg_2
$00DA	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00DB	$3A01			XORLW	1
$00DC	$1903			BTFSC	STATUS, Z
$00DD	$28A7			GOTO	L_Converte_to_7seg_3
$00DE	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00DF	$3A02			XORLW	2
$00E0	$1903			BTFSC	STATUS, Z
$00E1	$28AA			GOTO	L_Converte_to_7seg_4
$00E2	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00E3	$3A03			XORLW	3
$00E4	$1903			BTFSC	STATUS, Z
$00E5	$28AD			GOTO	L_Converte_to_7seg_5
$00E6	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00E7	$3A04			XORLW	4
$00E8	$1903			BTFSC	STATUS, Z
$00E9	$28B0			GOTO	L_Converte_to_7seg_6
$00EA	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00EB	$3A05			XORLW	5
$00EC	$1903			BTFSC	STATUS, Z
$00ED	$28B3			GOTO	L_Converte_to_7seg_7
$00EE	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00EF	$3A06			XORLW	6
$00F0	$1903			BTFSC	STATUS, Z
$00F1	$28B6			GOTO	L_Converte_to_7seg_8
$00F2	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00F3	$3A07			XORLW	7
$00F4	$1903			BTFSC	STATUS, Z
$00F5	$28B9			GOTO	L_Converte_to_7seg_9
$00F6	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00F7	$3A08			XORLW	8
$00F8	$1903			BTFSC	STATUS, Z
$00F9	$28BC			GOTO	L_Converte_to_7seg_10
$00FA	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00FB	$3A09			XORLW	9
$00FC	$1903			BTFSC	STATUS, Z
$00FD	$28BF			GOTO	L_Converte_to_7seg_11
$00FE	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$00FF	$3A0A			XORLW	10
$0100	$1903			BTFSC	STATUS, Z
$0101	$28C2			GOTO	L_Converte_to_7seg_12
$0102	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$0103	$3A0B			XORLW	11
$0104	$1903			BTFSC	STATUS, Z
$0105	$28C5			GOTO	L_Converte_to_7seg_13
$0106	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$0107	$3A0C			XORLW	12
$0108	$1903			BTFSC	STATUS, Z
$0109	$28C8			GOTO	L_Converte_to_7seg_14
$010A	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$010B	$3A0D			XORLW	13
$010C	$1903			BTFSC	STATUS, Z
$010D	$28CB			GOTO	L_Converte_to_7seg_15
$010E	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$010F	$3A0E			XORLW	14
$0110	$1903			BTFSC	STATUS, Z
$0111	$28CE			GOTO	L_Converte_to_7seg_16
$0112	$082E			MOVF	FARG_Converte_to_7seg+0, 0
$0113	$3A0F			XORLW	15
$0114	$1903			BTFSC	STATUS, Z
$0115	$28D1			GOTO	L_Converte_to_7seg_17
$0116	$	L_Converte_to_7seg_1:
;usart.c,96 :: 		}
$0116	$0008			RETURN
$0117	$	GlobalIniusart:
$0117	$3000			MOVLW	0
$0118	$1303			BCF	STATUS, RP1
$0119	$1283			BCF	STATUS, RP0
$011A	$00AA			MOVWF	_hora_msb+0
$011B	$3000			MOVLW	0
$011C	$00A9			MOVWF	_hora_lsb+0
$011D	$3000			MOVLW	0
$011E	$00A8			MOVWF	_minuto_msb+0
$011F	$3000			MOVLW	0
$0120	$00A7			MOVWF	_minuto_lsb+0
$0121	$0008			RETURN
$0122	$	_main:
;usart.c,187 :: 		void main(void)
;usart.c,190 :: 		trisa=0b00000000;
$0122	$2117			CALL	GlobalIniusart, 1
$0123	$1683			BSF	STATUS, RP0
$0124	$0185			CLRF	TRISA, 1
;usart.c,191 :: 		trisb=0b00000000;
$0125	$0186			CLRF	TRISB, 1
;usart.c,192 :: 		trisd=0b00000000;            //configura i/os
$0126	$0188			CLRF	TRISD, 1
;usart.c,193 :: 		option_reg=0b10000000;       //configura prescaler do timer 0
$0127	$3080			MOVLW	128
$0128	$0081			MOVWF	OPTION_REG
;usart.c,194 :: 		indice=0;                    //inicializa a variável de índice
$0129	$1283			BCF	STATUS, RP0
$012A	$01A0			CLRF	_indice, 1
;usart.c,195 :: 		hora_msb=0;
$012B	$01AA			CLRF	_hora_msb, 1
;usart.c,196 :: 		hora_lsb=0;
$012C	$01A9			CLRF	_hora_lsb, 1
;usart.c,197 :: 		minuto_msb=0;
$012D	$01A8			CLRF	_minuto_msb, 1
;usart.c,198 :: 		minuto_lsb=0;               //inicializa as variáveis de tempo
$012E	$01A7			CLRF	_minuto_lsb, 1
;usart.c,199 :: 		pie1=0b00000001;             //habilita interrupção de timer 1
$012F	$3001			MOVLW	1
$0130	$1683			BSF	STATUS, RP0
$0131	$008C			MOVWF	PIE1
;usart.c,200 :: 		t1con=0b00110001;            //configura timer 1 para prescaler de 1:8
$0132	$3031			MOVLW	49
$0133	$1283			BCF	STATUS, RP0
$0134	$0090			MOVWF	T1CON
;usart.c,201 :: 		tmr1h=0x0B;
$0135	$300B			MOVLW	11
$0136	$008F			MOVWF	TMR1H
;usart.c,202 :: 		tmr1l=0xDC;
$0137	$30DC			MOVLW	220
$0138	$008E			MOVWF	TMR1L
;usart.c,203 :: 		vezes_tmr1=120;             //inicializa variável de contagem
$0139	$3078			MOVLW	120
$013A	$00A6			MOVWF	_vezes_tmr1
;usart.c,204 :: 		pisca=0;                    //inicializa variável de piscagem
$013B	$01A5			CLRF	_pisca, 1
;usart.c,205 :: 		intcon=0b11100000;          //configura interrupção de timer0
$013C	$30E0			MOVLW	224
$013D	$008B			MOVWF	INTCON
;usart.c,208 :: 		while (1)
$013E	$	L_main_33:
;usart.c,210 :: 		vetor_display[0]=Converte_to_7seg(hora_msb);
$013E	$082A			MOVF	_hora_msb, 0
$013F	$00AE			MOVWF	FARG_Converte_to_7seg+0
$0140	$20A1			CALL	_Converte_to_7seg
$0141	$1303			BCF	STATUS, RP1
$0142	$1283			BCF	STATUS, RP0
$0143	$0870			MOVF	STACK_0, 0
$0144	$00A1			MOVWF	_vetor_display
;usart.c,211 :: 		vetor_display[1]=Converte_to_7seg(hora_lsb);
$0145	$0829			MOVF	_hora_lsb, 0
$0146	$00AE			MOVWF	FARG_Converte_to_7seg+0
$0147	$20A1			CALL	_Converte_to_7seg
$0148	$1303			BCF	STATUS, RP1
$0149	$1283			BCF	STATUS, RP0
$014A	$0870			MOVF	STACK_0, 0
$014B	$00A2			MOVWF	_vetor_display+1
;usart.c,212 :: 		vetor_display[2]=Converte_to_7seg(minuto_msb);
$014C	$0828			MOVF	_minuto_msb, 0
$014D	$00AE			MOVWF	FARG_Converte_to_7seg+0
$014E	$20A1			CALL	_Converte_to_7seg
$014F	$1303			BCF	STATUS, RP1
$0150	$1283			BCF	STATUS, RP0
$0151	$0870			MOVF	STACK_0, 0
$0152	$00A3			MOVWF	_vetor_display+2
;usart.c,213 :: 		vetor_display[3]=Converte_to_7seg(minuto_lsb);
$0153	$0827			MOVF	_minuto_lsb, 0
$0154	$00AE			MOVWF	FARG_Converte_to_7seg+0
$0155	$20A1			CALL	_Converte_to_7seg
$0156	$1303			BCF	STATUS, RP1
$0157	$1283			BCF	STATUS, RP0
$0158	$0870			MOVF	STACK_0, 0
$0159	$00A4			MOVWF	_vetor_display+3
;usart.c,214 :: 		}
$015A	$293E			GOTO	L_main_33
;usart.c,216 :: 		}
$015B	$295B			GOTO	$
