;  ASM code generated by mikroVirtualMachine for PIC - V. 5.0.0.2
;  Date/Time: 27/10/2007 19:48:04
;  Info: http://www.mikroelektronika.co.yu


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$294E			GOTO	DisplayLCD_main
$0004	$	delays_delay_1us:
^delays.pbas, 5 :: 		sub procedure Delay_1us
^delays.pbas, 6 :: 		Delay_us(1)
$0004	$0000			NOP
$0005	$	delays_L_0:
$0005	$0008			RETURN
$0006	$	delays_delay_5500us:
^delays.pbas, 29 :: 		sub procedure Delay_5500us
^delays.pbas, 30 :: 		Delay_us(5500)
$0006	$3008			MOVLW	8
$0007	$1303			BCF	STATUS, RP1
$0008	$1283			BCF	STATUS, RP0
$0009	$00FB			MOVWF	STACK_11
$000A	$30FF			MOVLW	255
$000B	$00FA			MOVWF	STACK_10
$000C	$0BFB			DECFSZ	STACK_11, F
$000D	$280F			GOTO	$+2
$000E	$2812			GOTO	$+4
$000F	$0BFA			DECFSZ	STACK_10, F
$0010	$280F			GOTO	$-1
$0011	$280C			GOTO	$-5
$0012	$301E			MOVLW	30
$0013	$00FA			MOVWF	STACK_10
$0014	$0BFA			DECFSZ	STACK_10, F
$0015	$2814			GOTO	$-1
$0016	$	delays_L_6:
$0016	$0008			RETURN
$0017	$	delays_delay_500us:
^delays.pbas, 25 :: 		sub procedure Delay_500us
^delays.pbas, 26 :: 		Delay_us(498)
$0017	$30A5			MOVLW	165
$0018	$1303			BCF	STATUS, RP1
$0019	$1283			BCF	STATUS, RP0
$001A	$00FA			MOVWF	STACK_10
$001B	$0BFA			DECFSZ	STACK_10, F
$001C	$281B			GOTO	$-1
$001D	$0000			NOP
$001E	$0000			NOP
$001F	$	delays_L_5:
$001F	$0008			RETURN
$0020	$	lcd8bit_lcd8_cmd:
$0020	$1303			BCF	STATUS, RP1
$0021	$1283			BCF	STATUS, RP0
$0022	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0023	$0084			MOVWF	FSR
$0024	$0180			CLRF	INDF, 1
$0025	$1BBB			BTFSC	FARG_LCD8_CMD, 7
$0026	$1780			BSF	INDF, __LCD8_DB7
$0027	$1B3B			BTFSC	FARG_LCD8_CMD, 6
$0028	$1700			BSF	INDF, __LCD8_DB6
$0029	$1ABB			BTFSC	FARG_LCD8_CMD, 5
$002A	$1680			BSF	INDF, __LCD8_DB5
$002B	$1A3B			BTFSC	FARG_LCD8_CMD, 4
$002C	$1600			BSF	INDF, __LCD8_DB4
$002D	$19BB			BTFSC	FARG_LCD8_CMD, 3
$002E	$1580			BSF	INDF, __LCD8_DB3
$002F	$193B			BTFSC	FARG_LCD8_CMD, 2
$0030	$1500			BSF	INDF, __LCD8_DB2
$0031	$18BB			BTFSC	FARG_LCD8_CMD, 1
$0032	$1480			BSF	INDF, __LCD8_DB1
$0033	$183B			BTFSC	FARG_LCD8_CMD, 0
$0034	$1400			BSF	INDF, __LCD8_DB0
$0035	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0036	$0084			MOVWF	FSR
$0037	$0822			MOVF	lcd8bit_main_global_com, 0
$0038	$3A01			XORLW	1
$0039	$1D03			BTFSS	STATUS, Z
$003A	$283D			GOTO	lcd8bit_L_2
$003B	$	lcd8bit_L_1:
$003B	$1100			BCF	INDF, __LCD8_RS
$003C	$283E			GOTO	lcd8bit_L_3
$003D	$	lcd8bit_L_2:
$003D	$1500			BSF	INDF, __LCD8_RS
$003E	$	lcd8bit_L_3:
$003E	$1480			BSF	INDF, __LCD8_ENABLE
$003F	$2004			CALL	delays_delay_1us
$0040	$1080			BCF	INDF, __LCD8_ENABLE
$0041	$0822			MOVF	lcd8bit_main_global_com, 0
$0042	$3A01			XORLW	1
$0043	$1D03			BTFSS	STATUS, Z
$0044	$2847			GOTO	lcd8bit_L_5
$0045	$	lcd8bit_L_4:
$0045	$2006			CALL	delays_delay_5500us
$0046	$2848			GOTO	lcd8bit_L_6
$0047	$	lcd8bit_L_5:
$0047	$2017			CALL	delays_delay_500us
$0048	$	lcd8bit_L_6:
$0048	$	lcd8bit_L_0:
$0048	$0008			RETURN
$0049	$	lcd8bit_lcd8_init:
$0049	$2006			CALL	delays_delay_5500us
$004A	$2006			CALL	delays_delay_5500us
$004B	$2006			CALL	delays_delay_5500us
$004C	$0837			MOVF	FARG_Lcd8_Init+1, 0
$004D	$00A0			MOVWF	lcd8bit_main_global_dataaddress
$004E	$0836			MOVF	FARG_Lcd8_Init, 0
$004F	$00A1			MOVWF	lcd8bit_main_global_ctrladdress
$0050	$0837			MOVF	FARG_Lcd8_Init+1, 0
$0051	$0084			MOVWF	FSR
$0052	$1784			BSF	FSR, 7
$0053	$0180			CLRF	INDF, 1
$0054	$0836			MOVF	FARG_Lcd8_Init, 0
$0055	$0084			MOVWF	FSR
$0056	$1000			BCF	INDF, __LCD8_RW
$0057	$1784			BSF	FSR, 7
$0058	$1100			BCF	INDF, __LCD8_RS
$0059	$1000			BCF	INDF, __LCD8_RW
$005A	$1080			BCF	INDF, __LCD8_ENABLE
$005B	$1384			BCF	FSR, 7
$005C	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$005D	$0084			MOVWF	FSR
$005E	$3030			MOVLW	48
$005F	$0080			MOVWF	INDF
$0060	$2006			CALL	delays_delay_5500us
$0061	$2006			CALL	delays_delay_5500us
$0062	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0063	$0084			MOVWF	FSR
$0064	$1480			BSF	INDF, __LCD8_ENABLE
$0065	$2004			CALL	delays_delay_1us
$0066	$1080			BCF	INDF, __LCD8_ENABLE
$0067	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0068	$0084			MOVWF	FSR
$0069	$3030			MOVLW	48
$006A	$0080			MOVWF	INDF
$006B	$2006			CALL	delays_delay_5500us
$006C	$2006			CALL	delays_delay_5500us
$006D	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$006E	$0084			MOVWF	FSR
$006F	$1480			BSF	INDF, __LCD8_ENABLE
$0070	$2004			CALL	delays_delay_1us
$0071	$1080			BCF	INDF, __LCD8_ENABLE
$0072	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0073	$0084			MOVWF	FSR
$0074	$3030			MOVLW	48
$0075	$0080			MOVWF	INDF
$0076	$2006			CALL	delays_delay_5500us
$0077	$2006			CALL	delays_delay_5500us
$0078	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0079	$0084			MOVWF	FSR
$007A	$1480			BSF	INDF, __LCD8_ENABLE
$007B	$2004			CALL	delays_delay_1us
$007C	$1080			BCF	INDF, __LCD8_ENABLE
$007D	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$007E	$0084			MOVWF	FSR
$007F	$3038			MOVLW	56
$0080	$0080			MOVWF	INDF
$0081	$2006			CALL	delays_delay_5500us
$0082	$2006			CALL	delays_delay_5500us
$0083	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$0084	$0084			MOVWF	FSR
$0085	$1480			BSF	INDF, __LCD8_ENABLE
$0086	$2004			CALL	delays_delay_1us
$0087	$1080			BCF	INDF, __LCD8_ENABLE
$0088	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0089	$0084			MOVWF	FSR
$008A	$3010			MOVLW	16
$008B	$0080			MOVWF	INDF
$008C	$2006			CALL	delays_delay_5500us
$008D	$2006			CALL	delays_delay_5500us
$008E	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$008F	$0084			MOVWF	FSR
$0090	$1480			BSF	INDF, __LCD8_ENABLE
$0091	$2004			CALL	delays_delay_1us
$0092	$1080			BCF	INDF, __LCD8_ENABLE
$0093	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$0094	$0084			MOVWF	FSR
$0095	$3001			MOVLW	1
$0096	$0080			MOVWF	INDF
$0097	$2006			CALL	delays_delay_5500us
$0098	$2006			CALL	delays_delay_5500us
$0099	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$009A	$0084			MOVWF	FSR
$009B	$1480			BSF	INDF, __LCD8_ENABLE
$009C	$2004			CALL	delays_delay_1us
$009D	$1080			BCF	INDF, __LCD8_ENABLE
$009E	$0820			MOVF	lcd8bit_main_global_dataaddress, 0
$009F	$0084			MOVWF	FSR
$00A0	$300F			MOVLW	15
$00A1	$0080			MOVWF	INDF
$00A2	$2006			CALL	delays_delay_5500us
$00A3	$2006			CALL	delays_delay_5500us
$00A4	$0821			MOVF	lcd8bit_main_global_ctrladdress, 0
$00A5	$0084			MOVWF	FSR
$00A6	$1480			BSF	INDF, __LCD8_ENABLE
$00A7	$2004			CALL	delays_delay_1us
$00A8	$1080			BCF	INDF, __LCD8_ENABLE
$00A9	$3001			MOVLW	1
$00AA	$00A2			MOVWF	lcd8bit_main_global_com
$00AB	$	lcd8bit_L_22:
$00AB	$0008			RETURN
$00AC	$	usartlib_u_a_usart_data_ready:
$00AC	$3000			MOVLW	0
$00AD	$1303			BCF	STATUS, RP1
$00AE	$1283			BCF	STATUS, RP0
$00AF	$1A8C			BTFSC	PIR1, 5
$00B0	$3001			MOVLW	1
$00B1	$00F1			MOVWF	STACK_1
$00B2	$0871			MOVF	STACK_1, 0
$00B3	$00B6			MOVWF	usartlib_u_a_usart_data_ready_local_result
$00B4	$	usartlib_u_a_L_18:
$00B4	$0836			MOVF	usartlib_u_a_usart_data_ready_local_result, 0
$00B5	$00F0			MOVWF	STACK_0
$00B6	$0008			RETURN
$00B7	$	usartlib_u_a_usart_read:
$00B7	$1303			BCF	STATUS, RP1
$00B8	$1283			BCF	STATUS, RP0
$00B9	$081A			MOVF	RCREG, 0
$00BA	$00B6			MOVWF	usartlib_u_a_usart_read_local_result
$00BB	$3000			MOVLW	0
$00BC	$1898			BTFSC	RCSTA, 1
$00BD	$3001			MOVLW	1
$00BE	$00F1			MOVWF	STACK_1
$00BF	$0871			MOVF	STACK_1, 0
$00C0	$3A01			XORLW	1
$00C1	$1D03			BTFSS	STATUS, Z
$00C2	$28C5			GOTO	usartlib_u_a_L_21
$00C3	$	usartlib_u_a_L_20:
$00C3	$1218			BCF	RCSTA, 4
$00C4	$	usartlib_u_a_L_24:
$00C4	$	usartlib_u_a_L_25:
$00C4	$1618			BSF	RCSTA, 4
$00C5	$	usartlib_u_a_L_26:
$00C5	$	usartlib_u_a_L_21:
$00C5	$	usartlib_u_a_L_22:
$00C5	$	usartlib_u_a_L_19:
$00C5	$0836			MOVF	usartlib_u_a_usart_read_local_result, 0
$00C6	$00F0			MOVWF	STACK_0
$00C7	$0008			RETURN
$00C8	$	lcd8bit_lcd8_chr:
$00C8	$	lcd8bit_L_10:
$00C8	$1303			BCF	STATUS, RP1
$00C9	$1283			BCF	STATUS, RP0
$00CA	$0836			MOVF	FARG_Lcd8_Chr, 0
$00CB	$3A01			XORLW	1
$00CC	$1D03			BTFSS	STATUS, Z
$00CD	$28D1			GOTO	lcd8bit_L_11
$00CE	$	lcd8bit_L_9:
$00CE	$3080			MOVLW	128
$00CF	$00B6			MOVWF	FARG_Lcd8_Chr
$00D0	$28E8			GOTO	lcd8bit_L_8
$00D1	$	lcd8bit_L_11:
$00D1	$	lcd8bit_L_13:
$00D1	$0836			MOVF	FARG_Lcd8_Chr, 0
$00D2	$3A02			XORLW	2
$00D3	$1D03			BTFSS	STATUS, Z
$00D4	$28D8			GOTO	lcd8bit_L_14
$00D5	$	lcd8bit_L_12:
$00D5	$30C0			MOVLW	192
$00D6	$00B6			MOVWF	FARG_Lcd8_Chr
$00D7	$28E8			GOTO	lcd8bit_L_8
$00D8	$	lcd8bit_L_14:
$00D8	$	lcd8bit_L_16:
$00D8	$0836			MOVF	FARG_Lcd8_Chr, 0
$00D9	$3A03			XORLW	3
$00DA	$1D03			BTFSS	STATUS, Z
$00DB	$28DF			GOTO	lcd8bit_L_17
$00DC	$	lcd8bit_L_15:
$00DC	$3094			MOVLW	148
$00DD	$00B6			MOVWF	FARG_Lcd8_Chr
$00DE	$28E8			GOTO	lcd8bit_L_8
$00DF	$	lcd8bit_L_17:
$00DF	$	lcd8bit_L_19:
$00DF	$0836			MOVF	FARG_Lcd8_Chr, 0
$00E0	$3A04			XORLW	4
$00E1	$1D03			BTFSS	STATUS, Z
$00E2	$28E6			GOTO	lcd8bit_L_20
$00E3	$	lcd8bit_L_18:
$00E3	$30D4			MOVLW	212
$00E4	$00B6			MOVWF	FARG_Lcd8_Chr
$00E5	$28E8			GOTO	lcd8bit_L_8
$00E6	$	lcd8bit_L_20:
$00E6	$3080			MOVLW	128
$00E7	$00B6			MOVWF	FARG_Lcd8_Chr
$00E8	$	lcd8bit_L_8:
$00E8	$0837			MOVF	FARG_Lcd8_Chr+1, 0
$00E9	$0736			ADDWF	FARG_Lcd8_Chr, 0
$00EA	$00F0			MOVWF	STACK_0
$00EB	$03F0			DECF	STACK_0, 1
$00EC	$0870			MOVF	STACK_0, 0
$00ED	$00B6			MOVWF	FARG_Lcd8_Chr
$00EE	$0870			MOVF	STACK_0, 0
$00EF	$00BB			MOVWF	FARG_Lcd8_Cmd
$00F0	$2020			CALL	lcd8bit_lcd8_cmd
$00F1	$01A2			CLRF	lcd8bit_main_global_com, 1
$00F2	$0838			MOVF	FARG_Lcd8_Chr+2, 0
$00F3	$00BB			MOVWF	FARG_Lcd8_Cmd
$00F4	$2020			CALL	lcd8bit_lcd8_cmd
$00F5	$3001			MOVLW	1
$00F6	$00A2			MOVWF	lcd8bit_main_global_com
$00F7	$	lcd8bit_L_7:
$00F7	$0008			RETURN
$00F8	$	lcd8bit_lcd8_out:
$00F8	$	lcd8bit_L_26:
$00F8	$1303			BCF	STATUS, RP1
$00F9	$1283			BCF	STATUS, RP0
$00FA	$0836			MOVF	FARG_Lcd8_Out, 0
$00FB	$3A01			XORLW	1
$00FC	$1D03			BTFSS	STATUS, Z
$00FD	$2901			GOTO	lcd8bit_L_27
$00FE	$	lcd8bit_L_25:
$00FE	$3080			MOVLW	128
$00FF	$00B6			MOVWF	FARG_Lcd8_Out
$0100	$2918			GOTO	lcd8bit_L_24
$0101	$	lcd8bit_L_27:
$0101	$	lcd8bit_L_29:
$0101	$0836			MOVF	FARG_Lcd8_Out, 0
$0102	$3A02			XORLW	2
$0103	$1D03			BTFSS	STATUS, Z
$0104	$2908			GOTO	lcd8bit_L_30
$0105	$	lcd8bit_L_28:
$0105	$30C0			MOVLW	192
$0106	$00B6			MOVWF	FARG_Lcd8_Out
$0107	$2918			GOTO	lcd8bit_L_24
$0108	$	lcd8bit_L_30:
$0108	$	lcd8bit_L_32:
$0108	$0836			MOVF	FARG_Lcd8_Out, 0
$0109	$3A03			XORLW	3
$010A	$1D03			BTFSS	STATUS, Z
$010B	$290F			GOTO	lcd8bit_L_33
$010C	$	lcd8bit_L_31:
$010C	$3094			MOVLW	148
$010D	$00B6			MOVWF	FARG_Lcd8_Out
$010E	$2918			GOTO	lcd8bit_L_24
$010F	$	lcd8bit_L_33:
$010F	$	lcd8bit_L_35:
$010F	$0836			MOVF	FARG_Lcd8_Out, 0
$0110	$3A04			XORLW	4
$0111	$1D03			BTFSS	STATUS, Z
$0112	$2916			GOTO	lcd8bit_L_36
$0113	$	lcd8bit_L_34:
$0113	$30D4			MOVLW	212
$0114	$00B6			MOVWF	FARG_Lcd8_Out
$0115	$2918			GOTO	lcd8bit_L_24
$0116	$	lcd8bit_L_36:
$0116	$3080			MOVLW	128
$0117	$00B6			MOVWF	FARG_Lcd8_Out
$0118	$	lcd8bit_L_24:
$0118	$0837			MOVF	FARG_Lcd8_Out+1, 0
$0119	$0736			ADDWF	FARG_Lcd8_Out, 0
$011A	$00F0			MOVWF	STACK_0
$011B	$03F0			DECF	STACK_0, 1
$011C	$0870			MOVF	STACK_0, 0
$011D	$00B6			MOVWF	FARG_Lcd8_Out
$011E	$0870			MOVF	STACK_0, 0
$011F	$00BB			MOVWF	FARG_Lcd8_Cmd
$0120	$2020			CALL	lcd8bit_lcd8_cmd
$0121	$01A2			CLRF	lcd8bit_main_global_com, 1
$0122	$01B9			CLRF	lcd8bit_lcd8_out_local_i, 1
$0123	$0838			MOVF	FARG_Lcd8_Out+2, 0
$0124	$0084			MOVWF	FSR
$0125	$0800			MOVF	INDF, 0
$0126	$00BA			MOVWF	lcd8bit_lcd8_out_local_a
$0127	$	lcd8bit_L_38:
$0127	$083A			MOVF	lcd8bit_lcd8_out_local_a, 0
$0128	$3A00			XORLW	0
$0129	$1903			BTFSC	STATUS, Z
$012A	$2937			GOTO	lcd8bit_L_39
$012B	$083A			MOVF	lcd8bit_lcd8_out_local_a, 0
$012C	$00BB			MOVWF	FARG_Lcd8_Cmd
$012D	$2020			CALL	lcd8bit_lcd8_cmd
$012E	$0AB9			INCF	lcd8bit_lcd8_out_local_i, 1
$012F	$0839			MOVF	lcd8bit_lcd8_out_local_i, 0
$0130	$0738			ADDWF	FARG_Lcd8_Out+2, 0
$0131	$00F0			MOVWF	STACK_0
$0132	$0870			MOVF	STACK_0, 0
$0133	$0084			MOVWF	FSR
$0134	$0800			MOVF	INDF, 0
$0135	$00BA			MOVWF	lcd8bit_lcd8_out_local_a
$0136	$2927			GOTO	lcd8bit_L_38
$0137	$	lcd8bit_L_39:
$0137	$3001			MOVLW	1
$0138	$00A2			MOVWF	lcd8bit_main_global_com
$0139	$	lcd8bit_L_23:
$0139	$0008			RETURN
$013A	$	usartlib_u_a_usart_init:
$013A	$	usartlib_u_a_L_1:
$013A	$1303			BCF	STATUS, RP1
$013B	$1683			BSF	STATUS, RP0
$013C	$1698			BSF	TXSTA, 5
$013D	$	usartlib_u_a_L_2:
$013D	$3090			MOVLW	144
$013E	$1283			BCF	STATUS, RP0
$013F	$0098			MOVWF	RCSTA
$0140	$	usartlib_u_a_L_3:
$0140	$1683			BSF	STATUS, RP0
$0141	$1787			BSF	TRISC, 7
$0142	$	usartlib_u_a_L_4:
$0142	$1307			BCF	TRISC, 6
$0143	$	usartlib_u_a_L_6:
$0143	$	usartlib_u_a_L_8:
$0143	$3000			MOVLW	0
$0144	$1283			BCF	STATUS, RP0
$0145	$1A8C			BTFSC	PIR1, 5
$0146	$3001			MOVLW	1
$0147	$00F1			MOVWF	STACK_1
$0148	$0871			MOVF	STACK_1, 0
$0149	$3A01			XORLW	1
$014A	$1D03			BTFSS	STATUS, Z
$014B	$294D			GOTO	usartlib_u_a_L_9
$014C	$2943			GOTO	usartlib_u_a_L_8
$014D	$	usartlib_u_a_L_9:
$014D	$	usartlib_u_a_L_0:
$014D	$0008			RETURN
$014E	$	DisplayLCD_main:
^DisplayLCD.pbas, 50 :: 		dim x as char
$014E	$	DisplayLCD_main_main:
^DisplayLCD.pbas, 51 :: 		trise=0
$014E	$1303			BCF	STATUS, RP1
$014F	$1683			BSF	STATUS, RP0
$0150	$0189			CLRF	TRISE, 1
^DisplayLCD.pbas, 52 :: 		trisd=0
$0151	$0188			CLRF	TRISD, 1
^DisplayLCD.pbas, 53 :: 		adcon1=7                        'configura pinos de i/o
$0152	$3007			MOVLW	7
$0153	$009F			MOVWF	ADCON1
^DisplayLCD.pbas, 55 :: 		LCD8_Config(PORTE, PORTD, 2, 1, 0, 7, 6, 5, 4, 3, 2, 1, 0)  'configura pinos de controle e dados
$0154	$3009			MOVLW	PORTE
$0155	$1283			BCF	STATUS, RP0
$0156	$00B6			MOVWF	farg_Lcd8_Init
$0157	$3008			MOVLW	PORTD
$0158	$00B7			MOVWF	farg_Lcd8_Init+1
$0159	$2049			CALL	lcd8bit_lcd8_init
^DisplayLCD.pbas, 56 :: 		LCD8_Init(PORTE,PORTD)                                      'inicializa o lcd
$015A	$3009			MOVLW	PORTE
$015B	$00B6			MOVWF	FARG_Lcd8_Init
$015C	$3008			MOVLW	PORTD
$015D	$00B7			MOVWF	FARG_Lcd8_Init+1
$015E	$2049			CALL	lcd8bit_lcd8_init
^DisplayLCD.pbas, 58 :: 		loop_principal:
$015F	$	DisplayLCD_main_loop_principal:
^DisplayLCD.pbas, 60 :: 		usart_init(9600)
$015F	$3019			MOVLW	25
$0160	$1683			BSF	STATUS, RP0
$0161	$0099			MOVWF	SPBRG
$0162	$1518			BSF	TXSTA, BRGH
$0163	$213A			CALL	usartlib_u_a_usart_init
^DisplayLCD.pbas, 62 :: 		while 1
$0164	$	DisplayLCD_L_2:
^DisplayLCD.pbas, 64 :: 		if usart_data_ready=1 then
$0164	$20AC			CALL	usartlib_u_a_usart_data_ready
$0165	$0870			MOVF	STACK_0, 0
$0166	$3A01			XORLW	1
$0167	$1D03			BTFSS	STATUS, Z
$0168	$2973			GOTO	DisplayLCD_L_7
$0169	$	DisplayLCD_L_6:
^DisplayLCD.pbas, 65 :: 		x=usart_read
$0169	$20B7			CALL	usartlib_u_a_usart_read
$016A	$0870			MOVF	STACK_0, 0
$016B	$00A3			MOVWF	main_global_x
^DisplayLCD.pbas, 66 :: 		lcd8_chr(1,8,x)
$016C	$3001			MOVLW	1
$016D	$00B6			MOVWF	FARG_Lcd8_Chr
$016E	$3008			MOVLW	8
$016F	$00B7			MOVWF	FARG_Lcd8_Chr+1
$0170	$0870			MOVF	STACK_0, 0
$0171	$00B8			MOVWF	FARG_Lcd8_Chr+2
$0172	$20C8			CALL	lcd8bit_lcd8_chr
$0173	$	DisplayLCD_L_7:
^DisplayLCD.pbas, 68 :: 		END IF
$0173	$	DisplayLCD_L_8:
$0173	$2964			GOTO	DisplayLCD_L_2
^DisplayLCD.pbas, 91 :: 		Goto loop_principal               'Volta para a leitura do botão
$0174	$2974			GOTO	$
